<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig\Comment;

use Simplia\Api3\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a CommentReferenceApiEntity to fetch.
 */
final class CommentReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the comment; the same value as `Comment.id`.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }
}
