<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Document;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api\FieldConfig\StockItemApiFieldConfig;

/**
 * Which properties of a DocumentItemApiEntity to fetch.
 */
final class DocumentItemApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the line; the value `PUT /documents/{id}/rows/price` addresses in `items[].id`. Not a stock item id.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The line's text as printed on the document. Null when the stored text is empty.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Number of units the line covers. Negative on a document that issues goods. Null when not recorded.
     */
    public function withQuantity(): self {
        $this->fields['quantity'] = true;

        return $this;
    }

    /**
     * Unit price including VAT, in the shop's main currency. Null when the line has no price.
     */
    public function withPrice(): self {
        $this->fields['price'] = true;

        return $this;
    }

    /**
     * Unit price including VAT, in the document's own currency (the document's `currency`, or the shop's main currency when none is recorded). Null when the line has no price in that currency.
     */
    public function withPriceInDocumentCurrency(): self {
        $this->fields['price_in_document_currency'] = true;

        return $this;
    }

    /**
     * VAT rate applied to the line, as a percentage (21 for 21 %).
     */
    public function withVatRate(): self {
        $this->fields['vat_rate'] = true;

        return $this;
    }

    /**
     * What the line is: `item` (a stock item), `bundle` (a bundle of items), `discount`, `shipping` (delivery charge), `deposit` (an advance payment), `rounding` (cash rounding), `other`. Null when not recorded.
     */
    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    /**
     * The stock item the line refers to; the same record as `GET /stock-items/{id}`, any of its members selectable through `rows.stock_item.…`. Null for a line that is not a stock item, such as a discount, shipping, rounding or deposit line.
     */
    public function withStockItem(StockItemApiFieldConfig $config): self {
        $this->fields['stock_item'] = $config;

        return $this;
    }
}
