<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\AdminApiEntity;
use Simplia\Api\FieldConfig\AdminApiFieldConfig;
use Simplia\Api\Request\AdminsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/admins.
 */
final class AdminsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List staff accounts.
     * Permission: api:admins:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, AdminApiEntity>
     */
    public function iterate(AdminsApiRequest $request, AdminApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('admins', [], $request, $fields, $perPage) as $row) {
            yield new AdminApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(AdminsApiRequest $request): int {
        return $this->countList('admins', [], $request);
    }

    /**
     * Get a staff account.
     * Permission: api:admins:get.
     */
    public function get(int $id, AdminApiFieldConfig $fields): ?AdminApiEntity {
        $result = $this->singleResult('admins/' . $id, [], $fields);

        return $result === null ? null : new AdminApiEntity($result);
    }
}
