<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\ArticleApiEntity;
use Simplia\Api\FieldConfig\ArticleApiFieldConfig;
use Simplia\Api\Request\ArticlesApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/articles.
 */
final class ArticlesApiEndpoint extends AbstractApiEndpoint {
    /**
     * List articles.
     * Permission: api:articles:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, ArticleApiEntity>
     */
    public function iterate(ArticlesApiRequest $request, ArticleApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('articles', [], $request, $fields, $perPage) as $row) {
            yield new ArticleApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(ArticlesApiRequest $request): int {
        return $this->countList('articles', [], $request);
    }

    /**
     * Get an article.
     * Permission: api:articles:get.
     */
    public function get(int $id, ArticleApiFieldConfig $fields): ?ArticleApiEntity {
        $result = $this->singleResult('articles/' . $id, [], $fields);

        return $result === null ? null : new ArticleApiEntity($result);
    }
}
