<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\AttributeApiEntity;
use Simplia\Api3\FieldConfig\AttributeApiFieldConfig;
use Simplia\Api3\Request\AttributesApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/attributes.
 */
final class AttributesApiEndpoint extends AbstractApiEndpoint {
    /**
     * List attributes.
     * Permission: api:attributes:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, AttributeApiEntity>
     */
    public function iterate(AttributesApiRequest $request, AttributeApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('attributes', [], $request, $fields, $perPage) as $row) {
            yield new AttributeApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(AttributesApiRequest $request): int {
        return $this->countList('attributes', [], $request);
    }

    /**
     * Get an attribute.
     * Permission: api:attributes:get.
     */
    public function get(int $id, AttributeApiFieldConfig $fields): ?AttributeApiEntity {
        $result = $this->singleResult('attributes/' . $id, [], $fields);

        return $result === null ? null : new AttributeApiEntity($result);
    }
}
