<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\AvailabilityApiEntity;
use Simplia\Api\FieldConfig\AvailabilityApiFieldConfig;
use Simplia\Api\Request\AvailabilityApiRequest;

class AvailabilitiesApiEndpoint extends AbstractApiEndpoint {
    /**
     * List availabilities
     * @param AvailabilityApiRequest $request
     * @param AvailabilityApiFieldConfig $fields
     * @param int $batchSize
     * @return Generator|AvailabilityApiEntity[]
     */
    final public function iterate(
        AvailabilityApiRequest $request,
        AvailabilityApiFieldConfig $fields,
        int $batchSize = 100
    ): Generator {
        foreach ($this->iterateList('availabilities', [], $request, $fields, $batchSize) as $row) {
            yield new AvailabilityApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single availability
     */
    final public function get(int $id, AvailabilityApiFieldConfig $fields): ?AvailabilityApiEntity {
        $result = $this->singleResult('availabilities/' . $id, [], $fields);

        return $result ? new AvailabilityApiEntity($result) : null;
    }
}
