<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\BrandApiEntity;
use Simplia\Api\FieldConfig\BrandApiFieldConfig;
use Simplia\Api\Request\BrandsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/brands.
 */
final class BrandsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List brands.
     * Permission: api:brands:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, BrandApiEntity>
     */
    public function iterate(BrandsApiRequest $request, BrandApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('brands', [], $request, $fields, $perPage) as $row) {
            yield new BrandApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(BrandsApiRequest $request): int {
        return $this->countList('brands', [], $request);
    }

    /**
     * Get a brand.
     * Permission: api:brands:get.
     */
    public function get(int $id, BrandApiFieldConfig $fields): ?BrandApiEntity {
        $result = $this->singleResult('brands/' . $id, [], $fields);

        return $result === null ? null : new BrandApiEntity($result);
    }
}
