<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\StockItemApiEntity;
use Simplia\Api\FieldConfig\StockItemApiFieldConfig;
use Simplia\Api\Input\MultiPackTypeApiInput;

class BundleApiEndpoint extends AbstractApiEndpoint {
    /**
     * Set item as multi pack
     */
    final public function setMultiPack(
        int $item,
        MultiPackTypeApiInput $input,
        ?StockItemApiFieldConfig $fields = null
    ): StockItemApiEntity {
        $result = $this->request('PUT', 'bundles/' . $item . '/set-multi-pack', [], $input, $fields);

        return new StockItemApiEntity($result);
    }

    /**
     * Remove bundle configuration
     */
    final public function delete(int $item, ?StockItemApiFieldConfig $fields = null): StockItemApiEntity {
        $result = $this->request('DELETE', 'bundle/' . $item . '/', [], null, $fields);

        return new StockItemApiEntity($result);
    }
}
