<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\CashRegisterApiEntity;
use Simplia\Api\FieldConfig\CashRegisterApiFieldConfig;
use Simplia\Api\Request\CashRegistersApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/cash-registers.
 */
final class CashRegistersApiEndpoint extends AbstractApiEndpoint {
    /**
     * List cash registers.
     * Permission: api:cash-registers:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, CashRegisterApiEntity>
     */
    public function iterate(CashRegistersApiRequest $request, CashRegisterApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('cash-registers', [], $request, $fields, $perPage) as $row) {
            yield new CashRegisterApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(CashRegistersApiRequest $request): int {
        return $this->countList('cash-registers', [], $request);
    }

    /**
     * Get a cash register.
     * Permission: api:cash-registers:get.
     */
    public function get(int $id, CashRegisterApiFieldConfig $fields): ?CashRegisterApiEntity {
        $result = $this->singleResult('cash-registers/' . $id, [], $fields);

        return $result === null ? null : new CashRegisterApiEntity($result);
    }
}
