<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\CategoryApiEntity;
use Simplia\Api3\FieldConfig\CategoryApiFieldConfig;
use Simplia\Api3\Request\CategoriesApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/categories.
 */
final class CategoriesApiEndpoint extends AbstractApiEndpoint {
    /**
     * List categories.
     * Permission: api:categories:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, CategoryApiEntity>
     */
    public function iterate(CategoriesApiRequest $request, CategoryApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('categories', [], $request, $fields, $perPage) as $row) {
            yield new CategoryApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(CategoriesApiRequest $request): int {
        return $this->countList('categories', [], $request);
    }

    /**
     * Get a category.
     * Permission: api:categories:get.
     */
    public function get(int $id, CategoryApiFieldConfig $fields): ?CategoryApiEntity {
        $result = $this->singleResult('categories/' . $id, [], $fields);

        return $result === null ? null : new CategoryApiEntity($result);
    }
}
