<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\CommentApiEntity;
use Simplia\Api3\FieldConfig\CommentApiFieldConfig;
use Simplia\Api3\Request\CommentsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/comments.
 */
final class CommentsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List comments.
     * Permission: api:comments:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, CommentApiEntity>
     */
    public function iterate(CommentsApiRequest $request, CommentApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('comments', [], $request, $fields, $perPage) as $row) {
            yield new CommentApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(CommentsApiRequest $request): int {
        return $this->countList('comments', [], $request);
    }

    /**
     * Get a comment.
     * Permission: api:comments:get.
     */
    public function get(int $id, CommentApiFieldConfig $fields): ?CommentApiEntity {
        $result = $this->singleResult('comments/' . $id, [], $fields);

        return $result === null ? null : new CommentApiEntity($result);
    }
}
