<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\ContentGroupApiEntity;
use Simplia\Api\FieldConfig\ContentGroupApiFieldConfig;
use Simplia\Api\Request\ContentGroupsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/content-groups.
 */
final class ContentGroupsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List content groups.
     * Permission: api:content-groups:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, ContentGroupApiEntity>
     */
    public function iterate(ContentGroupsApiRequest $request, ContentGroupApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('content-groups', [], $request, $fields, $perPage) as $row) {
            yield new ContentGroupApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(ContentGroupsApiRequest $request): int {
        return $this->countList('content-groups', [], $request);
    }

    /**
     * Get a content group.
     * Permission: api:content-groups:get.
     */
    public function get(int $id, ContentGroupApiFieldConfig $fields): ?ContentGroupApiEntity {
        $result = $this->singleResult('content-groups/' . $id, [], $fields);

        return $result === null ? null : new ContentGroupApiEntity($result);
    }
}
