<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\DocumentApiEntity;
use Simplia\Api\FieldConfig\DocumentApiFieldConfig;
use Simplia\Api\Input\DocumentItemPricesApiInput;
use Simplia\Api\Request\DocumentApiRequest;

class DocumentsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List documents
     * @param DocumentApiRequest $request
     * @param DocumentApiFieldConfig $fields
     * @param int $batchSize
     * @return Generator|DocumentApiEntity[]
     */
    final public function iterate(
        DocumentApiRequest $request,
        DocumentApiFieldConfig $fields,
        int $batchSize = 100
    ): Generator {
        foreach ($this->iterateList('documents', [], $request, $fields, $batchSize) as $row) {
            yield new DocumentApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single document by code
     */
    final public function get(string $id, DocumentApiFieldConfig $fields): ?DocumentApiEntity {
        $result = $this->singleResult('documents/' . $id, [], $fields);

        return $result ? new DocumentApiEntity($result) : null;
    }

    /**
     * Update document item prices
     */
    final public function updateRowsPrices(
        string $id,
        DocumentItemPricesApiInput $input,
        ?DocumentApiFieldConfig $fields = null
    ): DocumentApiEntity {
        $result = $this->request('PUT', 'documents/' . $id . '/rows/price', [], $input, $fields);

        return new DocumentApiEntity($result);
    }
}
