<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\DocumentApiEntity;
use Simplia\Api3\FieldConfig\DocumentApiFieldConfig;
use Simplia\Api3\Input\DocumentItemPricesApiInput;
use Simplia\Api3\Input\StockDocumentApiInput;
use Simplia\Api3\Request\DocumentsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/documents.
 */
final class DocumentsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List documents.
     * Permission: api:documents:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, DocumentApiEntity>
     */
    public function iterate(DocumentsApiRequest $request, DocumentApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('documents', [], $request, $fields, $perPage) as $row) {
            yield new DocumentApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(DocumentsApiRequest $request): int {
        return $this->countList('documents', [], $request);
    }

    /**
     * Get a document by its human code.
     * Permission: api:documents:get.
     */
    public function getByCode(string $code, DocumentApiFieldConfig $fields): ?DocumentApiEntity {
        $result = $this->singleResult('documents/by-code/' . rawurlencode($code), [], $fields);

        return $result === null ? null : new DocumentApiEntity($result);
    }

    /**
     * Create a stock movement document.
     * Permission: api:documents:create-stock.
     * `$idempotencyKey` is sent as Idempotency-Key; a fresh UUID when null.
     */
    public function createStock(StockDocumentApiInput $input, ?DocumentApiFieldConfig $fields = null, ?string $idempotencyKey = null): DocumentApiEntity {
        $result = $this->request('POST', 'documents/stock', [], $input, $fields, RequestHandler::JSON, $idempotencyKey);

        return new DocumentApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Get a document.
     * Permission: api:documents:get.
     */
    public function get(int $id, DocumentApiFieldConfig $fields): ?DocumentApiEntity {
        $result = $this->singleResult('documents/' . $id, [], $fields);

        return $result === null ? null : new DocumentApiEntity($result);
    }

    /**
     * Re-price the rows of a document.
     * Permission: api:documents:update-price.
     */
    public function updatePrices(int $id, DocumentItemPricesApiInput $input, ?DocumentApiFieldConfig $fields = null): DocumentApiEntity {
        $result = $this->request('PUT', 'documents/' . $id . '/rows/price', [], $input, $fields);

        return new DocumentApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }
}
