<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\LogisticPlanApiEntity;
use Simplia\Api3\FieldConfig\LogisticPlanApiFieldConfig;
use Simplia\Api3\Request\LogisticPlansApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/logistic-plans.
 */
final class LogisticPlansApiEndpoint extends AbstractApiEndpoint {
    /**
     * List logistic plans.
     * Permission: api:logistic-plans:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, LogisticPlanApiEntity>
     */
    public function iterate(LogisticPlansApiRequest $request, LogisticPlanApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('logistic-plans', [], $request, $fields, $perPage) as $row) {
            yield new LogisticPlanApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(LogisticPlansApiRequest $request): int {
        return $this->countList('logistic-plans', [], $request);
    }

    /**
     * Get a logistic plan.
     * Permission: api:logistic-plans:get.
     */
    public function get(int $id, LogisticPlanApiFieldConfig $fields): ?LogisticPlanApiEntity {
        $result = $this->singleResult('logistic-plans/' . $id, [], $fields);

        return $result === null ? null : new LogisticPlanApiEntity($result);
    }
}
