<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\OrderApiEntity;
use Simplia\Api3\FieldConfig\OrderApiFieldConfig;
use Simplia\Api3\Input\OrderCreateApiInput;
use Simplia\Api3\Input\OrderPriorityApiInput;
use Simplia\Api3\Input\OrderStatusApiInput;
use Simplia\Api3\Input\OrderUpdateApiInput;
use Simplia\Api3\Request\OrdersApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/orders.
 */
final class OrdersApiEndpoint extends AbstractApiEndpoint {
    /**
     * List orders.
     * Permission: api:orders:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, OrderApiEntity>
     */
    public function iterate(OrdersApiRequest $request, OrderApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('orders', [], $request, $fields, $perPage) as $row) {
            yield new OrderApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(OrdersApiRequest $request): int {
        return $this->countList('orders', [], $request);
    }

    /**
     * Create an order.
     * Permission: api:orders:add.
     * `$idempotencyKey` is sent as Idempotency-Key; a fresh UUID when null.
     */
    public function create(OrderCreateApiInput $input, ?OrderApiFieldConfig $fields = null, ?string $idempotencyKey = null): OrderApiEntity {
        $result = $this->request('POST', 'orders', [], $input, $fields, RequestHandler::JSON, $idempotencyKey);

        return new OrderApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Get an order by its human code.
     * Permission: api:orders:get.
     */
    public function getByCode(string $code, OrderApiFieldConfig $fields): ?OrderApiEntity {
        $result = $this->singleResult('orders/by-code/' . rawurlencode($code), [], $fields);

        return $result === null ? null : new OrderApiEntity($result);
    }

    /**
     * Get an order.
     * Permission: api:orders:get.
     */
    public function get(int $id, OrderApiFieldConfig $fields): ?OrderApiEntity {
        $result = $this->singleResult('orders/' . $id, [], $fields);

        return $result === null ? null : new OrderApiEntity($result);
    }

    /**
     * Update an order.
     * Permission: api:orders:update.
     */
    public function update(int $id, OrderUpdateApiInput $input, ?OrderApiFieldConfig $fields = null): OrderApiEntity {
        $result = $this->request('PATCH', 'orders/' . $id, [], $input, $fields, RequestHandler::MERGE_PATCH);

        return new OrderApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Set order priority.
     * Permission: api:orders:put.
     */
    public function updatePriority(int $id, OrderPriorityApiInput $input, ?OrderApiFieldConfig $fields = null): OrderApiEntity {
        $result = $this->request('PUT', 'orders/' . $id . '/priority', [], $input, $fields);

        return new OrderApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Transition order status.
     * Permission: api:orders:put.
     */
    public function updateStatus(int $id, OrderStatusApiInput $input, ?OrderApiFieldConfig $fields = null): OrderApiEntity {
        $result = $this->request('PUT', 'orders/' . $id . '/status', [], $input, $fields);

        return new OrderApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }
}
