<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\OrderItemApiEntity;
use Simplia\Api\FieldConfig\OrderItemApiFieldConfig;
use Simplia\Api\Request\OrderItemsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/order-items.
 */
final class OrderItemsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List order lines.
     * Permission: api:order-items:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, OrderItemApiEntity>
     */
    public function iterate(OrderItemsApiRequest $request, OrderItemApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('order-items', [], $request, $fields, $perPage) as $row) {
            yield new OrderItemApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(OrderItemsApiRequest $request): int {
        return $this->countList('order-items', [], $request);
    }

    /**
     * Get an order line.
     * Permission: api:order-items:get.
     */
    public function get(int $id, OrderItemApiFieldConfig $fields): ?OrderItemApiEntity {
        $result = $this->singleResult('order-items/' . $id, [], $fields);

        return $result === null ? null : new OrderItemApiEntity($result);
    }
}
