<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\OrderApiEntity;
use Simplia\Api\FieldConfig\OrderFieldConfig;
use Simplia\Api\Input\OrderStatusTypeInput;
use Simplia\Api\Request\OrderRequest;

class OrdersEndpoint extends AbstractEndpoint {
    /**
     * List orders
     * @param OrderRequest $request
     * @param OrderFieldConfig $fields
     * @param int $batchSize
     * @return Generator|OrderApiEntity[]
     */
    final public function iterate(OrderRequest $request, OrderFieldConfig $fields, int $batchSize = 100): Generator {
        foreach ($this->iterateList('orders', [], $request, $fields, $batchSize) as $row) {
            yield new OrderApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single order by code
     */
    final public function get(string $id, OrderFieldConfig $fields): ?OrderApiEntity {
        $result = $this->singleResult('orders/' . $id, [], $fields);

        return $result ? new OrderApiEntity($result) : null;
    }

    /**
     * Change order status
     */
    final public function updateStatus(
        string $id,
        OrderStatusTypeInput $input,
        ?OrderFieldConfig $fields = null
    ): OrderApiEntity {
        $result = $this->request('put', 'orders/' . $id . '/status', [], $input, $fields);

        return new OrderApiEntity($result);
    }
}
