<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\PackageApiEntity;
use Simplia\Api\FieldConfig\PackageFieldConfig;
use Simplia\Api\Request\PackageRequest;

class PackagesEndpoint extends AbstractEndpoint {
    /**
     * List packages
     * @param PackageRequest $request
     * @param PackageFieldConfig $fields
     * @param int $batchSize
     * @return Generator|PackageApiEntity[]
     */
    final public function iterate(PackageRequest $request, PackageFieldConfig $fields, int $batchSize = 100): Generator {
        foreach ($this->iterateList('packages', [], $request, $fields, $batchSize) as $row) {
            yield new PackageApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single package
     */
    final public function get(int $id, PackageFieldConfig $fields): ?PackageApiEntity {
        $result = $this->singleResult('packages/' . $id, [], $fields);

        return $result ? new PackageApiEntity($result) : null;
    }
}
