<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\PaymentApiEntity;
use Simplia\Api\FieldConfig\PaymentFieldConfig;
use Simplia\Api\Request\PaymentRequest;

class PaymentsEndpoint extends AbstractEndpoint {
    /**
     * List payments
     * @param PaymentRequest $request
     * @param PaymentFieldConfig $fields
     * @param int $batchSize
     * @return Generator|PaymentApiEntity[]
     */
    final public function iterate(PaymentRequest $request, PaymentFieldConfig $fields, int $batchSize = 100): Generator {
        foreach ($this->iterateList('payments', [], $request, $fields, $batchSize) as $row) {
            yield new PaymentApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single payment by id
     */
    final public function get(string $id, PaymentFieldConfig $fields): ?PaymentApiEntity {
        $result = $this->singleResult('payments/' . $id, [], $fields);

        return $result ? new PaymentApiEntity($result) : null;
    }
}
