<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\PaymentApiEntity;
use Simplia\Api3\FieldConfig\PaymentApiFieldConfig;
use Simplia\Api3\Request\PaymentsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/payments.
 */
final class PaymentsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List payments.
     * Permission: api:payments:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, PaymentApiEntity>
     */
    public function iterate(PaymentsApiRequest $request, PaymentApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('payments', [], $request, $fields, $perPage) as $row) {
            yield new PaymentApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(PaymentsApiRequest $request): int {
        return $this->countList('payments', [], $request);
    }

    /**
     * Get a payment.
     * Permission: api:payments:get.
     */
    public function get(int $id, PaymentApiFieldConfig $fields): ?PaymentApiEntity {
        $result = $this->singleResult('payments/' . $id, [], $fields);

        return $result === null ? null : new PaymentApiEntity($result);
    }
}
