<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\PaymentMethodApiEntity;
use Simplia\Api\FieldConfig\PaymentMethodApiFieldConfig;
use Simplia\Api\Request\PaymentMethodApiRequest;

class PaymentMethodApiEndpoint extends AbstractApiEndpoint {
    /**
     * List payment methods
     * @param PaymentMethodApiRequest $request
     * @param PaymentMethodApiFieldConfig $fields
     * @param int $batchSize
     * @return Generator|PaymentMethodApiEntity[]
     */
    final public function iterate(
        PaymentMethodApiRequest $request,
        PaymentMethodApiFieldConfig $fields,
        int $batchSize = 100
    ): Generator {
        foreach ($this->iterateList('payment-methods', [], $request, $fields, $batchSize) as $row) {
            yield new PaymentMethodApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single payment method
     */
    final public function get(int $id, PaymentMethodApiFieldConfig $fields): ?PaymentMethodApiEntity {
        $result = $this->singleResult('payment-methods/' . $id, [], $fields);

        return $result ? new PaymentMethodApiEntity($result) : null;
    }
}
