<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\PriceApiEntity;
use Simplia\Api3\Entity\PricingApiEntity;
use Simplia\Api3\FieldConfig\PriceApiFieldConfig;
use Simplia\Api3\FieldConfig\PricingApiFieldConfig;
use Simplia\Api3\Input\PriceBatchApiInput;
use Simplia\Api3\Request\PricingsApiRequest;
use Simplia\Api3\Request\PricingsPricesApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/pricings.
 */
final class PricingsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List pricings.
     * Permission: api:pricing:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, PricingApiEntity>
     */
    public function iterate(PricingsApiRequest $request, PricingApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('pricings', [], $request, $fields, $perPage) as $row) {
            yield new PricingApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(PricingsApiRequest $request): int {
        return $this->countList('pricings', [], $request);
    }

    /**
     * Get a pricing.
     * Permission: api:pricing:get.
     */
    public function get(int $id, PricingApiFieldConfig $fields): ?PricingApiEntity {
        $result = $this->singleResult('pricings/' . $id, [], $fields);

        return $result === null ? null : new PricingApiEntity($result);
    }

    /**
     * List prices of a pricing.
     * Permission: api:pricing:list-prices.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, PriceApiEntity>
     */
    public function iteratePrices(int $pricingId, PricingsPricesApiRequest $request, PriceApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('pricings/' . $pricingId . '/prices', [], $request, $fields, $perPage) as $row) {
            yield new PriceApiEntity($row);
        }
    }

    /**
     * How many rows iteratePrices() would answer, without fetching them.
     */
    public function countPrices(int $pricingId, PricingsPricesApiRequest $request): int {
        return $this->countList('pricings/' . $pricingId . '/prices', [], $request);
    }

    /**
     * Batch-upsert prices.
     * Permission: api:pricing:batch-update-prices.
     * @return list<PriceApiEntity>
     */
    public function updatePrices(int $pricingId, PriceBatchApiInput $input, ?PriceApiFieldConfig $fields = null): array {
        $result = $this->request('PUT', 'pricings/' . $pricingId . '/prices/batch', [], $input, $fields);

        return array_values(array_map(static fn(array $row) => new PriceApiEntity($row), $result ?? []));
    }
}
