<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\ImageApiEntity;
use Simplia\Api\Entity\ProductApiEntity;
use Simplia\Api\FieldConfig\ImageApiFieldConfig;
use Simplia\Api\FieldConfig\ProductApiFieldConfig;
use Simplia\Api\Input\ProductCreateApiInput;
use Simplia\Api\Input\ProductImageUploadApiInput;
use Simplia\Api\Input\ProductUpdateApiInput;
use Simplia\Api\Request\ProductsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/products.
 */
final class ProductsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List products.
     * Permission: api:product:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, ProductApiEntity>
     */
    public function iterate(ProductsApiRequest $request, ProductApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('products', [], $request, $fields, $perPage) as $row) {
            yield new ProductApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(ProductsApiRequest $request): int {
        return $this->countList('products', [], $request);
    }

    /**
     * Create a product.
     * Permission: api:product:create.
     * `$idempotencyKey` is sent as Idempotency-Key; a fresh UUID when null.
     */
    public function create(ProductCreateApiInput $input, ?ProductApiFieldConfig $fields = null, ?string $idempotencyKey = null): ProductApiEntity {
        $result = $this->request('POST', 'products', [], $input, $fields, RequestHandler::JSON, $idempotencyKey);

        return new ProductApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Get a product.
     * Permission: api:product:get.
     */
    public function get(int $id, ProductApiFieldConfig $fields): ?ProductApiEntity {
        $result = $this->singleResult('products/' . $id, [], $fields);

        return $result === null ? null : new ProductApiEntity($result);
    }

    /**
     * Update a product.
     * Permission: api:product:update.
     */
    public function update(int $id, ProductUpdateApiInput $input, ?ProductApiFieldConfig $fields = null): ProductApiEntity {
        $result = $this->request('PATCH', 'products/' . $id, [], $input, $fields, RequestHandler::MERGE_PATCH);

        return new ProductApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Upload a product image.
     * Permission: api:product:add-image.
     * `$idempotencyKey` is sent as Idempotency-Key; a fresh UUID when null.
     */
    public function uploadImage(int $id, ProductImageUploadApiInput $input, ?ImageApiFieldConfig $fields = null, ?string $idempotencyKey = null): ImageApiEntity {
        $result = $this->request('POST', 'products/' . $id . '/upload-image', [], $input, $fields, RequestHandler::JSON, $idempotencyKey);

        return new ImageApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }
}
