<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\DocumentApiEntity;
use Simplia\Api\Entity\StockRoomApiEntity;
use Simplia\Api\FieldConfig\DocumentApiFieldConfig;
use Simplia\Api\FieldConfig\StockRoomApiFieldConfig;
use Simplia\Api\Input\StockAmountBatchApiInput;
use Simplia\Api\Request\StockRoomsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/stock-rooms.
 */
final class StockRoomsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List stock rooms.
     * Permission: api:stock-rooms:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, StockRoomApiEntity>
     */
    public function iterate(StockRoomsApiRequest $request, StockRoomApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('stock-rooms', [], $request, $fields, $perPage) as $row) {
            yield new StockRoomApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(StockRoomsApiRequest $request): int {
        return $this->countList('stock-rooms', [], $request);
    }

    /**
     * Get a stock room.
     * Permission: api:stock-rooms:get.
     */
    public function get(int $id, StockRoomApiFieldConfig $fields): ?StockRoomApiEntity {
        $result = $this->singleResult('stock-rooms/' . $id, [], $fields);

        return $result === null ? null : new StockRoomApiEntity($result);
    }

    /**
     * Batch stock-amount adjustment.
     * Permission: api:stock-items:batch-update-stock-amount.
     * @return list<DocumentApiEntity>
     */
    public function adjustStockAmounts(int $stockRoom, StockAmountBatchApiInput $input, ?DocumentApiFieldConfig $fields = null): array {
        $result = $this->request('PUT', 'stock-rooms/' . $stockRoom . '/stock-amount-adjustments', [], $input, $fields);

        return array_values(array_map(static fn(array $row) => new DocumentApiEntity($row), $result ?? []));
    }
}
