<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\StockItemApiEntity;
use Simplia\Api\FieldConfig\StockItemApiFieldConfig;
use Simplia\Api\Input\BundleApiInput;
use Simplia\Api\Input\StockItemBatchUpdateApiInput;
use Simplia\Api\Input\StockItemLocationApiInput;
use Simplia\Api\Request\StockItemsApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/stock-items.
 */
final class StockItemsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List stock items.
     * Permission: api:stock-items:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, StockItemApiEntity>
     */
    public function iterate(StockItemsApiRequest $request, StockItemApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('stock-items', [], $request, $fields, $perPage) as $row) {
            yield new StockItemApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(StockItemsApiRequest $request): int {
        return $this->countList('stock-items', [], $request);
    }

    /**
     * Batch-update stock items.
     * Permission: api:stock-items:batch-update.
     * @return list<StockItemApiEntity>
     */
    public function batchUpdate(StockItemBatchUpdateApiInput $input, ?StockItemApiFieldConfig $fields = null): array {
        $result = $this->request('PUT', 'stock-items/batch', [], $input, $fields);

        return array_values(array_map(static fn(array $row) => new StockItemApiEntity($row), $result ?? []));
    }

    /**
     * Get a stock item.
     * Permission: api:stock-items:get.
     */
    public function get(int $id, StockItemApiFieldConfig $fields): ?StockItemApiEntity {
        $result = $this->singleResult('stock-items/' . $id, [], $fields);

        return $result === null ? null : new StockItemApiEntity($result);
    }

    /**
     * Set a stock item location.
     * Permission: api:stock-items:update-location.
     */
    public function updateLocation(int $id, int $stockRoom, StockItemLocationApiInput $input, ?StockItemApiFieldConfig $fields = null): StockItemApiEntity {
        $result = $this->request('PUT', 'stock-items/' . $id . '/location/' . $stockRoom, [], $input, $fields);

        return new StockItemApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Set the part list of a bundle.
     * Permission: api:bundle:update.
     */
    public function setBundle(int $item, BundleApiInput $input, ?StockItemApiFieldConfig $fields = null): StockItemApiEntity {
        $result = $this->request('PUT', 'stock-items/' . $item . '/bundle', [], $input, $fields);

        return new StockItemApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Delete a bundle.
     * Permission: api:bundle:delete.
     */
    public function deleteBundle(int $item, ?StockItemApiFieldConfig $fields = null): StockItemApiEntity {
        $result = $this->request('DELETE', 'stock-items/' . $item . '/bundle', [], null, $fields);

        return new StockItemApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }
}
