<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Generator;
use Simplia\Api\Entity\StockStorageCenterApiEntity;
use Simplia\Api\FieldConfig\StockStorageCenterApiFieldConfig;
use Simplia\Api\Request\StockStorageCenterApiRequest;

class StorageCentersApiEndpoint extends AbstractApiEndpoint {
    /**
     * List storage centers
     * @param StockStorageCenterApiRequest $request
     * @param StockStorageCenterApiFieldConfig $fields
     * @param int $batchSize
     * @return Generator|StockStorageCenterApiEntity[]
     */
    final public function iterate(
        StockStorageCenterApiRequest $request,
        StockStorageCenterApiFieldConfig $fields,
        int $batchSize = 100
    ): Generator {
        foreach ($this->iterateList('storage-centers', [], $request, $fields, $batchSize) as $row) {
            yield new StockStorageCenterApiEntity($row);
        }
        yield from [];
    }

    /**
     * Get single storage center
     */
    final public function get(int $id, StockStorageCenterApiFieldConfig $fields): ?StockStorageCenterApiEntity {
        $result = $this->singleResult('storage-centers/' . $id, [], $fields);

        return $result ? new StockStorageCenterApiEntity($result) : null;
    }
}
