<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\StorageCenterApiEntity;
use Simplia\Api\FieldConfig\StorageCenterApiFieldConfig;
use Simplia\Api\Request\StorageCentersApiRequest;
use Simplia\Api\RequestHandler;

/**
 * The operations of /api/3/storage-centers.
 */
final class StorageCentersApiEndpoint extends AbstractApiEndpoint {
    /**
     * List storage centers.
     * Permission: api:storage-centers:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, StorageCenterApiEntity>
     */
    public function iterate(StorageCentersApiRequest $request, StorageCenterApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('storage-centers', [], $request, $fields, $perPage) as $row) {
            yield new StorageCenterApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(StorageCentersApiRequest $request): int {
        return $this->countList('storage-centers', [], $request);
    }

    /**
     * Get a storage center.
     * Permission: api:storage-centers:get.
     */
    public function get(int $id, StorageCenterApiFieldConfig $fields): ?StorageCenterApiEntity {
        $result = $this->singleResult('storage-centers/' . $id, [], $fields);

        return $result === null ? null : new StorageCenterApiEntity($result);
    }
}
