<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\StorageLocationApiEntity;
use Simplia\Api3\Entity\StorageLocationItemApiEntity;
use Simplia\Api3\FieldConfig\StorageLocationApiFieldConfig;
use Simplia\Api3\FieldConfig\StorageLocationItemApiFieldConfig;
use Simplia\Api3\Request\StorageLocationsApiRequest;
use Simplia\Api3\Request\StorageLocationsItemsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/storage-locations.
 */
final class StorageLocationsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List storage locations.
     * Permission: api:storage-locations:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, StorageLocationApiEntity>
     */
    public function iterate(StorageLocationsApiRequest $request, StorageLocationApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('storage-locations', [], $request, $fields, $perPage) as $row) {
            yield new StorageLocationApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(StorageLocationsApiRequest $request): int {
        return $this->countList('storage-locations', [], $request);
    }

    /**
     * Get a storage location.
     * Permission: api:storage-locations:get.
     */
    public function get(int $id, StorageLocationApiFieldConfig $fields): ?StorageLocationApiEntity {
        $result = $this->singleResult('storage-locations/' . $id, [], $fields);

        return $result === null ? null : new StorageLocationApiEntity($result);
    }

    /**
     * List the stock items at a storage location.
     * Permission: api:storage-locations:list-items.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, StorageLocationItemApiEntity>
     */
    public function iterateItems(int $id, StorageLocationsItemsApiRequest $request, StorageLocationItemApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('storage-locations/' . $id . '/items', [], $request, $fields, $perPage) as $row) {
            yield new StorageLocationItemApiEntity($row);
        }
    }

    /**
     * How many rows iterateItems() would answer, without fetching them.
     */
    public function countItems(int $id, StorageLocationsItemsApiRequest $request): int {
        return $this->countList('storage-locations/' . $id . '/items', [], $request);
    }
}
