<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\SupplierApiEntity;
use Simplia\Api3\FieldConfig\SupplierApiFieldConfig;
use Simplia\Api3\Request\SuppliersApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/suppliers.
 */
final class SuppliersApiEndpoint extends AbstractApiEndpoint {
    /**
     * List suppliers.
     * Permission: api:suppliers:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, SupplierApiEntity>
     */
    public function iterate(SuppliersApiRequest $request, SupplierApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('suppliers', [], $request, $fields, $perPage) as $row) {
            yield new SupplierApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(SuppliersApiRequest $request): int {
        return $this->countList('suppliers', [], $request);
    }

    /**
     * Get a supplier.
     * Permission: api:suppliers:get.
     */
    public function get(int $id, SupplierApiFieldConfig $fields): ?SupplierApiEntity {
        $result = $this->singleResult('suppliers/' . $id, [], $fields);

        return $result === null ? null : new SupplierApiEntity($result);
    }
}
