<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\UserGroupApiEntity;
use Simplia\Api3\FieldConfig\UserGroupApiFieldConfig;
use Simplia\Api3\Request\UserGroupsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/user-groups.
 */
final class UserGroupsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List customer groups.
     * Permission: api:user-groups:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, UserGroupApiEntity>
     */
    public function iterate(UserGroupsApiRequest $request, UserGroupApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('user-groups', [], $request, $fields, $perPage) as $row) {
            yield new UserGroupApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(UserGroupsApiRequest $request): int {
        return $this->countList('user-groups', [], $request);
    }

    /**
     * Get a customer group.
     * Permission: api:user-groups:get.
     */
    public function get(int $id, UserGroupApiFieldConfig $fields): ?UserGroupApiEntity {
        $result = $this->singleResult('user-groups/' . $id, [], $fields);

        return $result === null ? null : new UserGroupApiEntity($result);
    }
}
