<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Endpoint;

use Simplia\Api3\Entity\VariantApiEntity;
use Simplia\Api3\FieldConfig\VariantApiFieldConfig;
use Simplia\Api3\Input\VariantCreateApiInput;
use Simplia\Api3\Input\VariantUpdateApiInput;
use Simplia\Api3\Request\VariantsApiRequest;
use Simplia\Api3\RequestHandler;

/**
 * The operations of /api/3/variants.
 */
final class VariantsApiEndpoint extends AbstractApiEndpoint {
    /**
     * List variants.
     * Permission: api:variant:list.
     * Every row, page by page (the Link header is followed for you).
     * @return \Generator<int, VariantApiEntity>
     */
    public function iterate(VariantsApiRequest $request, VariantApiFieldConfig $fields, int $perPage = 100): \Generator {
        foreach ($this->iterateList('variants', [], $request, $fields, $perPage) as $row) {
            yield new VariantApiEntity($row);
        }
    }

    /**
     * How many rows iterate() would answer, without fetching them.
     */
    public function count(VariantsApiRequest $request): int {
        return $this->countList('variants', [], $request);
    }

    /**
     * Create a variant.
     * Permission: api:variant:create.
     * `$idempotencyKey` is sent as Idempotency-Key; a fresh UUID when null.
     */
    public function create(VariantCreateApiInput $input, ?VariantApiFieldConfig $fields = null, ?string $idempotencyKey = null): VariantApiEntity {
        $result = $this->request('POST', 'variants', [], $input, $fields, RequestHandler::JSON, $idempotencyKey);

        return new VariantApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }

    /**
     * Get a variant.
     * Permission: api:variant:get.
     */
    public function get(int $id, VariantApiFieldConfig $fields): ?VariantApiEntity {
        $result = $this->singleResult('variants/' . $id, [], $fields);

        return $result === null ? null : new VariantApiEntity($result);
    }

    /**
     * Update a variant.
     * Permission: api:variant:update.
     */
    public function update(int $id, VariantUpdateApiInput $input, ?VariantApiFieldConfig $fields = null): VariantApiEntity {
        $result = $this->request('PATCH', 'variants/' . $id, [], $input, $fields, RequestHandler::MERGE_PATCH);

        return new VariantApiEntity($result ?? throw new \UnexpectedValueException('The API answered without a body.'));
    }
}
