<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Endpoint;

use Simplia\Api\Entity\VoucherApiEntity;
use Simplia\Api\FieldConfig\VoucherFieldConfig;
use Simplia\Api\Input\VoucherActivateTypeInput;
use Simplia\Api\Input\VoucherApplyTypeInput;

class VoucherEndpoint extends AbstractEndpoint {
    /**
     * Find by code
     * @param string $code
     */
    final public function getOneByCode(string $code, VoucherFieldConfig $fields): ?VoucherApiEntity {
        $query = [];
        $query['code'] = $code;
        $result = $this->singleResult('voucher/find', $query, $fields);

        return $result ? new VoucherApiEntity($result) : null;
    }

    /**
     * Activate prepared voucher
     * @param string $code
     */
    final public function activate(
        VoucherActivateTypeInput $input,
        string $code,
        ?VoucherFieldConfig $fields = null
    ): VoucherApiEntity {
        $query = [];
        $query['code'] = $code;
        $result = $this->request('put', 'voucher/activate', $query, $input, $fields);

        return new VoucherApiEntity($result);
    }

    /**
     * Apply voucher
     * @param string $code
     */
    final public function apply(
        VoucherApplyTypeInput $input,
        string $code,
        ?VoucherFieldConfig $fields = null
    ): VoucherApiEntity {
        $query = [];
        $query['code'] = $code;
        $result = $this->request('put', 'voucher/apply', $query, $input, $fields);

        return new VoucherApiEntity($result);
    }

    /**
     * Get single voucher
     * @param string $id
     */
    final public function get(string $id, VoucherFieldConfig $fields): ?VoucherApiEntity {
        $query = [];
        $query['id'] = $id;
        $result = $this->singleResult('voucher/', $query, $fields);

        return $result ? new VoucherApiEntity($result) : null;
    }
}
