<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\VoucherGroup;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a VoucherGroupReferenceApiEntity to fetch.
 */
final class VoucherGroupReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the group; the same value as `VoucherGroup.id`, and the value VoucherCreateInput.group_id takes.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the group as shown in the shop's administration.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }
}
