<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Comment;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\FieldConfig\Comment\CommentReferenceApiFieldConfig;

/**
 * A pointer at another comment: its id; the whole record is `GET /comments/{id}`.
 */
final class CommentReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the comment; the same value as `Comment.id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    public static function createFieldConfig(): CommentReferenceApiFieldConfig {
        return new CommentReferenceApiFieldConfig();
    }
}
