<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\FieldConfig\AdminApiFieldConfig;

/**
 * A staff account of the shop: a person who works in its administration, or a credential that calls its API — the record `Order.created_by` and `Document.issued_by` point at. Not a customer. Nothing an account signs in with is published. Inactive accounts are listed too.
 */
final class AdminApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the staff account; the value `Order.created_by.id` and `Document.issued_by.id` carry.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Given name. Null when not filled.
     */
    public function getFirstName(): ?string {
        return $this->readStringOrNull('first_name');
    }

    /**
     * Family name. Null when not filled.
     */
    public function getLastName(): ?string {
        return $this->readStringOrNull('last_name');
    }

    /**
     * Whether the account is enabled. A disabled account can neither sign in nor call the API; an enabled one may still be limited by the shop's own sign-in rules. An inactive account is kept for the orders and documents that name it.
     */
    public function isActive(): bool {
        return $this->readBool('active');
    }

    /**
     * Kind of account: `standard` (a person using the administration), `api` (a credential created for calling the API) or `integration` (the account an installed integration calls as).
     * @return 'standard'|'api'|'integration'
     * @phpstan-return string
     */
    public function getType(): string {
        return $this->readString('type');
    }

    public static function createFieldConfig(): AdminApiFieldConfig {
        return new AdminApiFieldConfig();
    }
}
