<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\FieldConfig\ArticleApiFieldConfig;

/**
 * A blog or news article of the shop: headline, teaser, HTML body, publication time and the path it is published at. Articles of every language of the shop are listed together, inactive ones included.
 */
final class ArticleApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the article.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Headline of the article. Null when none is stored.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Teaser shown in listings, as HTML. Null when the article has none.
     */
    public function getAnnotation(): ?string {
        return $this->readStringOrNull('annotation');
    }

    /**
     * Body of the article, as HTML. Null when the article has none.
     */
    public function getText(): ?string {
        return $this->readStringOrNull('text');
    }

    /**
     * When the article is published. Null when no date is set; such articles are listed too.
     */
    public function getPublishedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('published_at');
    }

    /**
     * Path of the article on the shop's site, relative to the shop origin, such as `/blog/new-products`. Null when the article has no address.
     */
    public function getUrl(): ?string {
        return $this->readStringOrNull('url');
    }

    public static function createFieldConfig(): ArticleApiFieldConfig {
        return new ArticleApiFieldConfig();
    }
}
