<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\Attribute\AttributeValueApiEntity;
use Simplia\Api\Enum\AttributeAppliesTo;
use Simplia\Api\Enum\AttributeMeaning;
use Simplia\Api\Enum\AttributeType;
use Simplia\Api\FieldConfig\AttributeApiFieldConfig;

/**
 * A product attribute: a named property — a colour, a material, a length — with its unit, its kind (a text, a number, a yes/no, one choice or several out of a list) and, for a choice attribute, the values to choose from. The vocabulary a product's `attributes` list is written in; a row of that list names its attribute by `id`.
 */
final class AttributeApiEntity extends AbstractApiEntity {
    /**
     * Attribute id, the `attribute.id` a row of a product's `attributes` carries.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name in the request language. Null when the attribute has no name in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Unit of the value in the request language ("cm", "kg"), as the shop wrote it. Null when the attribute has none.
     */
    public function getUnit(): ?string {
        return $this->readStringOrNull('unit');
    }

    /**
     * What a value of the attribute is: `text`, `integer` or `boolean` (a product stores one `value`, as text), `choice` (one of `values`) or `multi_choice` (several of `values`).
     */
    public function getType(): AttributeType {
        return $this->readEnum('type', AttributeType::class);
    }

    /**
     * What the attribute stands for, when the shop marked it: `size`, `color`, `gender`, `material`, `pattern`, `age_group`, `collection` or `season`. Null when it stands for nothing in particular.
     */
    public function getMeaning(): ?AttributeMeaning {
        return $this->readEnumOrNull('meaning', AttributeMeaning::class);
    }

    /**
     * The kind of record the attribute describes: `product` (it appears in a product's `attributes`), `brand`, `store`, `customer` or `article`. Null for a kind this document does not name.
     */
    public function getAppliesTo(): ?AttributeAppliesTo {
        return $this->readEnumOrNull('applies_to', AttributeAppliesTo::class);
    }

    /**
     * Whether the storefront shows the attribute at all.
     */
    public function isActive(): bool {
        return $this->readBool('active');
    }

    /**
     * Whether the storefront shows the attribute on the product's page.
     */
    public function isOnDetail(): bool {
        return $this->readBool('on_detail');
    }

    /**
     * Whether the storefront offers the attribute as a filter of a product list.
     */
    public function isInFilter(): bool {
        return $this->readBool('in_filter');
    }

    /**
     * Position among the shop's attributes; lower first. The order of `sort=priority` and of a product's `attributes` list.
     */
    public function getPriority(): int {
        return $this->readInt('priority');
    }

    /**
     * A picture standing for the attribute, when the shop stored one. Null when none is stored.
     */
    public function getImage(): ?ImageApiEntity {
        return $this->readEntityOrNull('image', ImageApiEntity::class);
    }

    /**
     * For a `choice` or `multi_choice` attribute, the values a product can carry, in the shop's order (`priority`, then id). Empty for the other kinds.
     * @return list<AttributeValueApiEntity>
     */
    public function getValues(): array {
        return $this->readEntities('values', AttributeValueApiEntity::class);
    }

    public static function createFieldConfig(): AttributeApiFieldConfig {
        return new AttributeApiFieldConfig();
    }
}
