<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\FieldConfig\AvailabilityApiFieldConfig;

/**
 * An entry of the shop's availability list: the delivery promise a product can carry, such as in stock or 1 week, labeled in the request language. The identifier is the number of hours the customer waits.
 */
final class AvailabilityApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the availability; by the shop's convention also the number of hours until the goods are available, 0 meaning in stock. The value `StockItem.availability_hours` carries.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The shop's own label for this availability, in the request language.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    public static function createFieldConfig(): AvailabilityApiFieldConfig {
        return new AvailabilityApiFieldConfig();
    }
}
