<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\CallFieldConfig;

class CallApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getDate(): string {
        return $this->returnField('date');
    }

    public function getName(): string {
        return $this->returnField('name');
    }

    public function getNumber(): string {
        return $this->returnField('number');
    }

    public function isIncoming(): bool {
        return $this->returnField('incoming');
    }

    public function getLength(): string {
        return $this->returnField('length');
    }

    public function getRecorder(): string {
        return $this->returnField('recorder');
    }

    public function isConnected(): bool {
        return $this->returnField('connected');
    }

    final public static function createFieldConfig(): CallFieldConfig {
        return new CallFieldConfig();
    }
}
