<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\CashRegisterApiFieldConfig;

class CashRegisterApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getName(): string {
        return $this->returnField('name');
    }

    public function getStore(): ?StoreApiEntity {
        return $this->returnField('store', StoreApiEntity::class);
    }

    final public static function createFieldConfig(): CashRegisterApiFieldConfig {
        return new CashRegisterApiFieldConfig();
    }
}
