<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\CategoryApiEntity as CategoryApiEntity1;
use Simplia\Api\Enum\CategoryType;
use Simplia\Api\FieldConfig\CategoryApiFieldConfig;

/**
 * A category of the catalog tree, the record `Product.main_category` and `Product.categories` point at: its place in the tree, its texts in the request language and its customs data. The list holds the content group (storefront tree) of the storefront being called, or the one `content_group` names; any category can be read by id. Inactive categories are listed too.
 */
final class CategoryApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the category; the value `Product.main_category.id` carries and the `category` filter of `GET /products` takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Category name in the request language. Null when the category has no text in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Names of the category and its ancestors, root first, joined by `|`, such as `Phones|Apple|iPhone`. An ancestor without a name in the request language leaves an empty segment.
     */
    public function getPath(): string {
        return $this->readString('path');
    }

    /**
     * Identifiers of the category and its ancestors, root first, this category last; one entry per segment of `path`.
     * @return list<int>
     */
    public function getPathIds(): array {
        return $this->readIntList('path_ids');
    }

    /**
     * The category this one sits under, selectable to any depth up the tree; the same record as `GET /categories/{id}`. Null for a root of the tree.
     */
    public function getParent(): ?CategoryApiEntity {
        return $this->readEntityOrNull('parent', CategoryApiEntity::class);
    }

    /**
     * Depth in the tree: 0 for a root, 1 for its subcategories, and so on; one less than the number of entries of `path_ids`.
     */
    public function getLevel(): int {
        return $this->readInt('level');
    }

    /**
     * Display order among the categories that share the same parent, lowest first. Null when never set.
     */
    public function getPosition(): ?int {
        return $this->readIntOrNull('position');
    }

    /**
     * Kind of category: `normal` (products are assigned to it), `alias` (a link to another category, whose products and page it shows) or `automatic` (its products are selected by a rule).
     */
    public function getType(): CategoryType {
        return $this->readEnum('type', CategoryType::class);
    }

    /**
     * Whether the category is shown on the storefront. An inactive category keeps its products and its place in the tree.
     */
    public function isActive(): bool {
        return $this->readBool('active');
    }

    /**
     * The shop's own code for the category. Null when none is set.
     */
    public function getCode(): ?string {
        return $this->readStringOrNull('code');
    }

    /**
     * Path of the category's page on the storefront in the request language, such as `/phones/apple/`; for an `alias` category, the path of the category it links to. Null when the category has no page in that language.
     */
    public function getUrl(): ?string {
        return $this->readStringOrNull('url');
    }

    /**
     * Number of active products in the category and its subcategories, as the shop last counted them; a parent includes the products of its children, and an `alias` category mirrors the count of the category it links to. Null when never counted.
     */
    public function getProductCount(): ?int {
        return $this->readIntOrNull('product_count');
    }

    /**
     * Harmonized System code the category's products are declared under on customs documents when a product carries no code of its own. Null when none is set.
     */
    public function getHsCode(): ?string {
        return $this->readStringOrNull('hs_code');
    }

    /**
     * Name of the goods as written on customs documents for the category's products. Null when none is set.
     */
    public function getCustomsName(): ?string {
        return $this->readStringOrNull('customs_name');
    }

    /**
     * The category's main picture. Null when none is stored.
     */
    public function getImage(): ?ImageApiEntity {
        return $this->readEntityOrNull('image', ImageApiEntity::class);
    }

    /**
     * A small picture of the category, for a menu or a tile, wherever the storefront's template puts it. Null when none is stored.
     */
    public function getIcon(): ?ImageApiEntity {
        return $this->readEntityOrNull('icon', ImageApiEntity::class);
    }

    /**
     * A background picture for the category's page. Null when none is stored.
     */
    public function getBackground(): ?ImageApiEntity {
        return $this->readEntityOrNull('background', ImageApiEntity::class);
    }

    /**
     * The background picture for narrow screens, when the storefront's template uses one. Null when none is stored.
     */
    public function getBackgroundMobile(): ?ImageApiEntity {
        return $this->readEntityOrNull('background_mobile', ImageApiEntity::class);
    }

    /**
     * The content group (storefront tree) the category belongs to; its `id` is the value the `content_group` filter takes.
     */
    public function getContentGroup(): ContentGroupApiEntity {
        return $this->readEntity('content_group', ContentGroupApiEntity::class);
    }

    /**
     * When the category was last written — a change to the category itself or a refresh of its product count — RFC 3339 with offset.
     */
    public function getUpdatedAt(): \DateTimeImmutable {
        return $this->readDateTime('updated_at');
    }

    public static function createFieldConfig(): CategoryApiFieldConfig {
        return new CategoryApiFieldConfig();
    }
}
