<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\CategoryApiFieldConfig;

class CategoryApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getName(): string {
        return $this->returnField('name');
    }

    public function getPath(): string {
        return $this->returnField('path');
    }

    final public static function createFieldConfig(): CategoryApiFieldConfig {
        return new CategoryApiFieldConfig();
    }
}
