<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\Entity\Admin\AdminReferenceApiEntity;
use Simplia\Api3\Entity\Article\ArticleReferenceApiEntity;
use Simplia\Api3\Entity\Category\CategoryReferenceApiEntity;
use Simplia\Api3\Entity\Comment\CommentReferenceApiEntity;
use Simplia\Api3\Entity\Product\ProductReferenceApiEntity;
use Simplia\Api3\FieldConfig\CommentApiFieldConfig;

/**
 * A comment a customer or a staff member wrote under a product, a category or an article of the shop, with the star rating given with it and its moderation state. Comments of every state are listed together; a reply is a comment of its own that points at the one it answers.
 */
final class CommentApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the comment.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * What the comment was written under: a `product`, a `category` or an `article`. The matching one of `product`, `category` and `article` is set.
     * @return 'product'|'category'|'article'
     * @phpstan-return string
     */
    public function getSubject(): string {
        return $this->readString('subject');
    }

    /**
     * The product the comment was written under. Null unless `subject` is `product`.
     */
    public function getProduct(): ?ProductReferenceApiEntity {
        return $this->readEntityOrNull('product', ProductReferenceApiEntity::class);
    }

    /**
     * The category the comment was written under. Null unless `subject` is `category`.
     */
    public function getCategory(): ?CategoryReferenceApiEntity {
        return $this->readEntityOrNull('category', CategoryReferenceApiEntity::class);
    }

    /**
     * The article the comment was written under. Null unless `subject` is `article`.
     */
    public function getArticle(): ?ArticleReferenceApiEntity {
        return $this->readEntityOrNull('article', ArticleReferenceApiEntity::class);
    }

    /**
     * The comment this one replies to. Null for a comment that starts a thread; the `parent` filter lists the replies of a comment.
     */
    public function getParent(): ?CommentReferenceApiEntity {
        return $this->readEntityOrNull('parent', CommentReferenceApiEntity::class);
    }

    /**
     * The title the writer gave the comment. Null when none was given.
     */
    public function getTitle(): ?string {
        return $this->readStringOrNull('title');
    }

    /**
     * The name the writer gave. Null when none was given.
     */
    public function getAuthor(): ?string {
        return $this->readStringOrNull('author');
    }

    /**
     * The e-mail address the writer gave, as stored. Null when none was given.
     */
    public function getEmail(): ?string {
        return $this->readStringOrNull('email');
    }

    /**
     * The phone number the writer gave, as stored. Null when none was given.
     */
    public function getPhone(): ?string {
        return $this->readStringOrNull('phone');
    }

    /**
     * The staff account that wrote the comment, when a staff member wrote it in the shop's administration: a reply, or a comment of the shop's own. Null for a customer's comment.
     */
    public function getStaff(): ?AdminReferenceApiEntity {
        return $this->readEntityOrNull('staff', AdminReferenceApiEntity::class);
    }

    /**
     * The comment, as plain text with its line breaks. Null when empty.
     */
    public function getText(): ?string {
        return $this->readStringOrNull('text');
    }

    /**
     * Moderation state: `pending` (waiting for the shop's approval), `approved`. A rejected comment is deleted, so no third state exists.
     * @return 'pending'|'approved'
     * @phpstan-return string
     */
    public function getStatus(): string {
        return $this->readString('status');
    }

    /**
     * When the comment was approved. Null while it is pending.
     */
    public function getApprovedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('approved_at');
    }

    /**
     * The star rating given with the comment, 0 to 5 stars. Null when none was given.
     */
    public function getRating(): ?int {
        return $this->readIntOrNull('rating');
    }

    /**
     * When the comment was written. The value the list sorts on by default.
     */
    public function getCreatedAt(): \DateTimeImmutable {
        return $this->readDateTime('created_at');
    }

    public static function createFieldConfig(): CommentApiFieldConfig {
        return new CommentApiFieldConfig();
    }
}
