<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\DocumentFieldConfig;

class DocumentApiEntity extends AbstractApiEntity {
    public function getId(): string {
        return $this->returnField('id');
    }

    public function getDateIssued(): string {
        return $this->returnField('date_issued');
    }

    public function getDueDate(): string {
        return $this->returnField('due_date');
    }

    public function getVatDate(): string {
        return $this->returnField('vat_date');
    }

    public function getCurrency(): string {
        return $this->returnField('currency');
    }

    public function getCurrencyRate(): float {
        return $this->returnField('currency_rate');
    }

    public function getNote(): string {
        return $this->returnField('note');
    }

    public function getType(): string {
        return $this->returnField('type');
    }

    public function getSubtype(): string {
        return $this->returnField('subtype');
    }

    public function getVariableSymbol(): string {
        return $this->returnField('variable_symbol');
    }

    public function getRows(): array {
        return $this->returnField('rows');
    }

    public function getCustomerAddress(): ContactApiEntity {
        return $this->returnField('customer_address', ContactApiEntity::class);
    }

    public function getStockRoom(): StockRoomApiEntity {
        return $this->returnField('stock_room', StockRoomApiEntity::class);
    }

    public function getRelevantDocument(): DocumentApiEntity {
        return $this->returnField('relevant_document', DocumentApiEntity::class);
    }

    public function getRelevantDocuments(): array {
        return $this->returnField('relevant_documents');
    }

    public function getPayments(): array {
        return $this->returnField('payments');
    }

    final public static function createFieldConfig(): DocumentFieldConfig {
        return new DocumentFieldConfig();
    }
}
