<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\DocumentItemPriceApiEntity;
use Simplia\Api\FieldConfig\DocumentItemPricesApiFieldConfig;

class DocumentItemPricesApiEntity extends AbstractApiEntity {
    /**
     * @return DocumentItemPriceApiEntity[]
     */
    public function getItems(): array {
        return $this->returnFieldArray('items', DocumentItemPriceApiEntity::class);
    }

    final public static function createFieldConfig(): DocumentItemPricesApiFieldConfig {
        return new DocumentItemPricesApiFieldConfig();
    }
}
