<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\DocumentItemPriceApiFieldConfig;

class DocumentItemPriceApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getPrice(): float {
        return $this->returnField('price');
    }

    public function getVatRate(): float {
        return $this->returnField('vat_rate');
    }

    final public static function createFieldConfig(): DocumentItemPriceApiFieldConfig {
        return new DocumentItemPriceApiFieldConfig();
    }
}
