<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\DocumentApiEntity as DocumentApiEntity1;
use Simplia\Api\FieldConfig\DocumentApiFieldConfig;

class DocumentApiEntity extends AbstractApiEntity {
    public function getId(): string {
        return $this->returnField('id');
    }

    public function getDateIssued(): string {
        return $this->returnField('date_issued');
    }

    public function getDueDate(): ?string {
        return $this->returnField('due_date');
    }

    public function getVatDate(): ?string {
        return $this->returnField('vat_date');
    }

    public function getCurrency(): string {
        return $this->returnField('currency');
    }

    public function getCurrencyRate(): float {
        return $this->returnField('currency_rate');
    }

    public function getNote(): ?string {
        return $this->returnField('note');
    }

    public function getType(): string {
        return $this->returnField('type');
    }

    public function getSubtype(): ?string {
        return $this->returnField('subtype');
    }

    public function getVariableSymbol(): ?string {
        return $this->returnField('variable_symbol');
    }

    /**
     * @return DocumentItemApiEntity[]
     */
    public function getRows(): array {
        return $this->returnFieldArray('rows', DocumentItemApiEntity::class);
    }

    public function getCustomerAddress(): ?ContactApiEntity {
        return $this->returnField('customer_address', ContactApiEntity::class);
    }

    public function getStockRoom(): ?StockRoomApiEntity {
        return $this->returnField('stock_room', StockRoomApiEntity::class);
    }

    public function getRelevantDocument(): ?DocumentApiEntity {
        return $this->returnField('relevant_document', DocumentApiEntity::class);
    }

    /**
     * @return DocumentApiEntity[]
     */
    public function getRelevantDocuments(): array {
        return $this->returnFieldArray('relevant_documents', DocumentApiEntity::class);
    }

    /**
     * @return PaymentApiEntity[]
     */
    public function getPayments(): array {
        return $this->returnFieldArray('payments', PaymentApiEntity::class);
    }

    final public static function createFieldConfig(): DocumentApiFieldConfig {
        return new DocumentApiFieldConfig();
    }
}
