<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\DocumentItemPricesFieldConfig;

class DocumentItemPricesApiEntity extends AbstractApiEntity {
    public function getItems(): array {
        return $this->returnField('items');
    }

    final public static function createFieldConfig(): DocumentItemPricesFieldConfig {
        return new DocumentItemPricesFieldConfig();
    }
}
