<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\FieldConfig\EmailMessageApiFieldConfig;

/**
 * The receipt for a sent e-mail: the identifier the mail server assigned to the message. Nothing is stored and there is no way to fetch it later.
 */
final class EmailMessageApiEntity extends AbstractApiEntity {
    /**
     * Message-ID the mail transport assigned to the message handed to the mail server; use it to correlate with mail logs. Where sending is suppressed, the fixed value `debug-suppressed`.
     */
    public function getMessageId(): string {
        return $this->readString('message_id');
    }

    public static function createFieldConfig(): EmailMessageApiFieldConfig {
        return new EmailMessageApiFieldConfig();
    }
}
