<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\ImageApiFieldConfig;

class ImageApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getHashMd5(): string {
        return $this->returnField('hash_md5');
    }

    final public static function createFieldConfig(): ImageApiFieldConfig {
        return new ImageApiFieldConfig();
    }
}
