<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\LogisticPlanApiFieldConfig;

/**
 * A named set of rules for moving stock between the shop's stock rooms automatically: which rooms restock which, and which kinds of demand count. A stock item is assigned one with PUT /stock-items/batch.
 */
final class LogisticPlanApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the plan; the value StockItemUpdateInput.logistic_plan_id takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the plan.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    /**
     * Whether demand from retail customer orders counts for this plan's transfers.
     */
    public function isActiveRetail(): bool {
        return $this->readBool('active_retail');
    }

    /**
     * Whether demand from wholesale customer orders counts for this plan's transfers.
     */
    public function isActiveWholesale(): bool {
        return $this->readBool('active_wholesale');
    }

    /**
     * Whether demand from repair jobs counts for this plan's transfers.
     */
    public function isActiveRepair(): bool {
        return $this->readBool('active_repair');
    }

    public static function createFieldConfig(): LogisticPlanApiFieldConfig {
        return new LogisticPlanApiFieldConfig();
    }
}
