<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\Order\ContactApiEntity;
use Simplia\Api\Entity\Order\OrderDiscountApiEntity;
use Simplia\Api\Entity\Order\OrderItemApiEntity;
use Simplia\Api\Entity\Order\OrderPackagingApiEntity;
use Simplia\Api\Entity\Order\PackageApiEntity;
use Simplia\Api\Entity\Order\PaymentApiEntity;
use Simplia\Api\FieldConfig\OrderApiFieldConfig;
use Simplia\Api\Money;

/**
 * A customer order: what was ordered, by whom, where it goes, how it is paid, and everything the shop has done with it since — payments received, shipments sent, documents issued, warehouse sessions. It moves through unprocessed, processed, waiting, ready and finished, or is cancelled.
 */
final class OrderApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the order. The address of every write, and the value `OrderItem.order_id` and the `order_id` filter of `GET /packages` carry.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The order number shown to customers and staff. Readable by `GET /orders/by-code/{code}`. Null when the order has no number yet.
     */
    public function getCode(): ?string {
        return $this->readStringOrNull('code');
    }

    /**
     * The order's identifier in the system it came from: a marketplace order id, or the value supplied when the order was created through this API. Null for an order placed in the shop itself.
     */
    public function getExternalCode(): ?string {
        return $this->readStringOrNull('external_code');
    }

    /**
     * Address of the shop (domain) the order was placed on. Null when it was not recorded.
     */
    public function getShopUrl(): ?string {
        return $this->readStringOrNull('shop_url');
    }

    /**
     * Public link at which the customer can follow this order. Null when the shop it was placed on no longer exists.
     */
    public function getOnlineUrl(): ?string {
        return $this->readStringOrNull('online_url');
    }

    /**
     * When the order was placed.
     */
    public function getCreatedAt(): \DateTimeImmutable {
        return $this->readDateTime('created_at');
    }

    /**
     * Day before which the order must not be dispatched, as asked by the customer or an operator. Null when dispatch is not postponed.
     */
    public function getDelayedUntilDate(): ?\DateTimeImmutable {
        return $this->readDateOrNull('delayed_until_date');
    }

    /**
     * Day the shop expects to dispatch the order: an estimate, not an instruction. Null when there is no estimate.
     */
    public function getExpectedDispatchDate(): ?\DateTimeImmutable {
        return $this->readDateOrNull('expected_dispatch_date');
    }

    /**
     * When the order entered its current `status`. Null when no transition has been recorded.
     */
    public function getStatusChangedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('status_changed_at');
    }

    /**
     * When the customer took delivery of the goods, as reported by the carrier. Null until then, and null for an order without an invoice.
     */
    public function getPickedUpAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('picked_up_at');
    }

    /**
     * ISO 4217 code of the currency the customer ordered in. Empty when the order has no currency recorded.
     */
    public function getCurrency(): string {
        return $this->readString('currency');
    }

    /**
     * Whether the order is handled by an external fulfillment partner rather than the shop's own warehouse.
     */
    public function isFulfillment(): bool {
        return $this->readBool('fulfillment');
    }

    /**
     * Numeric identifier of the marketplace the order was imported from, as the marketplace connector reports it. Null for an order that did not come through a marketplace.
     */
    public function getMarketplaceSourceId(): ?int {
        return $this->readIntOrNull('marketplace_source_id');
    }

    /**
     * Name of the marketplace the order was imported from, as the connector reports it (for example `Amazon`). Null for an order that did not come through a marketplace.
     */
    public function getMarketplaceSource(): ?string {
        return $this->readStringOrNull('marketplace_source');
    }

    /**
     * Where the order stands: `unprocessed` (new, not yet handled), `processed` (accepted for processing), `waiting` (on hold, for stock or payment), `ready` (picked and packed, waiting for the carrier), `finished` (dispatched), `cancelled`. Empty for an order whose stored state has no public value.
     * @return 'unprocessed'|'processed'|'waiting'|'ready'|'finished'|'cancelled'
     * @phpstan-return string
     */
    public function getStatus(): string {
        return $this->readString('status');
    }

    /**
     * Exchange rate frozen on the order: how many units of the shop's main currency one unit of `currency` is worth. 0 when no rate was recorded.
     */
    public function getCurrencyRate(): float {
        return $this->readFloat('currency_rate');
    }

    /**
     * Code of the carrier that delivers the order, such as `ppl`, `ups` or `gls`; `pickup` when the customer collects in person or no carrier is set.
     */
    public function getCarrierCode(): ?string {
        return $this->readStringOrNull('carrier_code');
    }

    /**
     * Identifier of the pickup point or parcel shop the customer chose, in the carrier's own format. Null when the delivery goes to an address.
     */
    public function getBranchCode(): ?string {
        return $this->readStringOrNull('branch_code');
    }

    /**
     * Shipping and handling charged on the order, including VAT, in the shop's main currency.
     */
    public function getDeliveryPrice(): Money {
        return $this->readMoney('delivery_price');
    }

    /**
     * Shipping and handling charged on the order, including VAT, in the order's own currency (`currency`): the amount the customer saw.
     */
    public function getDeliveryPriceInOrderCurrency(): Money {
        return $this->readMoney('delivery_price_in_order_currency');
    }

    /**
     * Shipping and handling charged on the order, without VAT, in the shop's main currency.
     */
    public function getDeliveryPriceWithoutVat(): Money {
        return $this->readMoney('delivery_price_without_vat');
    }

    /**
     * Shipping and handling charged on the order, without VAT, in the order's own currency (`currency`).
     */
    public function getDeliveryPriceWithoutVatInOrderCurrency(): Money {
        return $this->readMoney('delivery_price_without_vat_in_order_currency');
    }

    /**
     * Label of the delivery and payment combination the customer chose, as it was named at the time. Null when not recorded.
     */
    public function getDeliveryName(): ?string {
        return $this->readStringOrNull('delivery_name');
    }

    /**
     * How the customer chose to pay: `cash_on_delivery` (pay the courier), `online` (card or payment gateway), `bank_transfer`, `cash` (in person), `against_invoice` (invoiced, paid later). Null for a payment type without a public value.
     */
    public function getPaymentType(): ?string {
        return $this->readStringOrNull('payment_type');
    }

    /**
     * The note the customer wrote with the order. Null when there is none.
     */
    public function getNote(): ?string {
        return $this->readStringOrNull('note');
    }

    /**
     * Note to print on the invoice. Null when there is none.
     */
    public function getInvoiceNote(): ?string {
        return $this->readStringOrNull('invoice_note');
    }

    /**
     * Payment reference (variable symbol) the customer quotes on a bank transfer, derived from the order number. Null when the order has no number.
     */
    public function getVariableSymbol(): ?string {
        return $this->readStringOrNull('variable_symbol');
    }

    /**
     * How urgently the warehouse should handle the order: 0 normal, 1 important, 2 urgent, 3 emergency. Set with `PUT /orders/{id}/priority`.
     */
    public function getPriority(): int {
        return $this->readInt('priority');
    }

    /**
     * Grand total of the order including VAT: the lines, minus discounts, plus shipping, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPrice(): Money {
        return $this->readMoney('total_price');
    }

    /**
     * Grand total of the order including VAT, in the order's own currency (`currency`): what the customer was charged. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPriceInOrderCurrency(): Money {
        return $this->readMoney('total_price_in_order_currency');
    }

    /**
     * Grand total of the order without VAT, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPriceWithoutVat(): Money {
        return $this->readMoney('total_price_without_vat');
    }

    /**
     * Grand total of the order without VAT, in the order's own currency (`currency`). Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPriceWithoutVatInOrderCurrency(): Money {
        return $this->readMoney('total_price_without_vat_in_order_currency');
    }

    /**
     * Sum of the payments received against the order, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPaid(): Money {
        return $this->readMoney('total_paid');
    }

    /**
     * Sum of the payments received against the order, in the order's own currency (`currency`): a payment made in that currency counts as paid; one made in another currency is converted from the shop's main currency at `currency_rate`. Null when such a conversion is impossible because the order has no exchange rate. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function getTotalPaidInOrderCurrency(): ?Money {
        return $this->readMoneyOrNull('total_paid_in_order_currency');
    }

    /**
     * The shipping method the order uses; the same object as `GET /transport-methods/{id}`. Null when none is linked.
     */
    public function getTransportMethod(): ?TransportMethodApiEntity {
        return $this->readEntityOrNull('transport_method', TransportMethodApiEntity::class);
    }

    /**
     * The payment method the order uses; the same object as `GET /payment-methods/{id}`. Null when none is linked.
     */
    public function getPaymentMethod(): ?PaymentMethodApiEntity {
        return $this->readEntityOrNull('payment_method', PaymentMethodApiEntity::class);
    }

    /**
     * The store the order is assigned to. Null when it is not assigned to one.
     */
    public function getStore(): ?StoreApiEntity {
        return $this->readEntityOrNull('store', StoreApiEntity::class);
    }

    /**
     * The store the order was entered at, when it was created at a point of sale. Null otherwise.
     */
    public function getCreatedStore(): ?StoreApiEntity {
        return $this->readEntityOrNull('created_store', StoreApiEntity::class);
    }

    /**
     * The staff account that entered the order; the same record as `GET /admins/{id}`. Null when the customer placed it online.
     */
    public function getCreatedBy(): ?AdminApiEntity {
        return $this->readEntityOrNull('created_by', AdminApiEntity::class);
    }

    /**
     * The storage center that fulfills the order; changed with `PATCH /orders/{id}`. Null when none is assigned.
     */
    public function getStorageCenter(): ?StorageCenterApiEntity {
        return $this->readEntityOrNull('storage_center', StorageCenterApiEntity::class);
    }

    /**
     * The registered customer account that placed the order; the same record as `GET /users/{id}`. Null for a guest order.
     */
    public function getUser(): ?UserApiEntity {
        return $this->readEntityOrNull('user', UserApiEntity::class);
    }

    /**
     * Where the goods are delivered. Null when no delivery address is recorded.
     */
    public function getDeliveryAddress(): ?ContactApiEntity {
        return $this->readEntityOrNull('delivery_address', ContactApiEntity::class);
    }

    /**
     * Who is billed. Null when no separate billing address is recorded.
     */
    public function getInvoiceAddress(): ?ContactApiEntity {
        return $this->readEntityOrNull('invoice_address', ContactApiEntity::class);
    }

    /**
     * The ordered lines. Cancelled lines are not included.
     * @return list<OrderItemApiEntity>
     */
    public function getItems(): array {
        return $this->readEntities('items', OrderItemApiEntity::class);
    }

    /**
     * Payments recorded against the order.
     * @return list<PaymentApiEntity>
     */
    public function getPayments(): array {
        return $this->readEntities('payments', PaymentApiEntity::class);
    }

    /**
     * Closed documents issued for the order; each the same record as `GET /documents/{id}`, selectable through `documents.…`.
     * @return list<DocumentApiEntity>
     */
    public function getDocuments(): array {
        return $this->readEntities('documents', DocumentApiEntity::class);
    }

    /**
     * Discounts applied to the order, each shown as its own line.
     * @return list<OrderDiscountApiEntity>
     */
    public function getDiscounts(): array {
        return $this->readEntities('discounts', OrderDiscountApiEntity::class);
    }

    /**
     * Shipments sent for the order.
     * @return list<PackageApiEntity>
     */
    public function getPackages(): array {
        return $this->readEntities('packages', PackageApiEntity::class);
    }

    /**
     * Warehouse picking and packing sessions logged for the order.
     * @return list<OrderPackagingApiEntity>
     */
    public function getPackagingHistories(): array {
        return $this->readEntities('packaging_histories', OrderPackagingApiEntity::class);
    }

    public static function createFieldConfig(): OrderApiFieldConfig {
        return new OrderApiFieldConfig();
    }
}
