<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity;

use Simplia\Api3\FieldConfig\PaymentMethodApiFieldConfig;

/**
 * A way to pay offered at checkout, such as card, cash on delivery or bank transfer, in the request language. The same method has a different id in each language.
 */
final class PaymentMethodApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the payment method in the request language; the same value as Order.payment_method.id, and what OrderDeliveryInput.payment_method_id takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the payment method as shown to customers, in the request language.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    public static function createFieldConfig(): PaymentMethodApiFieldConfig {
        return new PaymentMethodApiFieldConfig();
    }
}
