<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Enum\PriceSource;
use Simplia\Api\FieldConfig\PriceApiFieldConfig;
use Simplia\Api\Money;

/**
 * One stock item's price in one price list: the stored row, not the price a shopper is charged (no fallback to another list, no conversion, no rounding, no check of the discount window). Prices have no address of their own; they are read and written through their price list.
 */
final class PriceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the price row. Usable only in the `ids` filter of `GET /pricings/{pricing_id}/prices`; writes address a price by `stock_item_id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Identifier of the stock item the price is for; the same value as `StockItem.id`, and the key a batch write addresses.
     */
    public function getStockItemId(): int {
        return $this->readInt('stock_item_id');
    }

    /**
     * Code (SKU) of the stock item, for convenience; the same value as `StockItem.code`. Null when the item has none.
     */
    public function getStockItemCode(): ?string {
        return $this->readStringOrNull('stock_item_code');
    }

    /**
     * The list price of the item in this price list, in the list's currency. A zero is a real zero price.
     */
    public function getValue(): Money {
        return $this->readMoney('value');
    }

    /**
     * The discounted price of the item in the list's currency, meant for the discount window; not checked against today's date. Null when no discounted price is stored.
     */
    public function getValueAfterDiscount(): ?Money {
        return $this->readMoneyOrNull('value_after_discount');
    }

    /**
     * First day the discounted price applies. Stored as a calendar date, so the time part is always midnight. Null when there is no start bound.
     */
    public function getDiscountStartsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('discount_starts_at');
    }

    /**
     * Last day the discounted price applies. Stored as a calendar date, so the time part is always midnight. Null when there is no end bound.
     */
    public function getDiscountEndsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('discount_ends_at');
    }

    /**
     * Where the stored value came from: `manual` (entered by a person, an import or this API), `bot` (an automated repricing job), `fallback` (derived from another price list).
     */
    public function getSource(): PriceSource {
        return $this->readEnum('source', PriceSource::class);
    }

    public static function createFieldConfig(): PriceApiFieldConfig {
        return new PriceApiFieldConfig();
    }
}
