<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\PricingApiFieldConfig;

/**
 * A price list: a named, coded set of prices per stock item in one currency, with an on/off switch, a precedence number and an optional validity window. The shop picks one active list per currency and customer at request time. Read-only here; lists are configured in the shop's administration. Inactive and expired lists are listed too.
 */
final class PricingApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the price list; the `{pricing_id}` of the price operations.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the price list as shown in the shop's administration.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    /**
     * Stable code of the price list, unique across price lists.
     */
    public function getCode(): string {
        return $this->readString('code');
    }

    /**
     * ISO 4217 code of the currency every price in this list is in, and the currency a batch write must send.
     */
    public function getCurrency(): string {
        return $this->readString('currency');
    }

    /**
     * Whether the list takes part in price selection. An inactive list is ignored by the storefront but still readable here.
     */
    public function isActive(): bool {
        return $this->readBool('active');
    }

    /**
     * Precedence among price lists: the lowest number wins when several lists match. Unique across lists.
     */
    public function getPriority(): int {
        return $this->readInt('priority');
    }

    /**
     * When the list becomes eligible for selection. Null when there is no start bound.
     */
    public function getStartsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('starts_at');
    }

    /**
     * When the list stops being eligible for selection. Null when it never expires.
     */
    public function getEndsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('ends_at');
    }

    public static function createFieldConfig(): PricingApiFieldConfig {
        return new PricingApiFieldConfig();
    }
}
