<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\Product\ProductReferenceApiEntity;
use Simplia\Api\Entity\Review\OrderReferenceApiEntity;
use Simplia\Api\Entity\Review\ReviewDetailsApiEntity;
use Simplia\Api\Entity\Review\ReviewReferenceApiEntity;
use Simplia\Api\Entity\Review\ReviewReplyApiEntity;
use Simplia\Api\Enum\ReviewSource;
use Simplia\Api\Enum\ReviewStatus;
use Simplia\Api\Enum\ReviewSubject;
use Simplia\Api\FieldConfig\ReviewApiFieldConfig;

/**
 * A customer review of a product or of an order (the shopping experience as a whole), written in the shop's own review form or imported from a price-comparison portal such as Heureka. Reviews of every language and moderation state are listed together; `status` says whether the shop approved the review for showing.
 */
final class ReviewApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the review.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * What the review is about: a `product`, or an `order` (the shopping experience as a whole).
     */
    public function getSubject(): ReviewSubject {
        return $this->readEnum('subject', ReviewSubject::class);
    }

    /**
     * Where the review came from: `shop` for one written in the shop's own review form, otherwise the price-comparison portal it was imported from (Heureka, Zboží.cz, Biano, Árukereső, Compari or Pazaruvaj).
     */
    public function getSource(): ReviewSource {
        return $this->readEnum('source', ReviewSource::class);
    }

    /**
     * Moderation state: `pending` (not yet decided), `approved` (may be shown), `rejected`.
     */
    public function getStatus(): ReviewStatus {
        return $this->readEnum('status', ReviewStatus::class);
    }

    /**
     * The reviewed product. Null for a review of an order.
     */
    public function getProduct(): ?ProductReferenceApiEntity {
        return $this->readEntityOrNull('product', ProductReferenceApiEntity::class);
    }

    /**
     * The order the review is linked to: the reviewed order, or the order the reviewed product was bought in. Null when there is none or it was deleted.
     */
    public function getOrder(): ?OrderReferenceApiEntity {
        return $this->readEntityOrNull('order', OrderReferenceApiEntity::class);
    }

    /**
     * The name the reviewer gave, as it is shown with the review. Null when none was given.
     */
    public function getAuthor(): ?string {
        return $this->readStringOrNull('author');
    }

    /**
     * Overall rating, 0 to 5 stars. Null when the reviewer gave none.
     */
    public function getRating(): ?int {
        return $this->readIntOrNull('rating');
    }

    /**
     * The review text, as written. Null when the reviewer wrote none.
     */
    public function getText(): ?string {
        return $this->readStringOrNull('text');
    }

    /**
     * What the reviewer liked, when the form asked for it separately. Null when none was given.
     */
    public function getPros(): ?string {
        return $this->readStringOrNull('pros');
    }

    /**
     * What the reviewer disliked, when the form asked for it separately. Null when none was given.
     */
    public function getCons(): ?string {
        return $this->readStringOrNull('cons');
    }

    /**
     * The further answers of an order review: whether the customer recommends the shop and the star ratings of the delivery, the transport, the website, the communication and the pick-up. Null when the review stores none of them, which is the case for a product review.
     */
    public function getDetails(): ?ReviewDetailsApiEntity {
        return $this->readEntityOrNull('details', ReviewDetailsApiEntity::class);
    }

    /**
     * The pictures the reviewer attached, in the shop's order. Empty when there are none.
     * @return list<ImageApiEntity>
     */
    public function getImages(): array {
        return $this->readEntities('images', ImageApiEntity::class);
    }

    /**
     * The shop's reply to the review: the one written in the shop, or, for an imported review, the one the shop gave on the portal. Null when there is none.
     */
    public function getReply(): ?ReviewReplyApiEntity {
        return $this->readEntityOrNull('reply', ReviewReplyApiEntity::class);
    }

    /**
     * The language the review is written in, as the shop's own language code.
     */
    public function getLanguage(): string {
        return $this->readString('language');
    }

    /**
     * The review this one is a machine translation of. Null when this review is the original.
     */
    public function getOriginal(): ?ReviewReferenceApiEntity {
        return $this->readEntityOrNull('original', ReviewReferenceApiEntity::class);
    }

    /**
     * The identifier the review carries on the portal it was imported from. Null when the review carries none.
     */
    public function getExternalId(): ?string {
        return $this->readStringOrNull('external_id');
    }

    /**
     * When the review was written. The value the list sorts on by default.
     */
    public function getCreatedAt(): \DateTimeImmutable {
        return $this->readDateTime('created_at');
    }

    public static function createFieldConfig(): ReviewApiFieldConfig {
        return new ReviewApiFieldConfig();
    }
}
