<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\StockItemAmountApiFieldConfig;

class StockItemAmountApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getStockRoom(): StockRoomApiEntity {
        return $this->returnField('stock_room', StockRoomApiEntity::class);
    }

    public function getStockItem(): StockItemApiEntity {
        return $this->returnField('stock_item', StockItemApiEntity::class);
    }

    public function getStockAmount(): int {
        return $this->returnField('stock_amount');
    }

    public function getReservedAmount(): int {
        return $this->returnField('reserved_amount');
    }

    public function getMinimalAmount(): int {
        return $this->returnField('minimal_amount');
    }

    public function getOptimalAmount(): int {
        return $this->returnField('optimal_amount');
    }

    public function getMaximalAmount(): int {
        return $this->returnField('maximal_amount');
    }

    final public static function createFieldConfig(): StockItemAmountApiFieldConfig {
        return new StockItemAmountApiFieldConfig();
    }
}
