<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\StockItemFieldConfig;

class StockItemApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getCode(): string {
        return $this->returnField('code');
    }

    public function getCodeSupplier(): string {
        return $this->returnField('code_supplier');
    }

    public function getEan(): string {
        return $this->returnField('ean');
    }

    public function getFullPrice(): float {
        return $this->returnField('full_price');
    }

    public function getTotalStockAmount(): int {
        return $this->returnField('total_stock_amount');
    }

    public function getAvailabilityHours(): int {
        return $this->returnField('availability_hours');
    }

    public function getName(): string {
        return $this->returnField('name');
    }

    public function getStorageLocations(): array {
        return $this->returnField('storage_locations');
    }

    public function getProduct(): ProductApiEntity {
        return $this->returnField('product', ProductApiEntity::class);
    }

    public function getVariant(): VariantApiEntity {
        return $this->returnField('variant', VariantApiEntity::class);
    }

    final public static function createFieldConfig(): StockItemFieldConfig {
        return new StockItemFieldConfig();
    }
}
