<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\StorageCenterApiFieldConfig;

/**
 * A storage center: a site, branch or depot that owns one or more stock rooms. Centers that are inactive are listed too.
 */
final class StorageCenterApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the storage center; the value Order.storage_center.id and StockRoom.storage_center.id carry.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the storage center.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    public static function createFieldConfig(): StorageCenterApiFieldConfig {
        return new StorageCenterApiFieldConfig();
    }
}
