<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Entity\Label\LabelReferenceApiEntity;
use Simplia\Api\Enum\StorageLocationType;
use Simplia\Api\FieldConfig\StorageLocationApiFieldConfig;

/**
 * A storage location: one shelf position of a stock room, as written on its label, with its kind, its capacity and the labels pinned on it. Every position of every stock room is listed; what is stored on a position is read through the stock items.
 */
final class StorageLocationApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the position; the value `StockItem.storage_locations[].id` carries.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The stock room the position is in; the same object as `GET /stock-rooms/{id}`, and the value the `stock_room` filter takes.
     */
    public function getStockRoom(): StockRoomApiEntity {
        return $this->readEntity('stock_room', StockRoomApiEntity::class);
    }

    /**
     * Position code as written on the shelf label, such as `A1` or `A-03-2`; unique within its stock room.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    /**
     * Free-text note about the position. Null when there is none.
     */
    public function getDescription(): ?string {
        return $this->readStringOrNull('description');
    }

    /**
     * Kind of position: `normal` (a shelf), `transitional` (a holding area for goods being received or prepared), `remote` (an external storage area), `mobile` (a mobile position, such as a picker's cart), `mobile_packaging_slot` (a packaging slot: the basket an order's picked items are gathered in), `mobile_admin` (a picker's own mobile position).
     */
    public function getType(): StorageLocationType {
        return $this->readEnum('type', StorageLocationType::class);
    }

    /**
     * How many pieces the position is meant to hold; 0 when no capacity is set.
     */
    public function getCapacity(): int {
        return $this->readInt('capacity');
    }

    /**
     * Order of the position among the stock room's positions, lower first. Null when none is set.
     */
    public function getPriority(): ?int {
        return $this->readIntOrNull('priority');
    }

    /**
     * Whether the shop assigns incoming items to this position automatically, by its rules.
     */
    public function isAutoAssign(): bool {
        return $this->readBool('auto_assign');
    }

    /**
     * The value encoded in the position's barcode, which the warehouse scanner reads to select it.
     */
    public function getBarcode(): string {
        return $this->readString('barcode');
    }

    /**
     * The labels pinned on the position, in the shop's order — every label assigned, whether or not it shows today (`GET /labels/{id}` says when and to whom). Empty when none is pinned.
     * @return list<LabelReferenceApiEntity>
     */
    public function getLabels(): array {
        return $this->readEntities('labels', LabelReferenceApiEntity::class);
    }

    public static function createFieldConfig(): StorageLocationApiFieldConfig {
        return new StorageLocationApiFieldConfig();
    }
}
