<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\TransportMethodApiFieldConfig;

/**
 * A shipping option offered at checkout, in the request language: which carrier delivers it, which of the carrier's services it uses, its position in the checkout list, and the store it is collected at for personal pickup. The same option has a different id in each language.
 */
final class TransportMethodApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the transport method in the request language; the same value as `Order.transport_method.id`, and what `OrderDeliveryInput.transport_method_id` takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the transport method as shown to customers, in the request language.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    /**
     * Code of the carrier that delivers it, as a lower-case slug such as `ppl`, `gls` or `dpd`; `osobne` for personal pickup at a store.
     */
    public function getCarrierCode(): string {
        return $this->readString('carrier_code');
    }

    /**
     * Code of the carrier's service or parcel type this option uses, in the carrier's own vocabulary. Null when the carrier's default service is used.
     */
    public function getPackageTypeCode(): ?string {
        return $this->readStringOrNull('package_type_code');
    }

    /**
     * Position in the checkout list: the lowest number comes first.
     */
    public function getPriority(): int {
        return $this->readInt('priority');
    }

    /**
     * The store the goods are collected at, for a personal-pickup option. Null for carrier delivery.
     */
    public function getStore(): ?StoreApiEntity {
        return $this->readEntityOrNull('store', StoreApiEntity::class);
    }

    public static function createFieldConfig(): TransportMethodApiFieldConfig {
        return new TransportMethodApiFieldConfig();
    }
}
