<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\UserApiFieldConfig;

class UserApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getEmail(): ?string {
        return $this->returnField('email');
    }

    public function getDeliveryAddress(): ?ContactApiEntity {
        return $this->returnField('delivery_address', ContactApiEntity::class);
    }

    public function getInvoiceAddress(): ?ContactApiEntity {
        return $this->returnField('invoice_address', ContactApiEntity::class);
    }

    public function getLoyaltyCard(): ?string {
        return $this->returnField('loyalty_card');
    }

    public function isWholesale(): bool {
        return $this->returnField('wholesale');
    }

    public function getDiscountPercentage(): ?float {
        return $this->returnField('discount_percentage');
    }

    public function getPointsFactor(): string {
        return $this->returnField('points_factor');
    }

    public function getUserGroup(): ?UserGroupApiEntity {
        return $this->returnField('user_group', UserGroupApiEntity::class);
    }

    final public static function createFieldConfig(): UserApiFieldConfig {
        return new UserApiFieldConfig();
    }
}
