<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\FieldConfig\VariantApiFieldConfig;

class VariantApiEntity extends AbstractApiEntity {
    public function getId(): int {
        return $this->returnField('id');
    }

    public function getName(): string {
        return $this->returnField('name');
    }

    public function getCode(): string {
        return $this->returnField('code');
    }

    public function getPriceVat(): string {
        return $this->returnField('price_vat');
    }

    public function getCodeSupplier(): ?string {
        return $this->returnField('code_supplier');
    }

    public function getEan(): ?string {
        return $this->returnField('ean');
    }

    public function getCreated(): string {
        return $this->returnField('created');
    }

    final public static function createFieldConfig(): VariantApiFieldConfig {
        return new VariantApiFieldConfig();
    }
}
