<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity;

use Simplia\Api\Enum\VoucherGroupKind;
use Simplia\Api\FieldConfig\VoucherGroupApiFieldConfig;
use Simplia\Api\Money;

/**
 * A voucher group: the campaign a set of discount codes belongs to, which defines what the codes take off and when they apply. The list holds the groups of the content group (storefront tree) being called, or the one `content_group` names; any group can be read by id.
 */
final class VoucherGroupApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the voucher group; the value `Voucher.group.id` carries and `VoucherCreateInput.group_id` takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name of the group as shown in the shop's administration.
     */
    public function getName(): string {
        return $this->readString('name');
    }

    /**
     * What the group's codes do: `percentage` (a percentage off), `amount` (an amount off), `n_plus_1` (buy several, one is free), `percentage_with_limit` (a percentage off, up to a limit), `percentage_most_expensive_with_limit` (a percentage off the most expensive item, up to a limit), `credit` (an amount credited). Null when the record does not say.
     */
    public function getKind(): ?VoucherGroupKind {
        return $this->readEnumOrNull('kind', VoucherGroupKind::class);
    }

    /**
     * The percentage the codes take off, for a percentage kind. Null for the other kinds.
     */
    public function getPercent(): ?float {
        return $this->readFloatOrNull('percent');
    }

    /**
     * The amount the codes take off or credit, in the shop's main currency, for an amount kind. Null for the other kinds.
     */
    public function getAmount(): ?Money {
        return $this->readMoneyOrNull('amount');
    }

    /**
     * How many times each code of the group may be redeemed. 0 or null means unlimited.
     */
    public function getMaxUses(): ?int {
        return $this->readIntOrNull('max_uses');
    }

    /**
     * The start of the validity window a newly generated code of the group receives, compared by calendar day; each code carries its own window (`Voucher.starts_at`), which is what redemption checks, and a group with a relative validity gives its codes a window counted from their creation. Null when there is no start bound.
     */
    public function getStartsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('starts_at');
    }

    /**
     * The last day of the validity window a newly generated code of the group receives, inclusive, compared by calendar day; the time part is always midnight; each code carries its own window (`Voucher.ends_at`), which is what redemption checks. Null when the codes never expire; a far-future day is published as stored.
     */
    public function getEndsAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('ends_at');
    }

    /**
     * The content group (storefront tree) the group belongs to; its `id` is the value the `content_group` filter takes.
     */
    public function getContentGroup(): ContentGroupApiEntity {
        return $this->readEntity('content_group', ContentGroupApiEntity::class);
    }

    public static function createFieldConfig(): VoucherGroupApiFieldConfig {
        return new VoucherGroupApiFieldConfig();
    }
}
