<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Product;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\FieldConfig\Product\ProductReferenceApiFieldConfig;

/**
 * A pointer at a product: its id and its name in the request language; the whole record is `GET /products/{id}`.
 */
final class ProductReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the product; the same value as `Product.id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Product name in the request language. Null when the product no longer exists or has no name in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    public static function createFieldConfig(): ProductReferenceApiFieldConfig {
        return new ProductReferenceApiFieldConfig();
    }
}
