<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Document;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\Entity\StockItemApiEntity;
use Simplia\Api3\FieldConfig\Document\DocumentItemApiFieldConfig;
use Simplia\Api3\Money;

/**
 * One line of a document: what was invoiced, received or issued, how many units, at what unit price and VAT rate.
 */
final class DocumentItemApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the line; the value `PUT /documents/{id}/rows/price` addresses in `items[].id`. Not a stock item id.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The line's text as printed on the document. Null when the stored text is empty.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Number of units the line covers. Negative on a document that issues goods. Null when not recorded.
     */
    public function getQuantity(): ?int {
        return $this->readIntOrNull('quantity');
    }

    /**
     * Unit price including VAT, in the shop's main currency. Null when the line has no price.
     */
    public function getPrice(): ?Money {
        return $this->readMoneyOrNull('price');
    }

    /**
     * Unit price including VAT, in the document's own currency (the document's `currency`, or the shop's main currency when none is recorded). Null when the line has no price in that currency.
     */
    public function getPriceInDocumentCurrency(): ?Money {
        return $this->readMoneyOrNull('price_in_document_currency');
    }

    /**
     * VAT rate applied to the line, as a percentage (21 for 21 %).
     */
    public function getVatRate(): float {
        return $this->readFloat('vat_rate');
    }

    /**
     * What the line is: `item` (a stock item), `bundle` (a bundle of items), `discount`, `shipping` (delivery charge), `deposit` (an advance payment), `rounding` (cash rounding), `other`. Null when not recorded.
     */
    public function getType(): ?string {
        return $this->readStringOrNull('type');
    }

    /**
     * The stock item the line refers to; the same record as `GET /stock-items/{id}`, any of its members selectable through `rows.stock_item.…`. Null for a line that is not a stock item, such as a discount, shipping, rounding or deposit line.
     */
    public function getStockItem(): ?StockItemApiEntity {
        return $this->readEntityOrNull('stock_item', StockItemApiEntity::class);
    }

    public static function createFieldConfig(): DocumentItemApiFieldConfig {
        return new DocumentItemApiFieldConfig();
    }
}
