<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Order;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a ContactApiEntity to fetch.
 */
final class ContactApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the stored address. Each address of an order has its own.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Given name of the recipient or contact. Null when not filled.
     */
    public function withFirstName(): self {
        $this->fields['first_name'] = true;

        return $this;
    }

    /**
     * Family name of the recipient or contact. Null when not filled.
     */
    public function withLastName(): self {
        $this->fields['last_name'] = true;

        return $this;
    }

    /**
     * Street and house number. Null when not filled.
     */
    public function withStreet(): self {
        $this->fields['street'] = true;

        return $this;
    }

    /**
     * Postal code, as entered. Null when not filled.
     */
    public function withZip(): self {
        $this->fields['zip'] = true;

        return $this;
    }

    /**
     * Town or city. Null when not filled.
     */
    public function withCity(): self {
        $this->fields['city'] = true;

        return $this;
    }

    /**
     * State, province or county, where the destination country uses one. Null when not filled.
     */
    public function withRegion(): self {
        $this->fields['region'] = true;

        return $this;
    }

    /**
     * Country as a lower-case two-letter code (ISO 3166-1 alpha-2), such as `cz`. Null when not filled.
     */
    public function withCountry(): self {
        $this->fields['country'] = true;

        return $this;
    }

    /**
     * Company name, when the address belongs to a business. Null for a private person.
     */
    public function withCompanyName(): self {
        $this->fields['company_name'] = true;

        return $this;
    }

    /**
     * Company registration number in the national business register (Czech IČO). Not the VAT number. Null when not a business or not filled.
     */
    public function withCompanyId(): self {
        $this->fields['company_id'] = true;

        return $this;
    }

    /**
     * VAT identification number (Czech DIČ, EU VAT id), usually the country prefix followed by digits. Null when not VAT-registered or not filled.
     */
    public function withCompanyVatId(): self {
        $this->fields['company_vat_id'] = true;

        return $this;
    }

    /**
     * Contact phone number, as entered. Null when not filled.
     */
    public function withPhone(): self {
        $this->fields['phone'] = true;

        return $this;
    }

    /**
     * Contact e-mail address. Null when not filled.
     */
    public function withEmail(): self {
        $this->fields['email'] = true;

        return $this;
    }
}
