<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Order;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api\FieldConfig\AdminApiFieldConfig;

/**
 * Which properties of a OrderPackagingApiEntity to fetch.
 */
final class OrderPackagingApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the session. Not addressable by any endpoint.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The staff account that collected the goods from the shelves; the same record as `GET /admins/{id}`. Null when picking has not started or is not attributed.
     */
    public function selectPickedBy(AdminApiFieldConfig $config): self {
        $this->fields['picked_by'] = $config;

        return $this;
    }

    /**
     * When collecting the goods began. Null when it has not started.
     */
    public function selectPickingStartedAt(): self {
        $this->fields['picking_started_at'] = true;

        return $this;
    }

    /**
     * When collecting the goods finished. Null when it has not finished.
     */
    public function selectPickingEndedAt(): self {
        $this->fields['picking_ended_at'] = true;

        return $this;
    }

    /**
     * The staff account that boxed the goods; the same record as `GET /admins/{id}`. Null when packing has not started or is not attributed.
     */
    public function selectPackagedBy(AdminApiFieldConfig $config): self {
        $this->fields['packaged_by'] = $config;

        return $this;
    }

    /**
     * When boxing began. Null when it has not started.
     */
    public function selectPackagingStartedAt(): self {
        $this->fields['packaging_started_at'] = true;

        return $this;
    }

    /**
     * When boxing finished and the parcel was ready for the carrier. Null when it has not finished.
     */
    public function selectPackagingEndedAt(): self {
        $this->fields['packaging_ended_at'] = true;

        return $this;
    }
}
