<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Order;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api\FieldConfig\StockItemApiFieldConfig;

/**
 * Which properties of a OrderItemApiEntity to fetch.
 */
final class OrderItemApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the line; the same value as `OrderItem.id` at `GET /order-items/{id}`.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Numeric identifier of the order the line belongs to; the same value as `Order.id`.
     */
    public function withOrderId(): self {
        $this->fields['order_id'] = true;

        return $this;
    }

    /**
     * Order number of the order the line belongs to; the same value as `Order.code`. Null when the order has none.
     */
    public function withOrderCode(): self {
        $this->fields['order_code'] = true;

        return $this;
    }

    /**
     * Product name followed by the variant name, as they were at the time of ordering.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Note attached to the line, such as a customization request. Null when there is none.
     */
    public function withNote(): self {
        $this->fields['note'] = true;

        return $this;
    }

    /**
     * Code (SKU) of the stock item on the line: the linked stock item's current code, or the code recorded on the line when nothing is linked.
     */
    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * Number of units ordered on this line.
     */
    public function withQuantity(): self {
        $this->fields['quantity'] = true;

        return $this;
    }

    /**
     * Number of those units reserved in stock for this line: still in the warehouse, no longer available to anyone else. 0 when nothing is reserved.
     */
    public function withBlockedQuantity(): self {
        $this->fields['blocked_quantity'] = true;

        return $this;
    }

    /**
     * Price of one unit, including VAT, in the shop's main currency.
     */
    public function withPrice(): self {
        $this->fields['price'] = true;

        return $this;
    }

    /**
     * Price of one unit, including VAT, in the order's own currency: the unit price the customer saw.
     */
    public function withPriceInOrderCurrency(): self {
        $this->fields['price_in_order_currency'] = true;

        return $this;
    }

    /**
     * Price of one unit, without VAT, in the shop's main currency.
     */
    public function withPriceWithoutVat(): self {
        $this->fields['price_without_vat'] = true;

        return $this;
    }

    /**
     * Price of one unit, without VAT, in the order's own currency.
     */
    public function withPriceWithoutVatInOrderCurrency(): self {
        $this->fields['price_without_vat_in_order_currency'] = true;

        return $this;
    }

    /**
     * VAT rate applied to the line, as a percentage (21 for 21 %).
     */
    public function withVatRate(): self {
        $this->fields['vat_rate'] = true;

        return $this;
    }

    /**
     * Discount applied to the line, as a percentage of the unit price. 0 when there is none.
     */
    public function withDiscountPercentage(): self {
        $this->fields['discount_percentage'] = true;

        return $this;
    }

    /**
     * The stock item the line refers to; the same record as `GET /stock-items/{id}`, any of its members selectable through `items.stock_item.…`. Null when the line has no linked stock item.
     */
    public function withStockItem(StockItemApiFieldConfig $config): self {
        $this->fields['stock_item'] = $config;

        return $this;
    }

    /**
     * Whether the line is a bundle: `none` (an ordinary product), `bundle` (a set of different products sold together), `multipack` (several units of one product or its variants sold as one pack).
     */
    public function withBundleType(): self {
        $this->fields['bundle_type'] = true;

        return $this;
    }
}
