<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig\StockItem;

use Simplia\Api3\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api3\FieldConfig\StockItemApiFieldConfig;

/**
 * Which properties of a BundlePartApiEntity to fetch.
 */
final class BundlePartApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the part line. Not a stock item id.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * How many of the part go into one unit of the bundle.
     */
    public function withQuantity(): self {
        $this->fields['quantity'] = true;

        return $this;
    }

    /**
     * The stock item used as the part; the same record as `GET /stock-items/{id}`, any of its members selectable through `bundle_parts.stock_item.…`.
     */
    public function withStockItem(StockItemApiFieldConfig $config): self {
        $this->fields['stock_item'] = $config;

        return $this;
    }
}
