<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\StockItem;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a VariantApiEntity to fetch.
 */
final class VariantApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the variant; the same value as `Variant.id`.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The option value of the variant, such as `black` or `XL`. Empty when none is stored.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * The shop's own code (SKU) of the variant's stock item. Empty when none is set.
     */
    public function selectCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * Catalog price of the variant including VAT, in the shop's main currency, before any price list, customer discount or promotion.
     */
    public function selectPrice(): self {
        $this->fields['price'] = true;

        return $this;
    }

    /**
     * The supplier's or manufacturer's part number for the variant. Null when none is set.
     */
    public function selectCodeSupplier(): self {
        $this->fields['code_supplier'] = true;

        return $this;
    }

    /**
     * Barcode (EAN) of the variant. Null when none is recorded.
     */
    public function selectEan(): self {
        $this->fields['ean'] = true;

        return $this;
    }

    /**
     * When the variant was created.
     */
    public function selectCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }
}
