<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a AdminApiEntity to fetch.
 */
final class AdminApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the staff account; the value `Order.created_by.id` and `Document.issued_by.id` carry.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Given name. Null when not filled.
     */
    public function withFirstName(): self {
        $this->fields['first_name'] = true;

        return $this;
    }

    /**
     * Family name. Null when not filled.
     */
    public function withLastName(): self {
        $this->fields['last_name'] = true;

        return $this;
    }

    /**
     * Whether the account is enabled. A disabled account can neither sign in nor call the API; an enabled one may still be limited by the shop's own sign-in rules. An inactive account is kept for the orders and documents that name it.
     */
    public function withActive(): self {
        $this->fields['active'] = true;

        return $this;
    }

    /**
     * Kind of account: `standard` (a person using the administration), `api` (a credential created for calling the API) or `integration` (the account an installed integration calls as).
     */
    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }
}
