<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a ArticleApiEntity to fetch.
 */
final class ArticleApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the article.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Headline of the article. Null when none is stored.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Teaser shown in listings, as HTML. Null when the article has none.
     */
    public function withAnnotation(): self {
        $this->fields['annotation'] = true;

        return $this;
    }

    /**
     * Body of the article, as HTML. Null when the article has none.
     */
    public function withText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    /**
     * When the article is published. Null when no date is set; such articles are listed too.
     */
    public function withPublishedAt(): self {
        $this->fields['published_at'] = true;

        return $this;
    }

    /**
     * Path of the article on the shop's site, relative to the shop origin, such as `/blog/new-products`. Null when the article has no address.
     */
    public function withUrl(): self {
        $this->fields['url'] = true;

        return $this;
    }
}
