<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

class ArticleApiFieldConfig extends AbstractApiFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    public function withAnnotation(): self {
        $this->fields['annotation'] = true;

        return $this;
    }

    public function withText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    public function withPublished(): self {
        $this->fields['published'] = true;

        return $this;
    }

    public function withUrl(): self {
        $this->fields['url'] = true;

        return $this;
    }
}
