<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\Attribute\AttributeValueApiFieldConfig;

/**
 * Which properties of a AttributeApiEntity to fetch.
 */
final class AttributeApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Attribute id, the `attribute.id` a row of a product's `attributes` carries.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name in the request language. Null when the attribute has no name in that language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Unit of the value in the request language ("cm", "kg"), as the shop wrote it. Null when the attribute has none.
     */
    public function withUnit(): self {
        $this->fields['unit'] = true;

        return $this;
    }

    /**
     * What a value of the attribute is: `text`, `integer` or `boolean` (a product stores one `value`, as text), `choice` (one of `values`) or `multi_choice` (several of `values`).
     */
    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    /**
     * What the attribute stands for, when the shop marked it: `size`, `color`, `gender`, `material`, `pattern`, `age_group`, `collection` or `season`. Null when it stands for nothing in particular.
     */
    public function withMeaning(): self {
        $this->fields['meaning'] = true;

        return $this;
    }

    /**
     * The kind of record the attribute describes: `product` (it appears in a product's `attributes`), `brand`, `store`, `customer` or `article`. Null for a kind this document does not name.
     */
    public function withAppliesTo(): self {
        $this->fields['applies_to'] = true;

        return $this;
    }

    /**
     * Whether the storefront shows the attribute at all.
     */
    public function withActive(): self {
        $this->fields['active'] = true;

        return $this;
    }

    /**
     * Whether the storefront shows the attribute on the product's page.
     */
    public function withOnDetail(): self {
        $this->fields['on_detail'] = true;

        return $this;
    }

    /**
     * Whether the storefront offers the attribute as a filter of a product list.
     */
    public function withInFilter(): self {
        $this->fields['in_filter'] = true;

        return $this;
    }

    /**
     * Position among the shop's attributes; lower first. The order of `sort=priority` and of a product's `attributes` list.
     */
    public function withPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * A picture standing for the attribute, when the shop stored one. Null when none is stored.
     */
    public function withImage(ImageApiFieldConfig $config): self {
        $this->fields['image'] = $config;

        return $this;
    }

    /**
     * For a `choice` or `multi_choice` attribute, the values a product can carry, in the shop's order (`priority`, then id). Empty for the other kinds.
     */
    public function withValues(AttributeValueApiFieldConfig $config): self {
        $this->fields['values'] = $config;

        return $this;
    }
}
