<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a BrandApiEntity to fetch.
 */
final class BrandApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the brand; the value `Product.brand.id` carries.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Brand name, the same in every language. Null when none is stored.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * The shop's own code for the brand. Null when none is set.
     */
    public function selectCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * URL-safe form of the name used in the brand's storefront address, such as `bellroy`. Null when none is set.
     */
    public function selectSlug(): self {
        $this->fields['slug'] = true;

        return $this;
    }

    /**
     * Whether the brand is offered in the catalog; a shop can have it recomputed nightly from the brand's products. An inactive brand is kept for the products that carry it.
     */
    public function selectActive(): self {
        $this->fields['active'] = true;

        return $this;
    }

    /**
     * The supplier the shop buys this brand from; `Product.supplier` falls back to it when a product has no supplier of its own; the same record as `GET /suppliers/{id}`. Null when none is set.
     */
    public function selectSupplier(SupplierApiFieldConfig $config): self {
        $this->fields['supplier'] = $config;

        return $this;
    }

    /**
     * The brand's main picture, such as its logo. Null when none is stored.
     */
    public function selectImage(ImageApiFieldConfig $config): self {
        $this->fields['image'] = $config;

        return $this;
    }

    /**
     * The brand's second picture, the larger one a storefront uses where it previews the brand, a brand list for instance. Null when none is stored.
     */
    public function selectPreviewImage(ImageApiFieldConfig $config): self {
        $this->fields['preview_image'] = $config;

        return $this;
    }
}
