<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

use Simplia\Api3\FieldConfig\Admin\AdminReferenceApiFieldConfig;
use Simplia\Api3\FieldConfig\Article\ArticleReferenceApiFieldConfig;
use Simplia\Api3\FieldConfig\Category\CategoryReferenceApiFieldConfig;
use Simplia\Api3\FieldConfig\Comment\CommentReferenceApiFieldConfig;
use Simplia\Api3\FieldConfig\Product\ProductReferenceApiFieldConfig;

/**
 * Which properties of a CommentApiEntity to fetch.
 */
final class CommentApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the comment.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * What the comment was written under: a `product`, a `category` or an `article`. The matching one of `product`, `category` and `article` is set.
     */
    public function withSubject(): self {
        $this->fields['subject'] = true;

        return $this;
    }

    /**
     * The product the comment was written under. Null unless `subject` is `product`.
     */
    public function withProduct(ProductReferenceApiFieldConfig $config): self {
        $this->fields['product'] = $config;

        return $this;
    }

    /**
     * The category the comment was written under. Null unless `subject` is `category`.
     */
    public function withCategory(CategoryReferenceApiFieldConfig $config): self {
        $this->fields['category'] = $config;

        return $this;
    }

    /**
     * The article the comment was written under. Null unless `subject` is `article`.
     */
    public function withArticle(ArticleReferenceApiFieldConfig $config): self {
        $this->fields['article'] = $config;

        return $this;
    }

    /**
     * The comment this one replies to. Null for a comment that starts a thread; the `parent` filter lists the replies of a comment.
     */
    public function withParent(CommentReferenceApiFieldConfig $config): self {
        $this->fields['parent'] = $config;

        return $this;
    }

    /**
     * The title the writer gave the comment. Null when none was given.
     */
    public function withTitle(): self {
        $this->fields['title'] = true;

        return $this;
    }

    /**
     * The name the writer gave. Null when none was given.
     */
    public function withAuthor(): self {
        $this->fields['author'] = true;

        return $this;
    }

    /**
     * The e-mail address the writer gave, as stored. Null when none was given.
     */
    public function withEmail(): self {
        $this->fields['email'] = true;

        return $this;
    }

    /**
     * The phone number the writer gave, as stored. Null when none was given.
     */
    public function withPhone(): self {
        $this->fields['phone'] = true;

        return $this;
    }

    /**
     * The staff account that wrote the comment, when a staff member wrote it in the shop's administration: a reply, or a comment of the shop's own. Null for a customer's comment.
     */
    public function withStaff(AdminReferenceApiFieldConfig $config): self {
        $this->fields['staff'] = $config;

        return $this;
    }

    /**
     * The comment, as plain text with its line breaks. Null when empty.
     */
    public function withText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    /**
     * Moderation state: `pending` (waiting for the shop's approval), `approved`. A rejected comment is deleted, so no third state exists.
     */
    public function withStatus(): self {
        $this->fields['status'] = true;

        return $this;
    }

    /**
     * When the comment was approved. Null while it is pending.
     */
    public function withApprovedAt(): self {
        $this->fields['approved_at'] = true;

        return $this;
    }

    /**
     * The star rating given with the comment, 0 to 5 stars. Null when none was given.
     */
    public function withRating(): self {
        $this->fields['rating'] = true;

        return $this;
    }

    /**
     * When the comment was written. The value the list sorts on by default.
     */
    public function withCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }
}
