<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a ContentGroupApiEntity to fetch.
 */
final class ContentGroupApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the content group; the value `Category.content_group.id` carries and the `content_group` filter of `GET /categories` takes.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the content group, such as `default` or `b2b`.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }
}
