<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

class DocumentItemPriceFieldConfig extends AbstractFieldConfig {
    public function withId(): self {
        return $this;
    }

    public function withPrice(): self {
        $this->fields['price'] = true;

        return $this;
    }

    public function withVatRate(): self {
        $this->fields['vat_rate'] = true;

        return $this;
    }
}
