<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\DocumentApiFieldConfig as DocumentApiFieldConfig1;

class DocumentApiFieldConfig extends AbstractApiFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withDateIssued(): self {
        $this->fields['date_issued'] = true;

        return $this;
    }

    public function withDueDate(): self {
        $this->fields['due_date'] = true;

        return $this;
    }

    public function withVatDate(): self {
        $this->fields['vat_date'] = true;

        return $this;
    }

    public function withCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    public function withCurrencyRate(): self {
        $this->fields['currency_rate'] = true;

        return $this;
    }

    public function withNote(): self {
        $this->fields['note'] = true;

        return $this;
    }

    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    public function withSubtype(): self {
        $this->fields['subtype'] = true;

        return $this;
    }

    public function withVariableSymbol(): self {
        $this->fields['variable_symbol'] = true;

        return $this;
    }

    public function withRows(DocumentItemApiFieldConfig $config): self {
        $this->fields['rows'] = $config;

        return $this;
    }

    public function withCustomerAddress(ContactApiFieldConfig $config): self {
        $this->fields['customer_address'] = $config;

        return $this;
    }

    public function withSupplier(SupplierApiFieldConfig $config): self {
        $this->fields['supplier'] = $config;

        return $this;
    }

    public function withStorageCenter(StockStorageCenterApiFieldConfig $config): self {
        $this->fields['storage_center'] = $config;

        return $this;
    }

    public function withStockRoom(StockRoomApiFieldConfig $config): self {
        $this->fields['stock_room'] = $config;

        return $this;
    }

    public function withRelevantDocument(DocumentApiFieldConfig $config): self {
        $this->fields['relevant_document'] = $config;

        return $this;
    }

    public function withRelevantDocuments(DocumentApiFieldConfig $config): self {
        $this->fields['relevant_documents'] = $config;

        return $this;
    }

    public function withPayments(PaymentApiFieldConfig $config): self {
        $this->fields['payments'] = $config;

        return $this;
    }
}
