<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a EmailMessageApiEntity to fetch.
 */
final class EmailMessageApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Message-ID the mail transport assigned to the message handed to the mail server; use it to correlate with mail logs. Where sending is suppressed, the fixed value `debug-suppressed`.
     */
    public function withMessageId(): self {
        $this->fields['message_id'] = true;

        return $this;
    }
}
