<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a ImageApiEntity to fetch.
 */
final class ImageApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the image.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * MD5 of the stored image file's bytes, as 32 lower-case hexadecimal characters; use it to tell whether you already hold this exact stored file. It is not the MD5 of what `url` answers, which is a rendition. Null for images stored before hashing was introduced.
     */
    public function selectHashMd5(): self {
        $this->fields['hash_md5'] = true;

        return $this;
    }

    /**
     * HTTPS address of a full-size rendition of the image on the shop's image service: the picture at the size `width` by `height` when neither side exceeds 5000 pixels, otherwise fitted into 5000 by 5000; an SVG is the drawing itself, which scales. A JPEG; a PNG with its transparency kept when the stored file is a PNG or GIF; an SVG when the stored file is one. A rendition, so its bytes are not the stored file's. Fetch it from this address when you need it and do not build other addresses from it: it is signed by the shop and can change.
     */
    public function selectUrl(): self {
        $this->fields['url'] = true;

        return $this;
    }

    /**
     * Width of the image in pixels as displayed (a photo's rotation flag applied). Null for an SVG, which has no pixel size, and when the size was not recorded; `url` then answers the picture fitted into 1600 pixels on that side.
     */
    public function selectWidth(): self {
        $this->fields['width'] = true;

        return $this;
    }

    /**
     * Height of the image in pixels as displayed. Null for an SVG and when the size was not recorded (see `width`).
     */
    public function selectHeight(): self {
        $this->fields['height'] = true;

        return $this;
    }
}
