<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a LabelApiEntity to fetch.
 */
final class LabelApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Label id, the `id` an entry of a product's `labels` carries.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * A short code the shop gave the label: lowercase letters, digits and underscores, unique among the shop's labels. Null when the label has none.
     */
    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * Name in the request language. Null when the label has no name in that language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * The label's colour as a hexadecimal `#rrggbb` value. Null when the shop set none.
     */
    public function withColor(): self {
        $this->fields['color'] = true;

        return $this;
    }

    /**
     * The label's picture, shown in place of its name when the shop stored one. Null when none is stored.
     */
    public function withImage(ImageApiFieldConfig $config): self {
        $this->fields['image'] = $config;

        return $this;
    }

    /**
     * The kinds of record the label can be pinned on: `product`, `variant`, `storage_location`. Empty when the shop has not picked any.
     */
    public function withAppliesTo(): self {
        $this->fields['applies_to'] = true;

        return $this;
    }

    /**
     * Whether retail customers see the label.
     */
    public function withPublicRetail(): self {
        $this->fields['public_retail'] = true;

        return $this;
    }

    /**
     * Whether wholesale customers see the label.
     */
    public function withPublicWholesale(): self {
        $this->fields['public_wholesale'] = true;

        return $this;
    }

    /**
     * Position among the shop's labels; lower first. The order of `sort=priority` and of a product's `labels` list.
     */
    public function withPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * The start of the label's validity window; before it the label is not shown.
     */
    public function withStartsAt(): self {
        $this->fields['starts_at'] = true;

        return $this;
    }

    /**
     * The end of the label's validity window; after it the label is not shown.
     */
    public function withEndsAt(): self {
        $this->fields['ends_at'] = true;

        return $this;
    }
}
