<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a LogisticPlanApiEntity to fetch.
 */
final class LogisticPlanApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the plan; the value StockItemUpdateInput.logistic_plan_id takes.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the plan.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Whether demand from retail customer orders counts for this plan's transfers.
     */
    public function selectActiveRetail(): self {
        $this->fields['active_retail'] = true;

        return $this;
    }

    /**
     * Whether demand from wholesale customer orders counts for this plan's transfers.
     */
    public function selectActiveWholesale(): self {
        $this->fields['active_wholesale'] = true;

        return $this;
    }

    /**
     * Whether demand from repair jobs counts for this plan's transfers.
     */
    public function selectActiveRepair(): self {
        $this->fields['active_repair'] = true;

        return $this;
    }
}
