<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a MeApiEntity to fetch.
 */
final class MeApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric id of the administrator account behind the credential.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Display name of the administrator account.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Permission keys the credential holds, sorted, exactly as granted — an umbrella key (api:orders:read, api:orders:write) is listed as itself, not expanded; each operation names the key it needs as x-permission.
     */
    public function withGrants(): self {
        $this->fields['grants'] = true;

        return $this;
    }
}
