<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

class OrderPackagingApiFieldConfig extends AbstractApiFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withPickedBy(): self {
        return $this;
    }

    public function withPickingStart(): self {
        $this->fields['picking_start'] = true;

        return $this;
    }

    public function withPickingEnd(): self {
        $this->fields['picking_end'] = true;

        return $this;
    }

    public function withPackagedBy(): self {
        return $this;
    }

    public function withPackagingStart(): self {
        $this->fields['packaging_start'] = true;

        return $this;
    }

    public function withPackagingEnd(): self {
        $this->fields['packaging_end'] = true;

        return $this;
    }
}
