<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

use Simplia\Api3\FieldConfig\Order\ContactApiFieldConfig;
use Simplia\Api3\FieldConfig\Order\OrderDiscountApiFieldConfig;
use Simplia\Api3\FieldConfig\Order\OrderItemApiFieldConfig;
use Simplia\Api3\FieldConfig\Order\OrderPackagingApiFieldConfig;
use Simplia\Api3\FieldConfig\Order\PackageApiFieldConfig;
use Simplia\Api3\FieldConfig\Order\PaymentApiFieldConfig;

/**
 * Which properties of a OrderApiEntity to fetch.
 */
final class OrderApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the order. The address of every write, and the value `OrderItem.order_id` and the `order_id` filter of `GET /packages` carry.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The order number shown to customers and staff. Readable by `GET /orders/by-code/{code}`. Null when the order has no number yet.
     */
    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * The order's identifier in the system it came from: a marketplace order id, or the value supplied when the order was created through this API. Null for an order placed in the shop itself.
     */
    public function withExternalCode(): self {
        $this->fields['external_code'] = true;

        return $this;
    }

    /**
     * Address of the shop (domain) the order was placed on. Null when it was not recorded.
     */
    public function withShopUrl(): self {
        $this->fields['shop_url'] = true;

        return $this;
    }

    /**
     * Public link at which the customer can follow this order. Null when the shop it was placed on no longer exists.
     */
    public function withOnlineUrl(): self {
        $this->fields['online_url'] = true;

        return $this;
    }

    /**
     * When the order was placed.
     */
    public function withCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }

    /**
     * Day before which the order must not be dispatched, as asked by the customer or an operator. Null when dispatch is not postponed.
     */
    public function withDelayedUntilDate(): self {
        $this->fields['delayed_until_date'] = true;

        return $this;
    }

    /**
     * Day the shop expects to dispatch the order: an estimate, not an instruction. Null when there is no estimate.
     */
    public function withExpectedDispatchDate(): self {
        $this->fields['expected_dispatch_date'] = true;

        return $this;
    }

    /**
     * When the order entered its current `status`. Null when no transition has been recorded.
     */
    public function withStatusChangedAt(): self {
        $this->fields['status_changed_at'] = true;

        return $this;
    }

    /**
     * When the customer took delivery of the goods, as reported by the carrier. Null until then, and null for an order without an invoice.
     */
    public function withPickedUpAt(): self {
        $this->fields['picked_up_at'] = true;

        return $this;
    }

    /**
     * ISO 4217 code of the currency the customer ordered in. Empty when the order has no currency recorded.
     */
    public function withCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    /**
     * Whether the order is handled by an external fulfillment partner rather than the shop's own warehouse.
     */
    public function withFulfillment(): self {
        $this->fields['fulfillment'] = true;

        return $this;
    }

    /**
     * Numeric identifier of the marketplace the order was imported from, as the marketplace connector reports it. Null for an order that did not come through a marketplace.
     */
    public function withMarketplaceSourceId(): self {
        $this->fields['marketplace_source_id'] = true;

        return $this;
    }

    /**
     * Name of the marketplace the order was imported from, as the connector reports it (for example `Amazon`). Null for an order that did not come through a marketplace.
     */
    public function withMarketplaceSource(): self {
        $this->fields['marketplace_source'] = true;

        return $this;
    }

    /**
     * Where the order stands: `unprocessed` (new, not yet handled), `processed` (accepted for processing), `waiting` (on hold, for stock or payment), `ready` (picked and packed, waiting for the carrier), `finished` (dispatched), `cancelled`. Empty for an order whose stored state has no public value.
     */
    public function withStatus(): self {
        $this->fields['status'] = true;

        return $this;
    }

    /**
     * Exchange rate frozen on the order: how many units of the shop's main currency one unit of `currency` is worth. 0 when no rate was recorded.
     */
    public function withCurrencyRate(): self {
        $this->fields['currency_rate'] = true;

        return $this;
    }

    /**
     * Code of the carrier that delivers the order, such as `ppl`, `ups` or `gls`; `pickup` when the customer collects in person or no carrier is set.
     */
    public function withCarrierCode(): self {
        $this->fields['carrier_code'] = true;

        return $this;
    }

    /**
     * Identifier of the pickup point or parcel shop the customer chose, in the carrier's own format. Null when the delivery goes to an address.
     */
    public function withBranchCode(): self {
        $this->fields['branch_code'] = true;

        return $this;
    }

    /**
     * Shipping and handling charged on the order, including VAT, in the shop's main currency.
     */
    public function withDeliveryPrice(): self {
        $this->fields['delivery_price'] = true;

        return $this;
    }

    /**
     * Shipping and handling charged on the order, including VAT, in the order's own currency (`currency`): the amount the customer saw.
     */
    public function withDeliveryPriceInOrderCurrency(): self {
        $this->fields['delivery_price_in_order_currency'] = true;

        return $this;
    }

    /**
     * Shipping and handling charged on the order, without VAT, in the shop's main currency.
     */
    public function withDeliveryPriceWithoutVat(): self {
        $this->fields['delivery_price_without_vat'] = true;

        return $this;
    }

    /**
     * Shipping and handling charged on the order, without VAT, in the order's own currency (`currency`).
     */
    public function withDeliveryPriceWithoutVatInOrderCurrency(): self {
        $this->fields['delivery_price_without_vat_in_order_currency'] = true;

        return $this;
    }

    /**
     * Label of the delivery and payment combination the customer chose, as it was named at the time. Null when not recorded.
     */
    public function withDeliveryName(): self {
        $this->fields['delivery_name'] = true;

        return $this;
    }

    /**
     * How the customer chose to pay: `cash_on_delivery` (pay the courier), `online` (card or payment gateway), `bank_transfer`, `cash` (in person), `against_invoice` (invoiced, paid later). Null for a payment type without a public value.
     */
    public function withPaymentType(): self {
        $this->fields['payment_type'] = true;

        return $this;
    }

    /**
     * The note the customer wrote with the order. Null when there is none.
     */
    public function withNote(): self {
        $this->fields['note'] = true;

        return $this;
    }

    /**
     * Note to print on the invoice. Null when there is none.
     */
    public function withInvoiceNote(): self {
        $this->fields['invoice_note'] = true;

        return $this;
    }

    /**
     * Payment reference (variable symbol) the customer quotes on a bank transfer, derived from the order number. Null when the order has no number.
     */
    public function withVariableSymbol(): self {
        $this->fields['variable_symbol'] = true;

        return $this;
    }

    /**
     * How urgently the warehouse should handle the order: 0 normal, 1 important, 2 urgent, 3 emergency. Set with `PUT /orders/{id}/priority`.
     */
    public function withPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * Grand total of the order including VAT: the lines, minus discounts, plus shipping, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPrice(): self {
        $this->fields['total_price'] = true;

        return $this;
    }

    /**
     * Grand total of the order including VAT, in the order's own currency (`currency`): what the customer was charged. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPriceInOrderCurrency(): self {
        $this->fields['total_price_in_order_currency'] = true;

        return $this;
    }

    /**
     * Grand total of the order without VAT, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPriceWithoutVat(): self {
        $this->fields['total_price_without_vat'] = true;

        return $this;
    }

    /**
     * Grand total of the order without VAT, in the order's own currency (`currency`). Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPriceWithoutVatInOrderCurrency(): self {
        $this->fields['total_price_without_vat_in_order_currency'] = true;

        return $this;
    }

    /**
     * Sum of the payments received against the order, in the shop's main currency. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPaid(): self {
        $this->fields['total_paid'] = true;

        return $this;
    }

    /**
     * Sum of the payments received against the order, in the order's own currency (`currency`): a payment made in that currency counts as paid; one made in another currency is converted from the shop's main currency at `currency_rate`. Null when such a conversion is impossible because the order has no exchange rate. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function withTotalPaidInOrderCurrency(): self {
        $this->fields['total_paid_in_order_currency'] = true;

        return $this;
    }

    /**
     * The shipping method the order uses; the same object as `GET /transport-methods/{id}`. Null when none is linked.
     */
    public function withTransportMethod(TransportMethodApiFieldConfig $config): self {
        $this->fields['transport_method'] = $config;

        return $this;
    }

    /**
     * The payment method the order uses; the same object as `GET /payment-methods/{id}`. Null when none is linked.
     */
    public function withPaymentMethod(PaymentMethodApiFieldConfig $config): self {
        $this->fields['payment_method'] = $config;

        return $this;
    }

    /**
     * The store the order is assigned to. Null when it is not assigned to one.
     */
    public function withStore(StoreApiFieldConfig $config): self {
        $this->fields['store'] = $config;

        return $this;
    }

    /**
     * The store the order was entered at, when it was created at a point of sale. Null otherwise.
     */
    public function withCreatedStore(StoreApiFieldConfig $config): self {
        $this->fields['created_store'] = $config;

        return $this;
    }

    /**
     * The staff account that entered the order; the same record as `GET /admins/{id}`. Null when the customer placed it online.
     */
    public function withCreatedBy(AdminApiFieldConfig $config): self {
        $this->fields['created_by'] = $config;

        return $this;
    }

    /**
     * The storage center that fulfills the order; changed with `PATCH /orders/{id}`. Null when none is assigned.
     */
    public function withStorageCenter(StorageCenterApiFieldConfig $config): self {
        $this->fields['storage_center'] = $config;

        return $this;
    }

    /**
     * The registered customer account that placed the order; the same record as `GET /users/{id}`. Null for a guest order.
     */
    public function withUser(UserApiFieldConfig $config): self {
        $this->fields['user'] = $config;

        return $this;
    }

    /**
     * Where the goods are delivered. Null when no delivery address is recorded.
     */
    public function withDeliveryAddress(ContactApiFieldConfig $config): self {
        $this->fields['delivery_address'] = $config;

        return $this;
    }

    /**
     * Who is billed. Null when no separate billing address is recorded.
     */
    public function withInvoiceAddress(ContactApiFieldConfig $config): self {
        $this->fields['invoice_address'] = $config;

        return $this;
    }

    /**
     * The ordered lines. Cancelled lines are not included.
     */
    public function withItems(OrderItemApiFieldConfig $config): self {
        $this->fields['items'] = $config;

        return $this;
    }

    /**
     * Payments recorded against the order.
     */
    public function withPayments(PaymentApiFieldConfig $config): self {
        $this->fields['payments'] = $config;

        return $this;
    }

    /**
     * Closed documents issued for the order; each the same record as `GET /documents/{id}`, selectable through `documents.…`.
     */
    public function withDocuments(DocumentApiFieldConfig $config): self {
        $this->fields['documents'] = $config;

        return $this;
    }

    /**
     * Discounts applied to the order, each shown as its own line.
     */
    public function withDiscounts(OrderDiscountApiFieldConfig $config): self {
        $this->fields['discounts'] = $config;

        return $this;
    }

    /**
     * Shipments sent for the order.
     */
    public function withPackages(PackageApiFieldConfig $config): self {
        $this->fields['packages'] = $config;

        return $this;
    }

    /**
     * Warehouse picking and packing sessions logged for the order.
     */
    public function withPackagingHistories(OrderPackagingApiFieldConfig $config): self {
        $this->fields['packaging_histories'] = $config;

        return $this;
    }
}
