<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a PaymentApiEntity to fetch.
 */
final class PaymentApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the payment; the same value as `Order.payments[].id`.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * When the payment was received or booked.
     */
    public function withPaidAt(): self {
        $this->fields['paid_at'] = true;

        return $this;
    }

    /**
     * How the money arrived: `cod` (collected by the courier on delivery), `cash` (cash in person), `online` (card or payment gateway), `card_terminal` (card on a physical terminal), `bank_transfer`, `voucher` (a gift voucher or credit note), `loan` (an installment or consumer-credit provider), `internal` (a settlement between documents or orders, no money from the customer), `currency_diff` (a bookkeeping entry for an exchange-rate difference), `paypal` (historical). Null for a payment whose stored type has no public value.
     */
    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    /**
     * ISO 4217 code of the currency the customer paid in.
     */
    public function withCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    /**
     * Free note on the payment, such as the bank statement text. Null when there is none.
     */
    public function withNote(): self {
        $this->fields['note'] = true;

        return $this;
    }

    /**
     * Payment reference the payer quoted, which is how the payment was matched to the order. Null when none was given, for example on a cash payment.
     */
    public function withVariableSymbol(): self {
        $this->fields['variable_symbol'] = true;

        return $this;
    }

    /**
     * The amount paid, in the shop's main currency.
     */
    public function withAmount(): self {
        $this->fields['amount'] = true;

        return $this;
    }

    /**
     * The amount paid, in the currency it was paid in (`currency`).
     */
    public function withAmountInPaymentCurrency(): self {
        $this->fields['amount_in_payment_currency'] = true;

        return $this;
    }
}
