<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\DocumentApiFieldConfig;
use Simplia\Api\FieldConfig\OrderApiFieldConfig;

class PaymentApiFieldConfig extends AbstractApiFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withDate(): self {
        $this->fields['date'] = true;

        return $this;
    }

    public function withType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    public function withCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    public function withNote(): self {
        $this->fields['note'] = true;

        return $this;
    }

    public function withVariableSymbol(): self {
        $this->fields['variable_symbol'] = true;

        return $this;
    }

    public function withAmount(): self {
        $this->fields['amount'] = true;

        return $this;
    }

    public function withOrder(OrderApiFieldConfig $config): self {
        $this->fields['order'] = $config;

        return $this;
    }

    public function withInvoice(DocumentApiFieldConfig $config): self {
        $this->fields['invoice'] = $config;

        return $this;
    }
}
