<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a PricingApiEntity to fetch.
 */
final class PricingApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the price list; the `{pricing_id}` of the price operations.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the price list as shown in the shop's administration.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Stable code of the price list, unique across price lists.
     */
    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * ISO 4217 code of the currency every price in this list is in, and the currency a batch write must send.
     */
    public function withCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    /**
     * Whether the list takes part in price selection. An inactive list is ignored by the storefront but still readable here.
     */
    public function withActive(): self {
        $this->fields['active'] = true;

        return $this;
    }

    /**
     * Precedence among price lists: the lowest number wins when several lists match. Unique across lists.
     */
    public function withPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * When the list becomes eligible for selection. Null when there is no start bound.
     */
    public function withStartsAt(): self {
        $this->fields['starts_at'] = true;

        return $this;
    }

    /**
     * When the list stops being eligible for selection. Null when it never expires.
     */
    public function withEndsAt(): self {
        $this->fields['ends_at'] = true;

        return $this;
    }
}
