<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

use Simplia\Api3\FieldConfig\Label\LabelReferenceApiFieldConfig;
use Simplia\Api3\FieldConfig\Product\ProductAttributeApiFieldConfig;

/**
 * Which properties of a ProductApiEntity to fetch.
 */
final class ProductApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the product; the same value as `StockItem.product.id`. Not a stock item id.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Product name in the request language. Null when the product has no text in that language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * VAT rate applied to the product, as a percentage with two decimals (`21.00`).
     */
    public function withVatRate(): self {
        $this->fields['vat_rate'] = true;

        return $this;
    }

    /**
     * Short description shown in listings, in the request language, as HTML. Null when the product has no text in that language.
     */
    public function withShortDescription(): self {
        $this->fields['short_description'] = true;

        return $this;
    }

    /**
     * Full description in the request language, as HTML. Null when the product has no text in that language.
     */
    public function withLongDescription(): self {
        $this->fields['long_description'] = true;

        return $this;
    }

    /**
     * The brand the product is sold under; the same record as `GET /brands/{id}`. Null when none is set.
     */
    public function withBrand(BrandApiFieldConfig $config): self {
        $this->fields['brand'] = $config;

        return $this;
    }

    /**
     * The product's main image. Null when it has none.
     */
    public function withMainImage(ImageApiFieldConfig $config): self {
        $this->fields['main_image'] = $config;

        return $this;
    }

    /**
     * The product's own pictures in the shop's order. The main picture is among them when it is one of them; a main picture chosen from a variant's pictures appears only as `main_image`. Empty when the product has no pictures of its own.
     */
    public function withImages(ImageApiFieldConfig $config): self {
        $this->fields['images'] = $config;

        return $this;
    }

    /**
     * The supplier the shop buys the product from: the product's own supplier, or its brand's supplier when the product has none; the same record as `GET /suppliers/{id}`. Null when neither is set.
     */
    public function withSupplier(SupplierApiFieldConfig $config): self {
        $this->fields['supplier'] = $config;

        return $this;
    }

    /**
     * The shop's own code (SKU) of the product's stock item. Empty when none is set.
     */
    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * The supplier's or manufacturer's part number for the product. Null when none is set.
     */
    public function withCodeSupplier(): self {
        $this->fields['code_supplier'] = true;

        return $this;
    }

    /**
     * Barcode (EAN) of the product's stock item. Null when none is recorded.
     */
    public function withEan(): self {
        $this->fields['ean'] = true;

        return $this;
    }

    /**
     * The product's primary category, the one the `category` filter of `GET /products` matches; the same record as `GET /categories/{id}`.
     */
    public function withMainCategory(CategoryApiFieldConfig $config): self {
        $this->fields['main_category'] = $config;

        return $this;
    }

    /**
     * The product's further category assignments within this storefront's category tree; each the same record as `GET /categories/{id}`. Empty when there are none.
     */
    public function withCategories(CategoryApiFieldConfig $config): self {
        $this->fields['categories'] = $config;

        return $this;
    }

    /**
     * What the product says about itself in the shop's attributes — its colour, material, size — in the shop's order: for each, the attribute, and either one `value` or the chosen `values`. Empty when the product carries none.
     */
    public function withAttributes(ProductAttributeApiFieldConfig $config): self {
        $this->fields['attributes'] = $config;

        return $this;
    }

    /**
     * The labels pinned on the product, in the shop's order — every label assigned, whether or not it shows today (`GET /labels/{id}` says when and to whom). Empty when none is pinned.
     */
    public function withLabels(LabelReferenceApiFieldConfig $config): self {
        $this->fields['labels'] = $config;

        return $this;
    }

    /**
     * When the product was created.
     */
    public function withCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }
}
