<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\Product\ProductReferenceApiFieldConfig;
use Simplia\Api\FieldConfig\Question\QuestionAnswerApiFieldConfig;

/**
 * Which properties of a QuestionApiEntity to fetch.
 */
final class QuestionApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the question.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The product the question was asked about. Null when it was asked without one.
     */
    public function selectProduct(ProductReferenceApiFieldConfig $config): self {
        $this->fields['product'] = $config;

        return $this;
    }

    /**
     * The product name as recorded when the question was asked, which outlives the product. Null when none was recorded.
     */
    public function selectProductName(): self {
        $this->fields['product_name'] = true;

        return $this;
    }

    /**
     * The name the customer gave; when none was given, the storefront records the part of the e-mail address before the @ in its place. Null when nothing is recorded.
     */
    public function selectAuthor(): self {
        $this->fields['author'] = true;

        return $this;
    }

    /**
     * The question, as plain text with its line breaks. Null when empty.
     */
    public function selectText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    /**
     * State of the question: `open` (waiting for an answer), `postponed` (set aside by the shop), `answered`.
     */
    public function selectStatus(): self {
        $this->fields['status'] = true;

        return $this;
    }

    /**
     * The shop's answer, the HTML as it was sent to the customer. Null when the question has not been answered.
     */
    public function selectAnswer(QuestionAnswerApiFieldConfig $config): self {
        $this->fields['answer'] = $config;

        return $this;
    }

    /**
     * When the question was asked. The value the list sorts on by default.
     */
    public function selectCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }
}
