<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\Product\ProductReferenceApiFieldConfig;
use Simplia\Api\FieldConfig\Review\OrderReferenceApiFieldConfig;
use Simplia\Api\FieldConfig\Review\ReviewDetailsApiFieldConfig;
use Simplia\Api\FieldConfig\Review\ReviewReferenceApiFieldConfig;
use Simplia\Api\FieldConfig\Review\ReviewReplyApiFieldConfig;

/**
 * Which properties of a ReviewApiEntity to fetch.
 */
final class ReviewApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the review.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * What the review is about: a `product`, or an `order` (the shopping experience as a whole).
     */
    public function selectSubject(): self {
        $this->fields['subject'] = true;

        return $this;
    }

    /**
     * Where the review came from: `shop` for one written in the shop's own review form, otherwise the price-comparison portal it was imported from (Heureka, Zboží.cz, Biano, Árukereső, Compari or Pazaruvaj).
     */
    public function selectSource(): self {
        $this->fields['source'] = true;

        return $this;
    }

    /**
     * Moderation state: `pending` (not yet decided), `approved` (may be shown), `rejected`.
     */
    public function selectStatus(): self {
        $this->fields['status'] = true;

        return $this;
    }

    /**
     * The reviewed product. Null for a review of an order.
     */
    public function selectProduct(ProductReferenceApiFieldConfig $config): self {
        $this->fields['product'] = $config;

        return $this;
    }

    /**
     * The order the review is linked to: the reviewed order, or the order the reviewed product was bought in. Null when there is none or it was deleted.
     */
    public function selectOrder(OrderReferenceApiFieldConfig $config): self {
        $this->fields['order'] = $config;

        return $this;
    }

    /**
     * The name the reviewer gave, as it is shown with the review. Null when none was given.
     */
    public function selectAuthor(): self {
        $this->fields['author'] = true;

        return $this;
    }

    /**
     * Overall rating, 0 to 5 stars. Null when the reviewer gave none.
     */
    public function selectRating(): self {
        $this->fields['rating'] = true;

        return $this;
    }

    /**
     * The review text, as written. Null when the reviewer wrote none.
     */
    public function selectText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    /**
     * What the reviewer liked, when the form asked for it separately. Null when none was given.
     */
    public function selectPros(): self {
        $this->fields['pros'] = true;

        return $this;
    }

    /**
     * What the reviewer disliked, when the form asked for it separately. Null when none was given.
     */
    public function selectCons(): self {
        $this->fields['cons'] = true;

        return $this;
    }

    /**
     * The further answers of an order review: whether the customer recommends the shop and the star ratings of the delivery, the transport, the website, the communication and the pick-up. Null when the review stores none of them, which is the case for a product review.
     */
    public function selectDetails(ReviewDetailsApiFieldConfig $config): self {
        $this->fields['details'] = $config;

        return $this;
    }

    /**
     * The pictures the reviewer attached, in the shop's order. Empty when there are none.
     */
    public function selectImages(ImageApiFieldConfig $config): self {
        $this->fields['images'] = $config;

        return $this;
    }

    /**
     * The shop's reply to the review: the one written in the shop, or, for an imported review, the one the shop gave on the portal. Null when there is none.
     */
    public function selectReply(ReviewReplyApiFieldConfig $config): self {
        $this->fields['reply'] = $config;

        return $this;
    }

    /**
     * The language the review is written in, as the shop's own language code.
     */
    public function selectLanguage(): self {
        $this->fields['language'] = true;

        return $this;
    }

    /**
     * The review this one is a machine translation of. Null when this review is the original.
     */
    public function selectOriginal(ReviewReferenceApiFieldConfig $config): self {
        $this->fields['original'] = $config;

        return $this;
    }

    /**
     * The identifier the review carries on the portal it was imported from. Null when the review carries none.
     */
    public function selectExternalId(): self {
        $this->fields['external_id'] = true;

        return $this;
    }

    /**
     * When the review was written. The value the list sorts on by default.
     */
    public function selectCreatedAt(): self {
        $this->fields['created_at'] = true;

        return $this;
    }
}
