<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\StockItem\BundlePartApiFieldConfig;
use Simplia\Api\FieldConfig\StockItem\StockLevelApiFieldConfig;
use Simplia\Api\FieldConfig\StockItem\StorageLocationApiFieldConfig;
use Simplia\Api\FieldConfig\StockItem\VariantApiFieldConfig;

/**
 * Which properties of a StockItemApiEntity to fetch.
 */
final class StockItemApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the stock item. The value every write addresses (`stock_item_id`, `StockAmountItemInput.id`) and every reference carries (`Order.items[].stock_item.id`, `Price.stock_item_id`).
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * External handle of the stock item, always `P` followed by the id. Accepted by `POST /orders` as `stock_item_tracking_id`.
     */
    public function selectTrackingId(): self {
        $this->fields['tracking_id'] = true;

        return $this;
    }

    /**
     * The shop's own code (SKU) of the stock item. Empty when none is set.
     */
    public function selectCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * The supplier's or manufacturer's code for the stock item. Null when none is set.
     */
    public function selectCodeSupplier(): self {
        $this->fields['code_supplier'] = true;

        return $this;
    }

    /**
     * Barcode (EAN) of the stock item. Null when none is recorded.
     */
    public function selectEan(): self {
        $this->fields['ean'] = true;

        return $this;
    }

    /**
     * Undiscounted selling price of one unit including VAT, in the shop's main currency.
     */
    public function selectFullPrice(): self {
        $this->fields['full_price'] = true;

        return $this;
    }

    /**
     * Reference price shown struck through in the storefront, including VAT, in the shop's main currency. Display only, never used in a calculation; zero when none is set.
     */
    public function selectOriginalPrice(): self {
        $this->fields['original_price'] = true;

        return $this;
    }

    /**
     * Warehouse valuation of one unit without VAT, in the shop's main currency; the basis of the margin. Zero when none is set.
     */
    public function selectAccountingValue(): self {
        $this->fields['accounting_value'] = true;

        return $this;
    }

    /**
     * Percentage taken off `full_price` while the discount window is open. Wins over `discount_value`. Null when no percentage discount is configured.
     */
    public function selectDiscountPercentage(): self {
        $this->fields['discount_percentage'] = true;

        return $this;
    }

    /**
     * Fixed amount taken off `full_price` while the discount window is open, in the shop's main currency. Ignored when `discount_percentage` is set. Null when no fixed discount is configured.
     */
    public function selectDiscountValue(): self {
        $this->fields['discount_value'] = true;

        return $this;
    }

    /**
     * First day the discount applies, inclusive, compared by calendar day. The discount is active only when both bounds are set. Null when none is set.
     */
    public function selectDiscountStartsAt(): self {
        $this->fields['discount_starts_at'] = true;

        return $this;
    }

    /**
     * Last day the discount applies, inclusive, compared by calendar day. The discount is active only when both bounds are set. Null when none is set.
     */
    public function selectDiscountEndsAt(): self {
        $this->fields['discount_ends_at'] = true;

        return $this;
    }

    /**
     * Pieces in stock across every stock room, the sum of `stock_levels[].quantity`. For a bundle, the number of complete bundles that can be assembled.
     */
    public function selectTotalQuantity(): self {
        $this->fields['total_quantity'] = true;

        return $this;
    }

    /**
     * Pieces committed to open orders across every stock room, minus what has already been issued.
     */
    public function selectTotalReservedQuantity(): self {
        $this->fields['total_reserved_quantity'] = true;

        return $this;
    }

    /**
     * Pieces physically set aside for orders across every stock room; a subset of the reserved pieces.
     */
    public function selectTotalBlockedQuantity(): self {
        $this->fields['total_blocked_quantity'] = true;

        return $this;
    }

    /**
     * Delivery promise in hours until dispatch; 0 means in stock. The same value as `Availability.id`.
     */
    public function selectAvailabilityHours(): self {
        $this->fields['availability_hours'] = true;

        return $this;
    }

    /**
     * Date from which the item becomes available, when a future date is set; cleared automatically once it passes. Null otherwise.
     */
    public function selectAvailableAt(): self {
        $this->fields['available_at'] = true;

        return $this;
    }

    /**
     * Whether the shop reorders the item from its supplier, so it can be sold while out of stock.
     */
    public function selectDemandable(): self {
        $this->fields['demandable'] = true;

        return $this;
    }

    /**
     * Display name in the request language: the product's name, with the variant's value in parentheses for a variant.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Shelf positions the item is kept at: fixed assignments (quantity null) and live counts in stock rooms that track stock per position. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectStorageLocations(StorageLocationApiFieldConfig $config): self {
        $this->fields['storage_locations'] = $config;

        return $this;
    }

    /**
     * The catalog product the item belongs to; the same record as `GET /products/{id}`, selectable through `product.…`.
     */
    public function selectProduct(ProductApiFieldConfig $config): self {
        $this->fields['product'] = $config;

        return $this;
    }

    /**
     * The variant the item represents. Null when the item is the product itself. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectVariant(VariantApiFieldConfig $config): self {
        $this->fields['variant'] = $config;

        return $this;
    }

    /**
     * What the item is assembled from, when it is a bundle; empty otherwise. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectBundleParts(BundlePartApiFieldConfig $config): self {
        $this->fields['bundle_parts'] = $config;

        return $this;
    }

    /**
     * Stock and target levels per stock room; a room appears only once the item has had stock activity there. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectStockLevels(StockLevelApiFieldConfig $config): self {
        $this->fields['stock_levels'] = $config;

        return $this;
    }

    /**
     * Date of the first goods receipt from a supplier for this item. Null when it was never bought in. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectFirstPurchasedAt(): self {
        $this->fields['first_purchased_at'] = true;

        return $this;
    }

    /**
     * Date of the most recent goods receipt from a supplier. Null when it was never bought in. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectLastPurchasedAt(): self {
        $this->fields['last_purchased_at'] = true;

        return $this;
    }

    /**
     * Date of the most recent invoice or till receipt containing the item. Null when it was never sold. Included by default; a `fields` selection that does not name it leaves it out.
     */
    public function selectLastSoldAt(): self {
        $this->fields['last_sold_at'] = true;

        return $this;
    }
}
