<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a StorageLocationItemApiEntity to fetch.
 */
final class StorageLocationItemApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the assignment of the item to the position.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The stock item kept at the position; the same record as `GET /stock-items/{id}`, whose `storage_locations` name this position — any of its members selectable through `stock_item.…`.
     */
    public function selectStockItem(StockItemApiFieldConfig $config): self {
        $this->fields['stock_item'] = $config;

        return $this;
    }
}
