<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

use Simplia\Api\FieldConfig\Label\LabelReferenceApiFieldConfig;

/**
 * Which properties of a StorageLocationApiEntity to fetch.
 */
final class StorageLocationApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the position; the value `StockItem.storage_locations[].id` carries.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The stock room the position is in; the same object as `GET /stock-rooms/{id}`, and the value the `stock_room` filter takes.
     */
    public function selectStockRoom(StockRoomApiFieldConfig $config): self {
        $this->fields['stock_room'] = $config;

        return $this;
    }

    /**
     * Position code as written on the shelf label, such as `A1` or `A-03-2`; unique within its stock room.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Free-text note about the position. Null when there is none.
     */
    public function selectDescription(): self {
        $this->fields['description'] = true;

        return $this;
    }

    /**
     * Kind of position: `normal` (a shelf), `transitional` (a holding area for goods being received or prepared), `remote` (an external storage area), `mobile` (a mobile position, such as a picker's cart), `mobile_packaging_slot` (a packaging slot: the basket an order's picked items are gathered in), `mobile_admin` (a picker's own mobile position).
     */
    public function selectType(): self {
        $this->fields['type'] = true;

        return $this;
    }

    /**
     * How many pieces the position is meant to hold; 0 when no capacity is set.
     */
    public function selectCapacity(): self {
        $this->fields['capacity'] = true;

        return $this;
    }

    /**
     * Order of the position among the stock room's positions, lower first. Null when none is set.
     */
    public function selectPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * Whether the shop assigns incoming items to this position automatically, by its rules.
     */
    public function selectAutoAssign(): self {
        $this->fields['auto_assign'] = true;

        return $this;
    }

    /**
     * The value encoded in the position's barcode, which the warehouse scanner reads to select it.
     */
    public function selectBarcode(): self {
        $this->fields['barcode'] = true;

        return $this;
    }

    /**
     * The labels pinned on the position, in the shop's order — every label assigned, whether or not it shows today (`GET /labels/{id}` says when and to whom). Empty when none is pinned.
     */
    public function selectLabels(LabelReferenceApiFieldConfig $config): self {
        $this->fields['labels'] = $config;

        return $this;
    }
}
