<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a SupplierApiEntity to fetch.
 */
final class SupplierApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the supplier; the value `Product.supplier.id` and `Document.supplier.id` carry.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the supplier. Null when none is stored.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * The shop's own code for the supplier, the one its accounting export identifies the supplier by. Null when none is set.
     */
    public function selectCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    /**
     * ISO 4217 code of the currency the supplier invoices in, such as `EUR`.
     */
    public function selectCurrency(): self {
        $this->fields['currency'] = true;

        return $this;
    }

    /**
     * Whether the shop currently buys from the supplier. An inactive supplier is kept for the documents that name it.
     */
    public function selectActive(): self {
        $this->fields['active'] = true;

        return $this;
    }
}
