<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

/**
 * Which properties of a TextPageApiEntity to fetch.
 */
final class TextPageApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the page, shared by all its language versions.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Title of the page in the request language. Empty when none is stored.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Body of the page in the request language, as HTML. Empty when none is stored.
     */
    public function selectText(): self {
        $this->fields['text'] = true;

        return $this;
    }
}
