<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

/**
 * Which properties of a TransportMethodApiEntity to fetch.
 */
final class TransportMethodApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the transport method in the request language; the same value as `Order.transport_method.id`, and what `OrderDeliveryInput.transport_method_id` takes.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the transport method as shown to customers, in the request language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Code of the carrier that delivers it, as a lower-case slug such as `ppl`, `gls` or `dpd`; `osobne` for personal pickup at a store.
     */
    public function withCarrierCode(): self {
        $this->fields['carrier_code'] = true;

        return $this;
    }

    /**
     * Code of the carrier's service or parcel type this option uses, in the carrier's own vocabulary. Null when the carrier's default service is used.
     */
    public function withPackageTypeCode(): self {
        $this->fields['package_type_code'] = true;

        return $this;
    }

    /**
     * Position in the checkout list: the lowest number comes first.
     */
    public function withPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * The store the goods are collected at, for a personal-pickup option. Null for carrier delivery.
     */
    public function withStore(StoreApiFieldConfig $config): self {
        $this->fields['store'] = $config;

        return $this;
    }
}
