<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig;

use Simplia\Api3\FieldConfig\Order\ContactApiFieldConfig;

/**
 * Which properties of a UserApiEntity to fetch.
 */
final class UserApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the account; the same value as `Order.user.id`.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * E-mail address of the account, which is its login. Null when the account has none, such as one created at a till.
     */
    public function withEmail(): self {
        $this->fields['email'] = true;

        return $this;
    }

    /**
     * Loyalty card number of the customer, as printed on the card. Null when the customer has none.
     */
    public function withLoyaltyCard(): self {
        $this->fields['loyalty_card'] = true;

        return $this;
    }

    /**
     * Whether the customer buys at wholesale prices.
     */
    public function withWholesale(): self {
        $this->fields['wholesale'] = true;

        return $this;
    }

    /**
     * Personal discount of the customer, as a percentage taken off prices (5 for 5 %). Null when none is configured.
     */
    public function withDiscountPercentage(): self {
        $this->fields['discount_percentage'] = true;

        return $this;
    }

    /**
     * Bonus added to the customer's loyalty-points rate, as a decimal string such as `0.0040`; `0.0` means no bonus.
     */
    public function withPointsFactor(): self {
        $this->fields['points_factor'] = true;

        return $this;
    }

    /**
     * The customer's saved delivery address. Null when none is saved.
     */
    public function withDeliveryAddress(ContactApiFieldConfig $config): self {
        $this->fields['delivery_address'] = $config;

        return $this;
    }

    /**
     * The customer's saved billing address. Null when none is saved.
     */
    public function withInvoiceAddress(ContactApiFieldConfig $config): self {
        $this->fields['invoice_address'] = $config;

        return $this;
    }

    /**
     * The customer group the account belongs to. Null when it is in none.
     */
    public function withUserGroup(UserGroupApiFieldConfig $config): self {
        $this->fields['user_group'] = $config;

        return $this;
    }
}
