<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

class UserApiFieldConfig extends AbstractApiFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withWholesale(): self {
        $this->fields['wholesale'] = true;

        return $this;
    }

    public function withPointsFactor(): self {
        $this->fields['points_factor'] = true;

        return $this;
    }
}
