<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig;

class VoucherFieldConfig extends AbstractFieldConfig {
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    public function withCode(): self {
        $this->fields['code'] = true;

        return $this;
    }

    public function withValidFrom(): self {
        $this->fields['valid_from'] = true;

        return $this;
    }

    public function withValidTo(): self {
        $this->fields['valid_to'] = true;

        return $this;
    }

    public function withPriceValue(): self {
        $this->fields['price_value'] = true;

        return $this;
    }

    public function withActive(): self {
        $this->fields['active'] = true;

        return $this;
    }

    public function withGroup(VoucherGroupFieldConfig $config): self {
        $this->fields['group'] = $config;

        return $this;
    }

    public function withMaxUses(): self {
        $this->fields['max_uses'] = true;

        return $this;
    }

    public function withTotalUses(): self {
        $this->fields['total_uses'] = true;

        return $this;
    }

    public function withValid(): self {
        $this->fields['valid'] = true;

        return $this;
    }
}
