<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * What the attribute stands for, when the shop marked it: `size`, `color`, `gender`, `material`, `pattern`, `age_group`, `collection` or `season`. Null when it stands for nothing in particular.
 * Carried by Attribute.meaning.
 */
enum AttributeMeaning: string {
    case Size = 'size';
    case Color = 'color';
    case Gender = 'gender';
    case Material = 'material';
    case Pattern = 'pattern';
    case AgeGroup = 'age_group';
    case Collection = 'collection';
    case Season = 'season';
}
