<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * The kind of record the attribute describes: `product` (it appears in a product's `attributes`), `brand`, `store`, `customer` or `article`. Null for a kind this document does not name.
 * Carried by Attribute.applies_to.
 */
enum AttributeAppliesTo: string {
    case Product = 'product';
    case Brand = 'brand';
    case Store = 'store';
    case Customer = 'customer';
    case Article = 'article';
}
