<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * Kind of category: `normal` (products are assigned to it), `alias` (a link to another category, whose products and page it shows) or `automatic` (its products are selected by a rule).
 * Carried by Category.type.
 */
enum CategoryType: string {
    case Normal = 'normal';
    case Alias = 'alias';
    case Automatic = 'automatic';
}
