<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * What the comment was written under: a `product`, a `category` or an `article`. The matching one of `product`, `category` and `article` is set.
 * Carried by Comment.subject, comments.list?subject.
 */
enum CommentSubject: string {
    case Product = 'product';
    case Category = 'category';
    case Article = 'article';
}
