<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * Moderation state: `pending` (waiting for the shop's approval), `approved`. A rejected comment is deleted, so no third state exists.
 * Carried by Comment.status, comments.list?status.
 */
enum CommentStatus: string {
    case Pending = 'pending';
    case Approved = 'approved';
}
