<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * Whether the line is a bundle: `none` (an ordinary product), `bundle` (a set of different products sold together), `multipack` (several units of one product or its variants sold as one pack).
 * Carried by OrderItem.bundle_type.
 */
enum OrderItemBundleType: string {
    case None = 'none';
    case Bundle = 'bundle';
    case Multipack = 'multipack';
}
