<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * Delivery state last reported by the carrier: `unknown` (no tracking update yet), `on_the_way` (in transit), `delivered` (handed to the customer), `deposited` (waiting at a pickup point or parcel box), `returned` (not collected, sent back to the shop).
 * Carried by Package.status, Order.Package.status.
 */
enum PackageStatus: string {
    case Unknown = 'unknown';
    case OnTheWay = 'on_the_way';
    case Delivered = 'delivered';
    case Deposited = 'deposited';
    case Returned = 'returned';
}
