<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * How the money arrived: `cod` (collected by the courier on delivery), `cash` (cash in person), `online` (card or payment gateway), `card_terminal` (card on a physical terminal), `bank_transfer`, `voucher` (a gift voucher or credit note), `loan` (an installment or consumer-credit provider), `internal` (a settlement between documents or orders, no money from the customer), `currency_diff` (a bookkeeping entry for an exchange-rate difference), `paypal` (historical). Null for a payment whose stored type has no public value.
 * Carried by Payment.type, Order.Payment.type, payments.list?type.
 */
enum PaymentType: string {
    case Cod = 'cod';
    case Cash = 'cash';
    case Online = 'online';
    case CardTerminal = 'card_terminal';
    case CurrencyDiff = 'currency_diff';
    case Internal = 'internal';
    case Voucher = 'voucher';
    case BankTransfer = 'bank_transfer';
    case Paypal = 'paypal';
    case Loan = 'loan';
}
