<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * What the review is about: a `product`, or an `order` (the shopping experience as a whole).
 * Carried by Review.subject, reviews.list?subject.
 */
enum ReviewSubject: string {
    case Product = 'product';
    case Order = 'order';
}
