<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * Kind of position: `normal` (a shelf), `transitional` (a holding area for goods being received or prepared), `remote` (an external storage area), `mobile` (a mobile position, such as a picker's cart), `mobile_packaging_slot` (a packaging slot: the basket an order's picked items are gathered in), `mobile_admin` (a picker's own mobile position).
 * Carried by StorageLocation.type, storage-locations.list?type.
 */
enum StorageLocationType: string {
    case Normal = 'normal';
    case Transitional = 'transitional';
    case Remote = 'remote';
    case Mobile = 'mobile';
    case MobilePackagingSlot = 'mobile_packaging_slot';
    case MobileAdmin = 'mobile_admin';
}
