<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Enum;

/**
 * What the group's codes do: `percentage` (a percentage off), `amount` (an amount off), `n_plus_1` (buy several, one is free), `percentage_with_limit` (a percentage off, up to a limit), `percentage_most_expensive_with_limit` (a percentage off the most expensive item, up to a limit), `credit` (an amount credited). Null when the record does not say.
 * Carried by VoucherGroup.kind, voucher-groups.list?kind.
 */
enum VoucherGroupKind: string {
    case Percentage = 'percentage';
    case Amount = 'amount';
    case NPlus1 = 'n_plus_1';
    case PercentageMostExpensiveWithLimit = 'percentage_most_expensive_with_limit';
    case PercentageWithLimit = 'percentage_with_limit';
    case Credit = 'credit';
}
