<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Category;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\FieldConfig\Category\CategoryReferenceApiFieldConfig;

/**
 * A pointer to a category of the catalog tree: its identifier, its name in the request language and the names and identifiers of its ancestors, as it appears on a product. The full category is at GET /categories/{id}.
 */
final class CategoryReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the category; the value the `category` filter of `GET /products` takes.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Category name in the request language. Null when the category has no text in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Names of the category and its ancestors, root first, joined by `|`, such as `Phones|Apple|iPhone`. An ancestor without a name in the request language leaves an empty segment.
     */
    public function getPath(): string {
        return $this->readString('path');
    }

    /**
     * Identifiers of the category and its ancestors, root first, this category last; one entry per segment of `path`.
     * @return list<int>
     */
    public function getPathIds(): array {
        return $this->readIntList('path_ids');
    }

    public static function createFieldConfig(): CategoryReferenceApiFieldConfig {
        return new CategoryReferenceApiFieldConfig();
    }
}
