<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Article;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a ArticleReferenceApiEntity to fetch.
 */
final class ArticleReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the article; the same value as `Article.id`.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name of the article. Null when the article no longer exists or has no name.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }
}
