<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Review;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a ReviewDetailsApiEntity to fetch.
 */
final class ReviewDetailsApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Whether the customer would recommend the shop. Null when not asked, or not stored as a yes or no.
     */
    public function selectRecommends(): self {
        $this->fields['recommends'] = true;

        return $this;
    }

    /**
     * Delivery time, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectDeliveryTime(): self {
        $this->fields['delivery_time'] = true;

        return $this;
    }

    /**
     * Quality of the transport, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectTransportQuality(): self {
        $this->fields['transport_quality'] = true;

        return $this;
    }

    /**
     * Ease of use of the website, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectWebUsability(): self {
        $this->fields['web_usability'] = true;

        return $this;
    }

    /**
     * Communication with the shop, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectCommunication(): self {
        $this->fields['communication'] = true;

        return $this;
    }

    /**
     * Waiting time at the pick-up point, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectPickupTime(): self {
        $this->fields['pickup_time'] = true;

        return $this;
    }

    /**
     * Quality of the pick-up, 0 to 5 stars in half-star steps. Null when not rated, or not stored as a number.
     */
    public function selectPickupQuality(): self {
        $this->fields['pickup_quality'] = true;

        return $this;
    }
}
