<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Review;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api\FieldConfig\Admin\AdminReferenceApiFieldConfig;

/**
 * Which properties of a ReviewReplyApiEntity to fetch.
 */
final class ReviewReplyApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * The reply, as written.
     */
    public function selectText(): self {
        $this->fields['text'] = true;

        return $this;
    }

    /**
     * When the reply was written in the shop. Null for a reply the shop gave on the portal the review came from.
     */
    public function selectRepliedAt(): self {
        $this->fields['replied_at'] = true;

        return $this;
    }

    /**
     * The staff account that wrote the reply in the shop. Null for a reply given on the portal, or when the account was deleted.
     */
    public function selectRepliedBy(AdminReferenceApiFieldConfig $config): self {
        $this->fields['replied_by'] = $config;

        return $this;
    }
}
