<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Review;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a ReviewReferenceApiEntity to fetch.
 */
final class ReviewReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the review; the same value as `Review.id`.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The language that review is written in, as the shop's own language code.
     */
    public function withLanguage(): self {
        $this->fields['language'] = true;

        return $this;
    }
}
