<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Label;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\Entity\ImageApiEntity;
use Simplia\Api3\FieldConfig\Label\LabelReferenceApiFieldConfig;

/**
 * A pointer at a label: its id, code, name in the request language, colour and picture — what a badge needs; the whole record, with where, when and to whom it shows, is `GET /labels/{id}`.
 */
final class LabelReferenceApiEntity extends AbstractApiEntity {
    /**
     * Label id; `GET /labels/{id}` answers the whole record.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The short code the shop gave the label. Null when it has none.
     */
    public function getCode(): ?string {
        return $this->readStringOrNull('code');
    }

    /**
     * Name in the request language. Null when the label has no name in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * The label's colour as a hexadecimal `#rrggbb` value. Null when the shop set none.
     */
    public function getColor(): ?string {
        return $this->readStringOrNull('color');
    }

    /**
     * The label's picture, shown in place of its name when the shop stored one. Null when none is stored.
     */
    public function getImage(): ?ImageApiEntity {
        return $this->readEntityOrNull('image', ImageApiEntity::class);
    }

    public static function createFieldConfig(): LabelReferenceApiFieldConfig {
        return new LabelReferenceApiFieldConfig();
    }
}
