<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Attribute;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a AttributeValueReferenceApiEntity to fetch.
 */
final class AttributeValueReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Value id, one of the `values[].id` of the attribute.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name in the request language. Null when the value has no name in that language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }
}
