<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Attribute;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api\FieldConfig\ImageApiFieldConfig;

/**
 * Which properties of a AttributeValueApiEntity to fetch.
 */
final class AttributeValueApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Value id, the `id` an entry of a product's `attributes[].values` carries.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name in the request language. Null when the value has no name in that language.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Position among the attribute's values; lower first.
     */
    public function selectPriority(): self {
        $this->fields['priority'] = true;

        return $this;
    }

    /**
     * A picture standing for the value — a colour swatch, a pattern — when the shop stored one. Null when none is stored.
     */
    public function selectImage(ImageApiFieldConfig $config): self {
        $this->fields['image'] = $config;

        return $this;
    }
}
