<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Attribute;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a AttributeReferenceApiEntity to fetch.
 */
final class AttributeReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Attribute id; `GET /attributes/{id}` answers the whole record.
     */
    public function selectId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Name in the request language. Null when the attribute has no name in that language.
     */
    public function selectName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Unit of the value in the request language ("cm", "kg"), as the shop wrote it. Null when the attribute has none.
     */
    public function selectUnit(): self {
        $this->fields['unit'] = true;

        return $this;
    }

    /**
     * What a value of the attribute is: `text`, `integer` or `boolean` (the row carries one `value`), `choice` (one of the attribute's values, in `values`) or `multi_choice` (several, in `values`).
     */
    public function selectType(): self {
        $this->fields['type'] = true;

        return $this;
    }
}
