<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Admin;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\FieldConfig\Admin\AdminReferenceApiFieldConfig;

/**
 * A pointer to a staff account of the shop: the person who issued a document, entered an order or handled it in the warehouse. Not a customer. The full account is at GET /admins/{id}.
 */
final class AdminReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the staff account; the same value as `Admin.id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Given name. Null when not filled.
     */
    public function getFirstName(): ?string {
        return $this->readStringOrNull('first_name');
    }

    /**
     * Family name. Null when not filled.
     */
    public function getLastName(): ?string {
        return $this->readStringOrNull('last_name');
    }

    public static function createFieldConfig(): AdminReferenceApiFieldConfig {
        return new AdminReferenceApiFieldConfig();
    }
}
