<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Order;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\Entity\AdminApiEntity;
use Simplia\Api\FieldConfig\Order\OrderPackagingApiFieldConfig;

/**
 * One warehouse session spent preparing an order: who collected the goods (picking) and who boxed them (packing), and when each stage started and ended. An order can have several, for example after a re-pick.
 */
final class OrderPackagingApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the session. Not addressable by any endpoint.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The staff account that collected the goods from the shelves; the same record as `GET /admins/{id}`. Null when picking has not started or is not attributed.
     */
    public function getPickedBy(): ?AdminApiEntity {
        return $this->readEntityOrNull('picked_by', AdminApiEntity::class);
    }

    /**
     * When collecting the goods began. Null when it has not started.
     */
    public function getPickingStartedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('picking_started_at');
    }

    /**
     * When collecting the goods finished. Null when it has not finished.
     */
    public function getPickingEndedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('picking_ended_at');
    }

    /**
     * The staff account that boxed the goods; the same record as `GET /admins/{id}`. Null when packing has not started or is not attributed.
     */
    public function getPackagedBy(): ?AdminApiEntity {
        return $this->readEntityOrNull('packaged_by', AdminApiEntity::class);
    }

    /**
     * When boxing began. Null when it has not started.
     */
    public function getPackagingStartedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('packaging_started_at');
    }

    /**
     * When boxing finished and the parcel was ready for the carrier. Null when it has not finished.
     */
    public function getPackagingEndedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('packaging_ended_at');
    }

    public static function createFieldConfig(): OrderPackagingApiFieldConfig {
        return new OrderPackagingApiFieldConfig();
    }
}
