<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `articles.list` (GET /api/3/articles).
 */
final class ArticlesApiRequest extends AbstractApiRequest {
    /**
     * Filter by article ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }

    /**
     * Filter by the identifier of the article's topic (section); 0 or greater, where 0 means no filter. A non-integer or negative value is a 422 violation.
     */
    public function whereTopic(int $topic): self {
        $this->params['topic'] = $topic;

        return $this;
    }
}
