<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

/**
 * The filters and the sort of `attributes.list` (GET /api/3/attributes).
 */
final class AttributesApiRequest extends AbstractApiRequest {
    /**
     * Filter by attribute ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    public function orderByPriorityAsc(): self {
        $this->params['sort'] = 'priority';

        return $this;
    }

    public function orderByPriorityDesc(): self {
        $this->params['sort'] = '-priority';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
