<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `categories.list` (GET /api/3/categories).
 */
final class CategoriesApiRequest extends AbstractApiRequest {
    /**
     * Filter by category ids, within the listed content group (storefront tree). Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Only the direct subcategories of the category with this identifier; not recursive. A non-integer or value below 1 is a 422 violation.
     */
    public function whereParent(int $parent): self {
        $this->params['parent'] = $parent;

        return $this;
    }

    /**
     * Only categories at this depth of the tree; 0 lists the roots. A non-integer or negative value is a 422 violation.
     */
    public function whereLevel(int $level): self {
        $this->params['level'] = $level;

        return $this;
    }

    /**
     * Only the categories of the content group (storefront tree) with this identifier, from `GET /content-groups`; without it, the list is the tree of the storefront being called. A non-integer or value below 1 is a 422 violation; an identifier that names no group lists nothing.
     */
    public function whereContentGroup(int $contentGroup): self {
        $this->params['content_group'] = $contentGroup;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }

    public function orderByLevelAsc(): self {
        $this->params['sort'] = 'level';

        return $this;
    }

    public function orderByLevelDesc(): self {
        $this->params['sort'] = '-level';

        return $this;
    }

    public function orderByUpdatedAtAsc(): self {
        $this->params['sort'] = 'updated_at';

        return $this;
    }

    public function orderByUpdatedAtDesc(): self {
        $this->params['sort'] = '-updated_at';

        return $this;
    }
}
