<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `comments.list` (GET /api/3/comments).
 */
final class CommentsApiRequest extends AbstractApiRequest {
    /**
     * Filter by comment ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Only the comments written under a product, a category or an article. An unknown value is a 422 violation.
     * @param 'product'|'category'|'article' $subject
     */
    public function whereSubject(string $subject): self {
        $this->params['subject'] = $subject;

        return $this;
    }

    /**
     * Only the comments written under the product with this identifier. A non-integer or value below 1 is a 422 violation.
     */
    public function whereProduct(int $product): self {
        $this->params['product'] = $product;

        return $this;
    }

    /**
     * Only the comments written under the category with this identifier. A non-integer or value below 1 is a 422 violation.
     */
    public function whereCategory(int $category): self {
        $this->params['category'] = $category;

        return $this;
    }

    /**
     * Only the comments written under the article with this identifier. A non-integer or value below 1 is a 422 violation.
     */
    public function whereArticle(int $article): self {
        $this->params['article'] = $article;

        return $this;
    }

    /**
     * Only the replies to the comment with this identifier. A non-integer or value below 1 is a 422 violation.
     */
    public function whereParent(int $parent): self {
        $this->params['parent'] = $parent;

        return $this;
    }

    /**
     * Only the comments in this moderation state. An unknown value is a 422 violation.
     * @param 'pending'|'approved' $status
     */
    public function whereStatus(string $status): self {
        $this->params['status'] = $status;

        return $this;
    }

    public function orderByCreatedAtAsc(): self {
        $this->params['sort'] = 'created_at';

        return $this;
    }

    public function orderByCreatedAtDesc(): self {
        $this->params['sort'] = '-created_at';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
