<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

/**
 * The filters and the sort of `labels.list` (GET /api/3/labels).
 */
final class LabelsApiRequest extends AbstractApiRequest {
    /**
     * Filter by label ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    public function orderByPriorityAsc(): self {
        $this->params['sort'] = 'priority';

        return $this;
    }

    public function orderByPriorityDesc(): self {
        $this->params['sort'] = '-priority';

        return $this;
    }

    public function orderByStartsAtAsc(): self {
        $this->params['sort'] = 'starts_at';

        return $this;
    }

    public function orderByStartsAtDesc(): self {
        $this->params['sort'] = '-starts_at';

        return $this;
    }

    public function orderByEndsAtAsc(): self {
        $this->params['sort'] = 'ends_at';

        return $this;
    }

    public function orderByEndsAtDesc(): self {
        $this->params['sort'] = '-ends_at';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
