<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

/**
 * The filters and the sort of `orders.list` (GET /api/3/orders).
 */
final class OrdersApiRequest extends AbstractApiRequest {
    /**
     * Filter by order status. Repeatable; allowed: unprocessed, processed, waiting, ready, finished, cancelled (422 otherwise).
     * @param list<'unprocessed'|'processed'|'waiting'|'ready'|'finished'|'cancelled'> $status
     */
    public function whereStatus(array $status): self {
        $this->params['status'] = $status;

        return $this;
    }

    /**
     * Orders of the customer with exactly this e-mail address, case-insensitively. A malformed address is a 400.
     */
    public function whereEmail(string $email): self {
        $this->params['email'] = $email;

        return $this;
    }

    /**
     * Orders of the customer with this phone number; spaces are ignored.
     */
    public function wherePhone(string $phone): self {
        $this->params['phone'] = $phone;

        return $this;
    }

    /**
     * Orders created on/after this date. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereCreatedAtFrom(\DateTimeInterface|string $createdAtFrom): self {
        $this->params['created_at_from'] = $createdAtFrom instanceof \DateTimeInterface ? $createdAtFrom->format(\DateTimeInterface::ATOM) : $createdAtFrom;

        return $this;
    }

    /**
     * Orders created on/before this date, the whole day included. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereCreatedAtTo(\DateTimeInterface|string $createdAtTo): self {
        $this->params['created_at_to'] = $createdAtTo instanceof \DateTimeInterface ? $createdAtTo->format(\DateTimeInterface::ATOM) : $createdAtTo;

        return $this;
    }

    /**
     * Status changed on/after this date. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereStatusChangedAtFrom(\DateTimeInterface|string $statusChangedAtFrom): self {
        $this->params['status_changed_at_from'] = $statusChangedAtFrom instanceof \DateTimeInterface ? $statusChangedAtFrom->format(\DateTimeInterface::ATOM) : $statusChangedAtFrom;

        return $this;
    }

    /**
     * Status changed on/before this date, the whole day included. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereStatusChangedAtTo(\DateTimeInterface|string $statusChangedAtTo): self {
        $this->params['status_changed_at_to'] = $statusChangedAtTo instanceof \DateTimeInterface ? $statusChangedAtTo->format(\DateTimeInterface::ATOM) : $statusChangedAtTo;

        return $this;
    }

    /**
     * Orders last modified on/after this date. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereUpdatedAtFrom(\DateTimeInterface|string $updatedAtFrom): self {
        $this->params['updated_at_from'] = $updatedAtFrom instanceof \DateTimeInterface ? $updatedAtFrom->format(\DateTimeInterface::ATOM) : $updatedAtFrom;

        return $this;
    }

    /**
     * Orders last modified on/before this date, the whole day included. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereUpdatedAtTo(\DateTimeInterface|string $updatedAtTo): self {
        $this->params['updated_at_to'] = $updatedAtTo instanceof \DateTimeInterface ? $updatedAtTo->format(\DateTimeInterface::ATOM) : $updatedAtTo;

        return $this;
    }

    /**
     * true: orders of wholesale customer accounts only. false: every other order, including guest orders.
     */
    public function whereWholesale(bool $wholesale): self {
        $this->params['wholesale'] = $wholesale ? 'true' : 'false';

        return $this;
    }

    /**
     * Orders whose dispatch is postponed to on/after this day. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereDelayedUntilDateFrom(\DateTimeInterface|string $delayedUntilDateFrom): self {
        $this->params['delayed_until_date_from'] = $delayedUntilDateFrom instanceof \DateTimeInterface ? $delayedUntilDateFrom->format(\DateTimeInterface::ATOM) : $delayedUntilDateFrom;

        return $this;
    }

    /**
     * Orders whose dispatch is postponed to on/before this day, the whole day included. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereDelayedUntilDateTo(\DateTimeInterface|string $delayedUntilDateTo): self {
        $this->params['delayed_until_date_to'] = $delayedUntilDateTo instanceof \DateTimeInterface ? $delayedUntilDateTo->format(\DateTimeInterface::ATOM) : $delayedUntilDateTo;

        return $this;
    }

    /**
     * Orders expected to dispatch on/after this day. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereExpectedDispatchDateFrom(\DateTimeInterface|string $expectedDispatchDateFrom): self {
        $this->params['expected_dispatch_date_from'] = $expectedDispatchDateFrom instanceof \DateTimeInterface ? $expectedDispatchDateFrom->format(\DateTimeInterface::ATOM) : $expectedDispatchDateFrom;

        return $this;
    }

    /**
     * Orders expected to dispatch on/before this day, the whole day included. A date-time (2026-09-09T14:30:00, optionally with an offset) bounds by that instant instead.
     */
    public function whereExpectedDispatchDateTo(\DateTimeInterface|string $expectedDispatchDateTo): self {
        $this->params['expected_dispatch_date_to'] = $expectedDispatchDateTo instanceof \DateTimeInterface ? $expectedDispatchDateTo->format(\DateTimeInterface::ATOM) : $expectedDispatchDateTo;

        return $this;
    }

    /**
     * Filter by order ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    public function orderByCreatedAtAsc(): self {
        $this->params['sort'] = 'created_at';

        return $this;
    }

    public function orderByCreatedAtDesc(): self {
        $this->params['sort'] = '-created_at';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
