<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

use Simplia\Api\Enum\OrderStatus;

/**
 * The filters and the sort of `order-items.list` (GET /api/3/order-items).
 */
final class OrderItemsApiRequest extends AbstractApiRequest {
    /**
     * Filter by the status of the owning order. When absent, lines of finished and cancelled orders are excluded. Repeatable; allowed: unprocessed, processed, waiting, ready, finished, cancelled (422 otherwise).
     * @param list<OrderStatus> $orderStatus
     */
    public function whereOrderStatus(array $orderStatus): self {
        self::validateArray($orderStatus, OrderStatus::class);
        $this->params['order_status'] = array_map(static fn(OrderStatus $value): string => $value->value, $orderStatus);

        return $this;
    }

    /**
     * Filter by the code (SKU) of the linked stock item. Lines without a linked stock item are not returned. Repeatable (`codes[]=A&codes[]=B`); every element must be a non-blank string of at most 255 characters (422 otherwise); unknown codes are silently absent.
     * @param list<string> $codes
     */
    public function whereCodes(array $codes): self {
        $this->params['codes'] = $codes;

        return $this;
    }

    /**
     * Filter by the supplier's code of the linked stock item. Lines without a linked stock item are not returned. Repeatable (`codes_supplier[]=A&codes_supplier[]=B`); every element must be a non-blank string of at most 255 characters (422 otherwise); unknown codes are silently absent.
     * @param list<string> $codesSupplier
     */
    public function whereCodesSupplier(array $codesSupplier): self {
        $this->params['codes_supplier'] = $codesSupplier;

        return $this;
    }

    /**
     * Filter by order-item ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
