<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `products.list` (GET /api/3/products).
 */
final class ProductsApiRequest extends AbstractApiRequest {
    /**
     * Filter by product code (the code property). Repeatable (`codes[]=A&codes[]=B`); every element must be a non-blank string of at most 255 characters (422 otherwise); unknown codes are silently absent.
     * @param list<string> $codes
     */
    public function whereCodes(array $codes): self {
        $this->params['codes'] = $codes;

        return $this;
    }

    /**
     * Filter by product ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * When true, only products whose own stock item has a positive quantity in stock. Accepts true/false; false is a no-op; anything else is a 422 violation.
     */
    public function whereInStock(bool $inStock): self {
        $this->params['in_stock'] = $inStock ? 'true' : 'false';

        return $this;
    }

    /**
     * Filter by primary category id (the main_category.id value); not recursive. A non-integer or value below 1 is a 422 violation.
     */
    public function whereCategory(int $category): self {
        $this->params['category'] = $category;

        return $this;
    }

    /**
     * Case-insensitive substring search over the request-language product name. Untranslated products cannot match. Minimum 3 characters after trimming (a shorter value, blank included, is a 422 violation — omit the parameter for no search); not combinable with with_total (422) — the substring scan is unindexed and a total over it is unbounded.
     */
    public function whereQ(string $q): self {
        $this->params['q'] = $q;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }

    public function orderByCreatedAtAsc(): self {
        $this->params['sort'] = 'created_at';

        return $this;
    }

    public function orderByCreatedAtDesc(): self {
        $this->params['sort'] = '-created_at';

        return $this;
    }
}
