<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

/**
 * The filters and the sort of `questions.list` (GET /api/3/questions).
 */
final class QuestionsApiRequest extends AbstractApiRequest {
    /**
     * Filter by question ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Only the questions asked about the product with this identifier. A non-integer or value below 1 is a 422 violation.
     */
    public function whereProduct(int $product): self {
        $this->params['product'] = $product;

        return $this;
    }

    /**
     * Only the questions in this state. An unknown value is a 422 violation.
     * @param 'open'|'postponed'|'answered' $status
     */
    public function whereStatus(string $status): self {
        $this->params['status'] = $status;

        return $this;
    }

    public function orderByCreatedAtAsc(): self {
        $this->params['sort'] = 'created_at';

        return $this;
    }

    public function orderByCreatedAtDesc(): self {
        $this->params['sort'] = '-created_at';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
