<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

class StockItemApiRequest extends AbstractApiRequest {
    /**
     * @param int[] $ids Stock item IDs
     * @return $this
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * @param string[] $codes Stock item codes
     * @return $this
     */
    public function whereCodes(array $codes): self {
        $this->params['codes'] = $codes;

        return $this;
    }

    /**
     * @param string[] $codesSupplier Stock item supplier codes
     * @return $this
     */
    public function whereCodesSupplier(array $codesSupplier): self {
        $this->params['codes_supplier'] = $codesSupplier;

        return $this;
    }

    /**
     * @param int $supplierId Supplier ID
     * @return $this
     */
    public function whereSupplierId(int $supplierId): self {
        $this->params['supplier_id'] = $supplierId;

        return $this;
    }

    /**
     * @param bool $inStock Only items currently in stock
     * @return $this
     */
    public function whereInStock(bool $inStock): self {
        $this->params['in_stock'] = $inStock ? 'true' : 'false';

        return $this;
    }
}
