<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `storage-locations.list_items` (GET /api/3/storage-locations/{id}/items).
 */
final class StorageLocationsItemsApiRequest extends AbstractApiRequest {
    /**
     * Filter by assignment ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Filter by stock item ids (the `stock_item.id` property). Repeatable (`stock_item_ids[]=1&stock_item_ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $stockItemIds
     */
    public function whereStockItemIds(array $stockItemIds): self {
        $this->params['stock_item_ids'] = $stockItemIds;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
