<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Request;

/**
 * The filters and the sort of `storage-locations.list` (GET /api/3/storage-locations).
 */
final class StorageLocationsApiRequest extends AbstractApiRequest {
    /**
     * Filter by storage location ids. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Only the positions of the stock room with this identifier, from `GET /stock-rooms`. A non-integer or value below 1 is a 422 violation; an identifier that names no stock room lists nothing.
     */
    public function whereStockRoom(int $stockRoom): self {
        $this->params['stock_room'] = $stockRoom;

        return $this;
    }

    /**
     * Only the positions of this kind. An unknown value is a 422 violation.
     * @param 'normal'|'transitional'|'remote'|'mobile'|'mobile_packaging_slot'|'mobile_admin' $type
     */
    public function whereType(string $type): self {
        $this->params['type'] = $type;

        return $this;
    }

    public function orderByNameAsc(): self {
        $this->params['sort'] = 'name';

        return $this;
    }

    public function orderByNameDesc(): self {
        $this->params['sort'] = '-name';

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
