<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Request;

/**
 * The filters and the sort of `vouchers.list` (GET /api/3/vouchers).
 */
final class VouchersApiRequest extends AbstractApiRequest {
    /**
     * Filter by voucher ids, within the listed content group. Repeatable (`ids[]=1&ids[]=2`); every element must be an integer (digits only; 422 otherwise); unknown ids are silently absent.
     * @param list<int> $ids
     */
    public function whereIds(array $ids): self {
        $this->params['ids'] = $ids;

        return $this;
    }

    /**
     * Only the codes of the voucher group with this identifier, from `GET /voucher-groups`. A non-integer or value below 1 is a 422 violation; an identifier that names no group lists nothing.
     */
    public function whereGroup(int $group): self {
        $this->params['group'] = $group;

        return $this;
    }

    /**
     * Only the codes in circulation (`true`), or only the prepared, inactive ones (`false`). A value other than true or false is a 422 violation.
     */
    public function whereActive(bool $active): self {
        $this->params['active'] = $active ? 'true' : 'false';

        return $this;
    }

    /**
     * Only the codes of the content group (storefront tree) with this identifier, from `GET /content-groups`; without it, the list is the content group of the storefront being called. A non-integer or value below 1 is a 422 violation; an identifier that names no content group lists nothing.
     */
    public function whereContentGroup(int $contentGroup): self {
        $this->params['content_group'] = $contentGroup;

        return $this;
    }

    public function orderByIdAsc(): self {
        $this->params['sort'] = 'id';

        return $this;
    }

    public function orderByIdDesc(): self {
        $this->params['sort'] = '-id';

        return $this;
    }
}
