<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Attribute;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\FieldConfig\Attribute\AttributeValueReferenceApiFieldConfig;

/**
 * One chosen value: its id and its name in the request language; the value's own record, with its position and picture, is an entry of `values` of `GET /attributes/{id}`.
 */
final class AttributeValueReferenceApiEntity extends AbstractApiEntity {
    /**
     * Value id, one of the `values[].id` of the attribute.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name in the request language. Null when the value has no name in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    public static function createFieldConfig(): AttributeValueReferenceApiFieldConfig {
        return new AttributeValueReferenceApiFieldConfig();
    }
}
