<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Attribute;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\FieldConfig\Attribute\AttributeReferenceApiFieldConfig;

/**
 * A pointer at an attribute: its id, its name and unit in the request language and its kind — what a row of a product's `attributes` needs to be read; the whole record, with its values, is `GET /attributes/{id}`.
 */
final class AttributeReferenceApiEntity extends AbstractApiEntity {
    /**
     * Attribute id; `GET /attributes/{id}` answers the whole record.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * Name in the request language. Null when the attribute has no name in that language.
     */
    public function getName(): ?string {
        return $this->readStringOrNull('name');
    }

    /**
     * Unit of the value in the request language ("cm", "kg"), as the shop wrote it. Null when the attribute has none.
     */
    public function getUnit(): ?string {
        return $this->readStringOrNull('unit');
    }

    /**
     * What a value of the attribute is: `text`, `integer` or `boolean` (the row carries one `value`), `choice` (one of the attribute's values, in `values`) or `multi_choice` (several, in `values`).
     * @return 'boolean'|'choice'|'multi_choice'|'text'|'integer'
     * @phpstan-return string
     */
    public function getType(): string {
        return $this->readString('type');
    }

    public static function createFieldConfig(): AttributeReferenceApiFieldConfig {
        return new AttributeReferenceApiFieldConfig();
    }
}
