<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Voucher;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\Entity\VoucherApiEntity;
use Simplia\Api3\FieldConfig\Voucher\VoucherLockApiFieldConfig;

/**
 * A short-lived reservation of a voucher code, so that two checkouts cannot redeem the same code at once. The holder is identified by the key it chose.
 */
final class VoucherLockApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the lock; the value the `ids` filter of `GET /vouchers/{code}/locks` takes. A lock is released by its `key`, not by this id.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The token the holder chose when taking the lock. Present it again to activate, apply or release; a different key is refused with 409.
     */
    public function getKey(): string {
        return $this->readString('key');
    }

    /**
     * When the lock was taken.
     */
    public function getLockedAt(): \DateTimeImmutable {
        return $this->readDateTime('locked_at');
    }

    /**
     * When the lock lapses on its own; after that it no longer blocks anyone and is no longer listed.
     */
    public function getExpiresAt(): \DateTimeImmutable {
        return $this->readDateTime('expires_at');
    }

    /**
     * The locked voucher, in full.
     */
    public function getVoucher(): ?VoucherApiEntity {
        return $this->readEntityOrNull('voucher', VoucherApiEntity::class);
    }

    public static function createFieldConfig(): VoucherLockApiFieldConfig {
        return new VoucherLockApiFieldConfig();
    }
}
