<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Review;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\FieldConfig\Review\OrderReferenceApiFieldConfig;

/**
 * A pointer to the customer order a document was issued for: the order's identifiers only. The full order is at GET /orders/{id}.
 */
final class OrderReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the order; the same value as `Order.id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The order number shown to customers and staff; the same value as `Order.code`. Null when the order has none.
     */
    public function getCode(): ?string {
        return $this->readStringOrNull('code');
    }

    public static function createFieldConfig(): OrderReferenceApiFieldConfig {
        return new OrderReferenceApiFieldConfig();
    }
}
