<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Entity\Review;

use Simplia\Api3\Entity\AbstractApiEntity;
use Simplia\Api3\FieldConfig\Review\ReviewReferenceApiFieldConfig;

/**
 * A pointer at another review: its id and the language it is written in; the whole record is `GET /reviews/{id}`.
 */
final class ReviewReferenceApiEntity extends AbstractApiEntity {
    /**
     * Numeric identifier of the review; the same value as `Review.id`.
     */
    public function getId(): int {
        return $this->readInt('id');
    }

    /**
     * The language that review is written in, as the shop's own language code.
     */
    public function getLanguage(): string {
        return $this->readString('language');
    }

    public static function createFieldConfig(): ReviewReferenceApiFieldConfig {
        return new ReviewReferenceApiFieldConfig();
    }
}
