<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Entity\Review;

use Simplia\Api\Entity\AbstractApiEntity;
use Simplia\Api\Entity\Admin\AdminReferenceApiEntity;
use Simplia\Api\FieldConfig\Review\ReviewReplyApiFieldConfig;

/**
 * The shop's reply to a review: what was said, when, and by which staff account when it was written in the shop.
 */
final class ReviewReplyApiEntity extends AbstractApiEntity {
    /**
     * The reply, as written.
     */
    public function getText(): string {
        return $this->readString('text');
    }

    /**
     * When the reply was written in the shop. Null for a reply the shop gave on the portal the review came from.
     */
    public function getRepliedAt(): ?\DateTimeImmutable {
        return $this->readDateTimeOrNull('replied_at');
    }

    /**
     * The staff account that wrote the reply in the shop. Null for a reply given on the portal, or when the account was deleted.
     */
    public function getRepliedBy(): ?AdminReferenceApiEntity {
        return $this->readEntityOrNull('replied_by', AdminReferenceApiEntity::class);
    }

    public static function createFieldConfig(): ReviewReplyApiFieldConfig {
        return new ReviewReplyApiFieldConfig();
    }
}
