<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\FieldConfig\Voucher;

use Simplia\Api3\FieldConfig\AbstractApiFieldConfig;
use Simplia\Api3\FieldConfig\VoucherApiFieldConfig;

/**
 * Which properties of a VoucherLockApiEntity to fetch.
 */
final class VoucherLockApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the lock; the value the `ids` filter of `GET /vouchers/{code}/locks` takes. A lock is released by its `key`, not by this id.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * The token the holder chose when taking the lock. Present it again to activate, apply or release; a different key is refused with 409.
     */
    public function withKey(): self {
        $this->fields['key'] = true;

        return $this;
    }

    /**
     * When the lock was taken.
     */
    public function withLockedAt(): self {
        $this->fields['locked_at'] = true;

        return $this;
    }

    /**
     * When the lock lapses on its own; after that it no longer blocks anyone and is no longer listed.
     */
    public function withExpiresAt(): self {
        $this->fields['expires_at'] = true;

        return $this;
    }

    /**
     * The locked voucher, in full.
     */
    public function withVoucher(VoucherApiFieldConfig $config): self {
        $this->fields['voucher'] = $config;

        return $this;
    }
}
