<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\FieldConfig\Category;

use Simplia\Api\FieldConfig\AbstractApiFieldConfig;

/**
 * Which properties of a CategoryReferenceApiEntity to fetch.
 */
final class CategoryReferenceApiFieldConfig extends AbstractApiFieldConfig {
    /**
     * Numeric identifier of the category; the value the `category` filter of `GET /products` takes.
     */
    public function withId(): self {
        $this->fields['id'] = true;

        return $this;
    }

    /**
     * Category name in the request language. Null when the category has no text in that language.
     */
    public function withName(): self {
        $this->fields['name'] = true;

        return $this;
    }

    /**
     * Names of the category and its ancestors, root first, joined by `|`, such as `Phones|Apple|iPhone`. An ancestor without a name in the request language leaves an empty segment.
     */
    public function withPath(): self {
        $this->fields['path'] = true;

        return $this;
    }

    /**
     * Identifiers of the category and its ancestors, root first, this category last; one entry per segment of `path`.
     */
    public function withPathIds(): self {
        $this->fields['path_ids'] = true;

        return $this;
    }
}
