<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api;

use Psr\Http\Client\ClientInterface;
use Simplia\Api\Endpoint\AdminsApiEndpoint;
use Simplia\Api\Endpoint\ArticlesApiEndpoint;
use Simplia\Api\Endpoint\AttributesApiEndpoint;
use Simplia\Api\Endpoint\AvailabilitiesApiEndpoint;
use Simplia\Api\Endpoint\BrandsApiEndpoint;
use Simplia\Api\Endpoint\CashRegistersApiEndpoint;
use Simplia\Api\Endpoint\CategoriesApiEndpoint;
use Simplia\Api\Endpoint\CommentsApiEndpoint;
use Simplia\Api\Endpoint\ContentGroupsApiEndpoint;
use Simplia\Api\Endpoint\DocumentsApiEndpoint;
use Simplia\Api\Endpoint\EmailApiEndpoint;
use Simplia\Api\Endpoint\LabelsApiEndpoint;
use Simplia\Api\Endpoint\LogisticPlansApiEndpoint;
use Simplia\Api\Endpoint\MeApiEndpoint;
use Simplia\Api\Endpoint\OrderItemsApiEndpoint;
use Simplia\Api\Endpoint\OrdersApiEndpoint;
use Simplia\Api\Endpoint\PackagesApiEndpoint;
use Simplia\Api\Endpoint\PaymentMethodsApiEndpoint;
use Simplia\Api\Endpoint\PaymentsApiEndpoint;
use Simplia\Api\Endpoint\PricingsApiEndpoint;
use Simplia\Api\Endpoint\ProductsApiEndpoint;
use Simplia\Api\Endpoint\QuestionsApiEndpoint;
use Simplia\Api\Endpoint\ReviewsApiEndpoint;
use Simplia\Api\Endpoint\StockItemsApiEndpoint;
use Simplia\Api\Endpoint\StockRoomsApiEndpoint;
use Simplia\Api\Endpoint\StorageCentersApiEndpoint;
use Simplia\Api\Endpoint\StorageLocationsApiEndpoint;
use Simplia\Api\Endpoint\StoresApiEndpoint;
use Simplia\Api\Endpoint\SuppliersApiEndpoint;
use Simplia\Api\Endpoint\TextPagesApiEndpoint;
use Simplia\Api\Endpoint\TransportMethodsApiEndpoint;
use Simplia\Api\Endpoint\UserGroupsApiEndpoint;
use Simplia\Api\Endpoint\UsersApiEndpoint;
use Simplia\Api\Endpoint\VariantsApiEndpoint;
use Simplia\Api\Endpoint\VoucherGroupsApiEndpoint;
use Simplia\Api\Endpoint\VouchersApiEndpoint;

/**
 * The entry point: one credential, one endpoint object per resource.
 * Build it with withUsernameAuth() (HTTP Basic: API login and key) or withJWT() (an integration token).
 */
final class Api {
    private readonly RequestHandler $client;

    private function __construct(RequestHandler $client) {
        $this->client = $client;
    }

    /**
     * HTTP Basic with the API login and its key.
     */
    public static function withUsernameAuth(
        ClientInterface $client,
        string $hostname,
        string $username,
        #[\SensitiveParameter]
        string $password,
    ): self {
        return new self(new RequestHandler($client, $hostname, 'Basic ' . base64_encode($username . ':' . $password)));
    }

    /**
     * A Bearer integration token. The token is base64-wrapped on the wire, which is what the shop's authenticator decodes.
     */
    public static function withJWT(
        ClientInterface $client,
        string $hostname,
        #[\SensitiveParameter]
        string $jwt,
    ): self {
        return new self(new RequestHandler($client, $hostname, 'Bearer ' . base64_encode($jwt)));
    }

    public function getAdminsEndpoint(): AdminsApiEndpoint {
        return new AdminsApiEndpoint($this->client);
    }

    public function getArticlesEndpoint(): ArticlesApiEndpoint {
        return new ArticlesApiEndpoint($this->client);
    }

    public function getAttributesEndpoint(): AttributesApiEndpoint {
        return new AttributesApiEndpoint($this->client);
    }

    public function getAvailabilitiesEndpoint(): AvailabilitiesApiEndpoint {
        return new AvailabilitiesApiEndpoint($this->client);
    }

    public function getBrandsEndpoint(): BrandsApiEndpoint {
        return new BrandsApiEndpoint($this->client);
    }

    public function getCashRegistersEndpoint(): CashRegistersApiEndpoint {
        return new CashRegistersApiEndpoint($this->client);
    }

    public function getCategoriesEndpoint(): CategoriesApiEndpoint {
        return new CategoriesApiEndpoint($this->client);
    }

    public function getCommentsEndpoint(): CommentsApiEndpoint {
        return new CommentsApiEndpoint($this->client);
    }

    public function getContentGroupsEndpoint(): ContentGroupsApiEndpoint {
        return new ContentGroupsApiEndpoint($this->client);
    }

    public function getDocumentsEndpoint(): DocumentsApiEndpoint {
        return new DocumentsApiEndpoint($this->client);
    }

    public function getEmailEndpoint(): EmailApiEndpoint {
        return new EmailApiEndpoint($this->client);
    }

    public function getLabelsEndpoint(): LabelsApiEndpoint {
        return new LabelsApiEndpoint($this->client);
    }

    public function getLogisticPlansEndpoint(): LogisticPlansApiEndpoint {
        return new LogisticPlansApiEndpoint($this->client);
    }

    public function getMeEndpoint(): MeApiEndpoint {
        return new MeApiEndpoint($this->client);
    }

    public function getOrderItemsEndpoint(): OrderItemsApiEndpoint {
        return new OrderItemsApiEndpoint($this->client);
    }

    public function getOrdersEndpoint(): OrdersApiEndpoint {
        return new OrdersApiEndpoint($this->client);
    }

    public function getPackagesEndpoint(): PackagesApiEndpoint {
        return new PackagesApiEndpoint($this->client);
    }

    public function getPaymentMethodsEndpoint(): PaymentMethodsApiEndpoint {
        return new PaymentMethodsApiEndpoint($this->client);
    }

    public function getPaymentsEndpoint(): PaymentsApiEndpoint {
        return new PaymentsApiEndpoint($this->client);
    }

    public function getPricingsEndpoint(): PricingsApiEndpoint {
        return new PricingsApiEndpoint($this->client);
    }

    public function getProductsEndpoint(): ProductsApiEndpoint {
        return new ProductsApiEndpoint($this->client);
    }

    public function getQuestionsEndpoint(): QuestionsApiEndpoint {
        return new QuestionsApiEndpoint($this->client);
    }

    public function getReviewsEndpoint(): ReviewsApiEndpoint {
        return new ReviewsApiEndpoint($this->client);
    }

    public function getStockItemsEndpoint(): StockItemsApiEndpoint {
        return new StockItemsApiEndpoint($this->client);
    }

    public function getStockRoomsEndpoint(): StockRoomsApiEndpoint {
        return new StockRoomsApiEndpoint($this->client);
    }

    public function getStorageCentersEndpoint(): StorageCentersApiEndpoint {
        return new StorageCentersApiEndpoint($this->client);
    }

    public function getStorageLocationsEndpoint(): StorageLocationsApiEndpoint {
        return new StorageLocationsApiEndpoint($this->client);
    }

    public function getStoresEndpoint(): StoresApiEndpoint {
        return new StoresApiEndpoint($this->client);
    }

    public function getSuppliersEndpoint(): SuppliersApiEndpoint {
        return new SuppliersApiEndpoint($this->client);
    }

    public function getTextPagesEndpoint(): TextPagesApiEndpoint {
        return new TextPagesApiEndpoint($this->client);
    }

    public function getTransportMethodsEndpoint(): TransportMethodsApiEndpoint {
        return new TransportMethodsApiEndpoint($this->client);
    }

    public function getUserGroupsEndpoint(): UserGroupsApiEndpoint {
        return new UserGroupsApiEndpoint($this->client);
    }

    public function getUsersEndpoint(): UsersApiEndpoint {
        return new UsersApiEndpoint($this->client);
    }

    public function getVariantsEndpoint(): VariantsApiEndpoint {
        return new VariantsApiEndpoint($this->client);
    }

    public function getVoucherGroupsEndpoint(): VoucherGroupsApiEndpoint {
        return new VoucherGroupsApiEndpoint($this->client);
    }

    public function getVouchersEndpoint(): VouchersApiEndpoint {
        return new VouchersApiEndpoint($this->client);
    }
}
