<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * The complete part list of a bundle. Replaces what is there: parts not listed are removed. To empty a bundle use DELETE, not an empty list.
 */
final class BundleApiInput extends AbstractApiInput {
    /**
     * @param list<BundlePartApiInput> $parts The parts, at least one, each stock item once.
     */
    public function __construct(array $parts) {
        self::validateArray($parts, BundlePartApiInput::class);
        $this->params['parts'] = $parts;
    }
}
