<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Input;

/**
 * One part of a bundle: which stock item and how many of it go into one bundle.
 */
final class BundlePartApiInput extends AbstractApiInput {
    /**
     * Identifier of the stock item used as the part (StockItem.id). An unknown or repeated id is a 422 violation at parts[N].stock_item_id.
     */
    public function setStockItemId(?int $stockItemId): self {
        $this->params['stock_item_id'] = $stockItemId;

        return $this;
    }

    /**
     * How many of the part go into one unit of the bundle, at least 1.
     */
    public function setQuantity(?int $quantity): self {
        $this->params['quantity'] = $quantity;

        return $this;
    }
}
