<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Re-prices some or all lines of a stock document. Lines not listed keep their price.
 */
final class DocumentItemPricesApiInput extends AbstractApiInput {
    /**
     * @param list<DocumentItemPriceApiInput> $items The lines to re-price, at least one. Violations across all lines are answered together as one 422.
     */
    public function __construct(array $items) {
        self::validateArray($items, DocumentItemPriceApiInput::class);
        $this->params['items'] = $items;
    }
}
