<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Input\AbstractApiInput;

class DocumentItemPriceApiInput extends AbstractApiInput {
    public function setId(int $id): self {
        $this->params['id'] = $id;

        return $this;
    }

    public function setPrice(float $price): self {
        $this->params['price'] = $price;

        return $this;
    }

    public function setVatRate(float $vatRate): self {
        $this->params['vat_rate'] = $vatRate;

        return $this;
    }
}
