<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * One file attached to an e-mail.
 */
final class EmailAttachmentApiInput extends AbstractApiInput {
    /**
     * @param string $name File name the recipient sees.
     * @param string $bodyBase64 The file's bytes as standard base64, without a data: prefix and not double-encoded.
     * @param string $contentType MIME type of the file, such as `application/pdf`. Not validated.
     */
    public function __construct(string $name, string $bodyBase64, string $contentType) {
        $this->params['name'] = $name;
        $this->params['body_base64'] = $bodyBase64;
        $this->params['content_type'] = $contentType;
    }
}
