<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * One HTML e-mail to one recipient, optionally with attachments, sent from the shop's configured sender address. Nothing is stored: the message is not attached to any customer or order.
 */
final class EmailSendApiInput extends AbstractApiInput {
    /**
     * @param string $recipient The recipient's e-mail address, a single bare address such as `user@example.com`: no display name, no list, no cc or bcc.
     * @param string $subject Subject of the message.
     * @param string $htmlBody Body of the message, as HTML. There is no plain-text alternative.
     */
    public function __construct(string $recipient, string $subject, string $htmlBody) {
        $this->params['recipient'] = $recipient;
        $this->params['subject'] = $subject;
        $this->params['html_body'] = $htmlBody;
    }

    /**
     * Files to attach. No declared limit on count or size.
     * @param list<EmailAttachmentApiInput> $attachments
     */
    public function setAttachments(array $attachments): self {
        self::validateArray($attachments, EmailAttachmentApiInput::class);
        $this->params['attachments'] = $attachments;

        return $this;
    }
}
