<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class EmailMessageTypeApiInput extends AbstractApiInput {
    public function setRecipient(string $recipient): self {
        $this->params['recipient'] = $recipient;

        return $this;
    }

    public function setSubject(string $subject): self {
        $this->params['subject'] = $subject;

        return $this;
    }

    public function setHtmlBody(string $htmlBody): self {
        $this->params['html_body'] = $htmlBody;

        return $this;
    }

    /**
     * @param EmailAttachmentTypeApiInput[] $attachments
     * @return $this
     */
    public function setAttachments(array $attachments): self {
        self::validateArray($attachments, EmailAttachmentTypeApiInput::class);
        $this->params['attachments'] = $attachments;

        return $this;
    }
}
