<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Input;

/**
 * One file attached to an e-mail.
 */
final class EmailAttachmentApiInput extends AbstractApiInput {
    /**
     * File name the recipient sees.
     */
    public function setName(?string $name): self {
        $this->params['name'] = $name;

        return $this;
    }

    /**
     * The file's bytes as standard base64, without a data: prefix and not double-encoded.
     */
    public function setBodyBase64(?string $bodyBase64): self {
        $this->params['body_base64'] = $bodyBase64;

        return $this;
    }

    /**
     * MIME type of the file, such as `application/pdf`. Not validated.
     */
    public function setContentType(?string $contentType): self {
        $this->params['content_type'] = $contentType;

        return $this;
    }
}
