<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class ImageUploadTypeApiInput extends AbstractApiInput {
    public function setBodyBase64(string $bodyBase64): self {
        $this->params['body_base64'] = $bodyBase64;

        return $this;
    }

    public function setDescription(string $description): self {
        $this->params['description'] = $description;

        return $this;
    }
}
