<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class OrderDeliveryTypeApiInput extends AbstractApiInput {
    public function setTransportMethodId(int $transportMethodId): self {
        $this->params['transport_method_id'] = $transportMethodId;

        return $this;
    }

    public function setTransportPrice(float $transportPrice): self {
        $this->params['transport_price'] = $transportPrice;

        return $this;
    }

    public function setPaymentVatRate(float $paymentVatRate): self {
        $this->params['payment_vat_rate'] = $paymentVatRate;

        return $this;
    }

    public function setPaymentMethodId(int $paymentMethodId): self {
        $this->params['payment_method_id'] = $paymentMethodId;

        return $this;
    }

    public function setPaymentPrice(float $paymentPrice): self {
        $this->params['payment_price'] = $paymentPrice;

        return $this;
    }
}
