<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class OrderCreateTypeApiInput extends AbstractApiInput {
    /**
     * @param OrderItemTypeApiInput[] $items
     * @return $this
     */
    public function setItems(array $items): self {
        self::validateArray($items, OrderItemTypeApiInput::class);
        $this->params['items'] = $items;

        return $this;
    }

    public function setDeliveryAddress(AddressTypeApiInput $deliveryAddress): self {
        $this->params['delivery_address'] = $deliveryAddress;

        return $this;
    }

    public function setInvoiceAddress(AddressTypeApiInput $invoiceAddress): self {
        $this->params['invoice_address'] = $invoiceAddress;

        return $this;
    }

    public function setCustomerNote(string $customerNote): self {
        $this->params['customer_note'] = $customerNote;

        return $this;
    }

    public function setTransportMethodId(int $transportMethodId): self {
        $this->params['transport_method_id'] = $transportMethodId;

        return $this;
    }

    public function setTransportPrice(float $transportPrice): self {
        $this->params['transport_price'] = $transportPrice;

        return $this;
    }

    public function setPaymentMethodId(int $paymentMethodId): self {
        $this->params['payment_method_id'] = $paymentMethodId;

        return $this;
    }

    public function setPaymentPrice(float $paymentPrice): self {
        $this->params['payment_price'] = $paymentPrice;

        return $this;
    }
}
