<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Input;

/**
 * Creates one customer order: the lines, the addresses, how it ships and is paid, and optional links to a store, a storage center and a customer account. The order starts in the unprocessed status; the answer is the full order with its number assigned.
 */
final class OrderCreateApiInput extends AbstractApiInput {
    /**
     * Your own identifier for the order, such as an ERP or marketplace order number. Returned as `Order.external_code`. An empty string is ignored.
     */
    public function setExternalCode(?string $externalCode): self {
        $this->params['external_code'] = $externalCode;

        return $this;
    }

    /**
     * The order lines, at least one.
     * @param list<OrderItemApiInput> $items
     */
    public function setItems(array $items): self {
        self::validateArray($items, OrderItemApiInput::class);
        $this->params['items'] = $items;

        return $this;
    }

    /**
     * Where the goods go. Returned as `Order.delivery_address`. When only `invoice_address` is sent, that address is used for delivery as well.
     */
    public function setDeliveryAddress(?OrderAddressApiInput $deliveryAddress): self {
        $this->params['delivery_address'] = $deliveryAddress;

        return $this;
    }

    /**
     * Who is billed, when different from the delivery address; send it together with `delivery_address`. Omitted or empty, the delivery address is used for billing too. A `company_vat_id` here can change the order's VAT where the shop applies EU reverse charge, and the VAT registry may replace the company name and VAT id with its own values.
     */
    public function setInvoiceAddress(?OrderAddressApiInput $invoiceAddress): self {
        $this->params['invoice_address'] = $invoiceAddress;

        return $this;
    }

    /**
     * How the order ships and is paid: the transport and payment methods with their prices.
     */
    public function setDelivery(?OrderDeliveryApiInput $delivery): self {
        $this->params['delivery'] = $delivery;

        return $this;
    }

    /**
     * Identifier of the store where the customer collects the order (`Store.id`). Allowed only with a personal-pickup transport method; otherwise, or for an unknown id, a 422 violation. Returned as `Order.store`.
     */
    public function setStoreId(int $storeId): self {
        $this->params['store_id'] = $storeId;

        return $this;
    }

    /**
     * Identifier of the store the order is entered at, for an order created at a point of sale (`Store.id`). An unknown id is a 422 violation. Returned as `Order.created_store`.
     */
    public function setCreatedStoreId(int $createdStoreId): self {
        $this->params['created_store_id'] = $createdStoreId;

        return $this;
    }

    /**
     * Identifier of the storage center that fulfills the order (`StorageCenter.id`). Omit to let the shop choose. An unknown id is a 422 violation. Returned as `Order.storage_center`.
     */
    public function setStorageCenterId(int $storageCenterId): self {
        $this->params['storage_center_id'] = $storageCenterId;

        return $this;
    }

    /**
     * Identifier of the registered customer account to link the order to (`User.id`). Omit for a guest order. An unknown id is a 422 violation. Returned as `Order.user`.
     */
    public function setUserId(int $userId): self {
        $this->params['user_id'] = $userId;

        return $this;
    }

    /**
     * The note the customer wrote with the order. Returned as `Order.note`. An empty string is ignored.
     */
    public function setCustomerNote(?string $customerNote): self {
        $this->params['customer_note'] = $customerNote;

        return $this;
    }

    /**
     * Note to print on the invoice. Returned as `Order.invoice_note`. An empty string is ignored.
     */
    public function setInvoiceNote(?string $invoiceNote): self {
        $this->params['invoice_note'] = $invoiceNote;

        return $this;
    }

    /**
     * Payment reference (variable symbol) to store on the order; 0 is ignored. Not returned by any read: `Order.variable_symbol` is always derived from the order number.
     */
    public function setVariableSymbol(?int $variableSymbol): self {
        $this->params['variable_symbol'] = $variableSymbol;

        return $this;
    }

    /**
     * Whether to send the customer the order confirmation e-mail, and the shop its new-order notification, where the shop has confirmations enabled. Default false. Not returned by any read.
     */
    public function setSendConfirmationEmail(bool $sendConfirmationEmail): self {
        $this->params['send_confirmation_email'] = $sendConfirmationEmail;

        return $this;
    }
}
