<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Money;

/**
 * How a new order ships and is paid: the transport and payment methods and what the customer is charged for each. Both methods are required. The two charges are added into the order's single delivery price and must carry the same VAT rate; two different rates are a 422 violation on `payment_vat_rate` — post a payment fee at its own rate as an order line.
 */
final class OrderDeliveryApiInput extends AbstractApiInput {
    /**
     * Identifier of the transport method (`TransportMethod.id`); also sets the order's carrier. Required; an unknown id is a 422 violation.
     */
    public function setTransportMethodId(int $transportMethodId): self {
        $this->params['transport_method_id'] = $transportMethodId;

        return $this;
    }

    /**
     * What the customer pays for shipping, including VAT, in the same currency as every other price in the request.
     */
    public function setTransportPrice(?Money $transportPrice): self {
        $this->params['transport_price'] = $transportPrice;

        return $this;
    }

    /**
     * VAT rate of the shipping charge, as a percentage (21 for 21 %). Not returned by any read.
     */
    public function setTransportVatRate(?float $transportVatRate): self {
        $this->params['transport_vat_rate'] = $transportVatRate;

        return $this;
    }

    /**
     * Identifier of the payment method (`PaymentMethod.id`); also sets `Order.payment_type`. Required; an unknown id is a 422 violation.
     */
    public function setPaymentMethodId(int $paymentMethodId): self {
        $this->params['payment_method_id'] = $paymentMethodId;

        return $this;
    }

    /**
     * Surcharge for the payment method, typically the cash-on-delivery fee, including VAT, in the same currency as every other price in the request; `0.00` when free.
     */
    public function setPaymentPrice(?Money $paymentPrice): self {
        $this->params['payment_price'] = $paymentPrice;

        return $this;
    }

    /**
     * VAT rate of the payment surcharge, as a percentage (21 for 21 %). Not returned by any read. Must equal `transport_vat_rate`.
     */
    public function setPaymentVatRate(?float $paymentVatRate): self {
        $this->params['payment_vat_rate'] = $paymentVatRate;

        return $this;
    }
}
