<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * A postal address with contact details for a new order. Every field is optional; the address counts as given when at least one field is set.
 */
final class OrderAddressApiInput extends AbstractApiInput {
    /** Wire name => setter, for every property the schema requires. */
    public const REQUIRED = [];

    /**
     * Given name of the recipient or contact.
     */
    public function setFirstName(?string $firstName): self {
        $this->params['first_name'] = $firstName;

        return $this;
    }

    /**
     * Family name of the recipient or contact.
     */
    public function setLastName(?string $lastName): self {
        $this->params['last_name'] = $lastName;

        return $this;
    }

    /**
     * Street and house number.
     */
    public function setStreet(?string $street): self {
        $this->params['street'] = $street;

        return $this;
    }

    /**
     * Town or city.
     */
    public function setCity(?string $city): self {
        $this->params['city'] = $city;

        return $this;
    }

    /**
     * State, province or county, where the destination country uses one.
     */
    public function setRegion(?string $region): self {
        $this->params['region'] = $region;

        return $this;
    }

    /**
     * Postal code, stored as sent.
     */
    public function setZip(?string $zip): self {
        $this->params['zip'] = $zip;

        return $this;
    }

    /**
     * Country as a two-letter code (ISO 3166-1 alpha-2), in any letter case; stored and returned in lower case. Not validated.
     */
    public function setCountry(?string $country): self {
        $this->params['country'] = $country;

        return $this;
    }

    /**
     * Contact e-mail address, where order and status e-mails go.
     */
    public function setEmail(?string $email): self {
        $this->params['email'] = $email;

        return $this;
    }

    /**
     * Contact phone number, stored as sent.
     */
    public function setPhone(?string $phone): self {
        $this->params['phone'] = $phone;

        return $this;
    }

    /**
     * Company name, when ordering as a business.
     */
    public function setCompanyName(?string $companyName): self {
        $this->params['company_name'] = $companyName;

        return $this;
    }

    /**
     * Company registration number in the national business register (Czech IČO). Not the VAT number.
     */
    public function setCompanyId(?string $companyId): self {
        $this->params['company_id'] = $companyId;

        return $this;
    }

    /**
     * VAT identification number (Czech DIČ, EU VAT id), such as `CZ27082440`.
     */
    public function setCompanyVatId(?string $companyVatId): self {
        $this->params['company_vat_id'] = $companyVatId;

        return $this;
    }
}
