<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Moves an order to another status, optionally telling the customer.
 */
final class OrderStatusApiInput extends AbstractApiInput {
    /**
     * The status to move the order to: `unprocessed`, `processed`, `waiting`, `ready`, `finished` or `cancelled`. Which transitions are allowed depends on the shop's configuration; a refused transition is a 409 and nothing changes. Moving to the current status changes nothing and answers 200.
     * @param 'unprocessed'|'processed'|'waiting'|'ready'|'finished'|'cancelled'|null $status
     */
    public function setStatus(?string $status): self {
        $this->params['status'] = $status;

        return $this;
    }

    /**
     * Whether to send the customer the e-mail for the new status. Default false. Sent even when the status did not change; 409 when the shop has no e-mail template for that status.
     */
    public function setSendInformationEmail(bool $sendInformationEmail): self {
        $this->params['send_information_email'] = $sendInformationEmail;

        return $this;
    }
}
