<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class OrderStatusTypeApiInput extends AbstractApiInput {
    public function setStatusId(int $statusId): self {
        $this->params['status_id'] = $statusId;

        return $this;
    }

    public function setSendInformationEmail(bool $sendInformationEmail): self {
        $this->params['send_information_email'] = $sendInformationEmail ? 'true' : 'false';

        return $this;
    }
}
