<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Sets how urgently the warehouse handles an order.
 */
final class OrderPriorityApiInput extends AbstractApiInput {
    /**
     * @param int $priority 0 normal, 1 important, 2 urgent, 3 emergency. Returned as `Order.priority`.
     */
    public function __construct(int $priority) {
        $this->params['priority'] = $priority;
    }
}
