<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Money;

/**
 * One price row: sets the price of one stock item in the addressed price list.
 */
final class PriceItemApiInput extends AbstractApiInput {
    /**
     * @param int $stockItemId Identifier of the stock item to price (`StockItem.id`). An unknown or repeated id is a 422 violation at `prices[i].stock_item_id`.
     * @param Money $value The list price to store, in the price list's currency; anything else is a 422 violation at `prices[i].value.currency`. `0` stores a zero price, it does not delete the row.
     */
    public function __construct(int $stockItemId, Money $value) {
        $this->params['stock_item_id'] = $stockItemId;
        $this->params['value'] = $value;
    }

    /**
     * The discounted price to store, in the price list's currency. Omit or send null to clear it.
     */
    public function setValueAfterDiscount(?Money $valueAfterDiscount): self {
        $this->params['value_after_discount'] = $valueAfterDiscount;

        return $this;
    }

    /**
     * First day of the discount window, as `YYYY-MM-DD` or a date-time whose time part is dropped. Omit or send an empty string to clear it.
     */
    public function setDiscountStartsAt(?\DateTimeInterface $discountStartsAt): self {
        $this->params['discount_starts_at'] = $discountStartsAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }

    /**
     * Last day of the discount window, as `YYYY-MM-DD` or a date-time whose time part is dropped. Omit or send an empty string to clear it.
     */
    public function setDiscountEndsAt(?\DateTimeInterface $discountEndsAt): self {
        $this->params['discount_ends_at'] = $discountEndsAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }
}
