<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * The prices to create or update in one price list, one row per stock item.
 */
final class PriceBatchApiInput extends AbstractApiInput {
    /**
     * The rows, 1 to 1000, each stock item once.
     * @param list<PriceItemApiInput> $prices
     */
    public function setPrices(array $prices): self {
        self::validateArray($prices, PriceItemApiInput::class);
        $this->params['prices'] = $prices;

        return $this;
    }
}
