<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * One line of a stock movement: which stock item and how many units.
 *
 * Required before sending: setStockItemId(), setQuantity(). A missing one throws IncompleteInputException at the endpoint call, before any request.
 */
final class StockDocumentItemApiInput extends AbstractApiInput {
    /** Wire name => setter, for every property the schema requires. */
    public const REQUIRED = ['stock_item_id' => 'setStockItemId', 'quantity' => 'setQuantity'];

    /**
     * Required. Identifier of the stock item to move (`StockItem.id`). An unknown id is a 422 violation at this line.
     */
    public function setStockItemId(int $stockItemId): self {
        $this->params['stock_item_id'] = $stockItemId;

        return $this;
    }

    /**
     * Required. Number of units to move, always positive; the document `type` gives the direction.
     */
    public function setQuantity(int $quantity): self {
        $this->params['quantity'] = $quantity;

        return $this;
    }
}
