<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * The fixed shelf position to assign a stock item to within a stock room.
 */
final class StockItemLocationApiInput extends AbstractApiInput {
    /**
     * Position code inside the stock room, as written on the shelf label; created when it does not exist yet. Returned as `storage_locations[].name`.
     */
    public function setName(?string $name): self {
        $this->params['name'] = $name;

        return $this;
    }
}
