<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Money;

/**
 * The changes to apply to one stock item. Send only the fields to change; a field that is absent or null is left as it is, so nothing can be cleared here.
 */
final class StockItemUpdateApiInput extends AbstractApiInput {
    /**
     * @param int $id Identifier of the stock item to change (`StockItem.id`). Required; an unknown id is a 422 violation at `items[i].id`.
     */
    public function __construct(int $id) {
        $this->params['id'] = $id;
    }

    /**
     * New undiscounted selling price of one unit including VAT, in the shop's main currency; anything else is a 422 violation at `items[i].full_price.currency`.
     */
    public function setFullPrice(?Money $fullPrice): self {
        $this->params['full_price'] = $fullPrice;

        return $this;
    }

    /**
     * New reference price shown struck through, including VAT, in the shop's main currency.
     */
    public function setOriginalPrice(?Money $originalPrice): self {
        $this->params['original_price'] = $originalPrice;

        return $this;
    }

    /**
     * New VAT rate as a percentage (21 for 21 %). Not returned by any read.
     */
    public function setVatRate(?float $vatRate): self {
        $this->params['vat_rate'] = $vatRate;

        return $this;
    }

    /**
     * New delivery promise in hours (`Availability.id`); 0 means in stock. On a shop with automatic availability it sets the promise used while the item is out of stock, so the value read back can differ.
     */
    public function setAvailabilityHours(?int $availabilityHours): self {
        $this->params['availability_hours'] = $availabilityHours;

        return $this;
    }

    /**
     * Date from which the item becomes available.
     */
    public function setAvailableAt(?\DateTimeInterface $availableAt): self {
        $this->params['available_at'] = $availableAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }

    /**
     * New barcode (EAN).
     */
    public function setEan(?string $ean): self {
        $this->params['ean'] = $ean;

        return $this;
    }

    /**
     * New percentage taken off `full_price` within the discount window. Wins over `discount_value`.
     */
    public function setDiscountPercentage(?float $discountPercentage): self {
        $this->params['discount_percentage'] = $discountPercentage;

        return $this;
    }

    /**
     * New shop-wide minimum stock of the item that demand planning keeps above. Not the per-room `StockLevel.minimum_quantity`, and not returned by any read.
     */
    public function setMinimumQuantity(?int $minimumQuantity): self {
        $this->params['minimum_quantity'] = $minimumQuantity;

        return $this;
    }

    /**
     * New fixed amount taken off `full_price` within the discount window, in the shop's main currency.
     */
    public function setDiscountValue(?Money $discountValue): self {
        $this->params['discount_value'] = $discountValue;

        return $this;
    }

    /**
     * First day of the discount window. Both bounds must be set for the discount to apply.
     */
    public function setDiscountStartsAt(?\DateTimeInterface $discountStartsAt): self {
        $this->params['discount_starts_at'] = $discountStartsAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }

    /**
     * Last day of the discount window. Both bounds must be set for the discount to apply.
     */
    public function setDiscountEndsAt(?\DateTimeInterface $discountEndsAt): self {
        $this->params['discount_ends_at'] = $discountEndsAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }

    /**
     * Identifier of the logistic plan to assign (`LogisticPlan.id`); an unknown id is a 422 violation. Not returned by any read.
     */
    public function setLogisticPlanId(?int $logisticPlanId): self {
        $this->params['logistic_plan_id'] = $logisticPlanId;

        return $this;
    }
}
