<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Creates and immediately posts one stock movement: goods received into a stock room or issued from it, one line per stock item. Answered with the created document.
 */
final class StockDocumentApiInput extends AbstractApiInput {
    /**
     * Document number to assign instead of the next number from the shop's sequence, at most 32 characters. Omit to let the shop number the document.
     */
    public function setCode(?string $code): self {
        $this->params['code'] = $code;

        return $this;
    }

    /**
     * Identifier of the stock room the goods move into or out of (`StockRoom.id`). An unknown id is a 422 violation.
     */
    public function setStockRoomId(?int $stockRoomId): self {
        $this->params['stock_room_id'] = $stockRoomId;

        return $this;
    }

    /**
     * Issue date to record instead of the moment of posting.
     */
    public function setIssuedAt(?\DateTimeInterface $issuedAt): self {
        $this->params['issued_at'] = $issuedAt?->format(\DateTimeInterface::ATOM);

        return $this;
    }

    /**
     * Direction of the movement: `stock_input` receives goods (stock goes up), `stock_output` issues them (stock goes down). No other document type can be created here.
     * @param 'stock_input'|'stock_output'|null $type
     */
    public function setType(?string $type): self {
        $this->params['type'] = $type;

        return $this;
    }

    /**
     * The movement lines, at least one. Send each stock item once: for a repeated item only the last line is kept and the earlier quantity is discarded.
     * @param list<StockDocumentItemApiInput> $items
     */
    public function setItems(array $items): self {
        self::validateArray($items, StockDocumentItemApiInput::class);
        $this->params['items'] = $items;

        return $this;
    }
}
