<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Input\AbstractApiInput;

class StockDocumentItemTypeApiInput extends AbstractApiInput {
    public function setItemId(string $itemId): self {
        $this->params['item_id'] = $itemId;

        return $this;
    }

    public function setQuantity(float $quantity): self {
        $this->params['quantity'] = $quantity;

        return $this;
    }
}
