<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class StockItemLocationTypeApiInput extends AbstractApiInput {
    public function setName(string $name): self {
        $this->params['name'] = $name;

        return $this;
    }
}
