<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Applies changes to many stock items in one transaction. Answered with the updated items, one per input item in input order.
 */
final class StockItemBatchUpdateApiInput extends AbstractApiInput {
    /**
     * The items to change, at least one. Violations across all items are answered together as one 422.
     * @param list<StockItemUpdateApiInput> $items
     */
    public function setItems(array $items): self {
        self::validateArray($items, StockItemUpdateApiInput::class);
        $this->params['items'] = $items;

        return $this;
    }
}
