<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * One line of a stock movement: which stock item and how many units.
 */
final class StockDocumentItemApiInput extends AbstractApiInput {
    /**
     * @param int $stockItemId Identifier of the stock item to move (`StockItem.id`). An unknown id is a 422 violation at this line.
     * @param int $quantity Number of units to move, always positive; the document `type` gives the direction.
     */
    public function __construct(int $stockItemId, int $quantity) {
        $this->params['stock_item_id'] = $stockItemId;
        $this->params['quantity'] = $quantity;
    }
}
