<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

use Simplia\Api\Input\AbstractApiInput;

class TextPageApiInput extends AbstractApiInput {
    public function setId(int $id): self {
        $this->params['id'] = $id;

        return $this;
    }

    public function setName(string $name): self {
        $this->params['name'] = $name;

        return $this;
    }

    public function setText(string $text): self {
        $this->params['text'] = $text;

        return $this;
    }
}
