<?php

/**
 * !!! AUTOGENERATED FROM OPENAPI SPECIFICATION
 * !!! DON'T EDIT AND DON'T SEND PULL REQUESTS DIRECTLY FOR THIS FILE
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

class UserApiInput extends AbstractApiInput {
    public function setId(int $id): self {
        $this->params['id'] = $id;

        return $this;
    }

    public function setEmail(string $email): self {
        $this->params['email'] = $email;

        return $this;
    }

    public function setDeliveryAddress(ContactApiInput $deliveryAddress): self {
        $this->params['delivery_address'] = $deliveryAddress;

        return $this;
    }

    public function setInvoiceAddress(ContactApiInput $invoiceAddress): self {
        $this->params['invoice_address'] = $invoiceAddress;

        return $this;
    }

    public function setLoyaltyCard(string $loyaltyCard): self {
        $this->params['loyalty_card'] = $loyaltyCard;

        return $this;
    }

    public function setWholesale(bool $wholesale): self {
        $this->params['wholesale'] = $wholesale ? 'true' : 'false';

        return $this;
    }

    public function setDiscountPercentage(float $discountPercentage): self {
        $this->params['discount_percentage'] = $discountPercentage;

        return $this;
    }

    public function setPointsFactor(string $pointsFactor): self {
        $this->params['points_factor'] = $pointsFactor;

        return $this;
    }

    public function setUserGroup(UserGroupApiInput $userGroup): self {
        $this->params['user_group'] = $userGroup;

        return $this;
    }
}
