<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Input;

use Simplia\Api3\Money;

/**
 * Changes the name, code, barcode or price of a variant. Send only the fields to change; a field that is absent or null is left as it is.
 */
final class VariantUpdateApiInput extends AbstractApiInput {
    /**
     * New option value of the variant.
     */
    public function setName(?string $name): self {
        $this->params['name'] = $name;

        return $this;
    }

    /**
     * New code (SKU) of the variant's stock item. An empty string clears it.
     */
    public function setCode(?string $code): self {
        $this->params['code'] = $code;

        return $this;
    }

    /**
     * New barcode (EAN). An empty string clears it.
     */
    public function setEan(?string $ean): self {
        $this->params['ean'] = $ean;

        return $this;
    }

    /**
     * New catalog price including VAT, in the shop's main currency; anything else is a 422 violation at price.currency. When it differs from the product's price, the product switches to per-variant pricing.
     */
    public function setPrice(?Money $price): self {
        $this->params['price'] = $price;

        return $this;
    }
}
