<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api3\Input;

/**
 * Takes a lock on a voucher code for a chosen number of seconds.
 */
final class VoucherLockApiInput extends AbstractApiInput {
    /**
     * A token you choose to identify the holder of the lock, such as a till or session identifier. Present it again to activate, apply or release. Locking again with the same key replaces your own lock.
     */
    public function setKey(?string $key): self {
        $this->params['key'] = $key;

        return $this;
    }

    /**
     * How long the lock lasts, in seconds, from 30 to 604800 (7 days).
     */
    public function setTtl(?int $ttl): self {
        $this->params['ttl'] = $ttl;

        return $this;
    }
}
