<?php

/**
 * !!! AUTOGENERATED FROM THE /api/3 OPENAPI DOCUMENT BY api3:sdk:generate
 * !!! DO NOT EDIT — change the generator (src/Api/Sdk in the shop repository) instead
 */

declare(strict_types=1);

namespace Simplia\Api\Input;

/**
 * Proof of holding the lock on a voucher code, when one is held.
 */
final class VoucherKeyApiInput extends AbstractApiInput {
    /** Wire name => setter, for every property the schema requires. */
    public const REQUIRED = [];

    /**
     * The key of the lock you hold on the code. Omit when no lock is held. A live lock held under another key answers 409; your own lock is released by the call.
     */
    public function setKey(?string $key): self {
        $this->params['key'] = $key;

        return $this;
    }

    /**
     * Accepted but not stored.
     */
    public function setNote(?string $note): self {
        $this->params['note'] = $note;

        return $this;
    }
}
